### ISSUE TITLE
Add support for several filters in one filter set

### ISSUE THREAD

**Issue by ghost** [liip/LiipImagineBundle#1]
Currently in configuration we can specify only one filter in filter set. E.g.:

```
liip_imagine:
    filters:
        my_thumb:
            type:    thumbnail
            options: { size: [120, 90], mode: outbound }
```

We should allow specifiying several filters in one filter set (e.g. resize the image and add watermark). For example:

```
liip_imagine:
    filters:
        my_thumb:
            thumbnail:
                options: { size: [120, 90], mode: outbound }
            other_filter: ~
            other_filter2: ~
```

What do you think?
