### ISSUE TITLE
AWS Missing version

### ISSUE THREAD

**Issue by rsaenen** [liip/LiipImagineBundle#1000]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1
| AWS Version | 3.36

Hi,
According to the following documentation:
http://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolver/aws_s3.html

I got the following error:
```
Missing required client configuration options: 

version: (string)

A "version" configuration value is required. Specifying a version constraint
ensures that your code will not be affected by a breaking change made to the
service. For example, when using Amazon S3, you can lock your API version to
"2006-03-01".
````

Here's my configuration
```yml
liip_imagine:
    resolvers:
        profile_uploads:
            aws_s3:
                client_config:
                    credentials:
                        key:    "%amazon.s3.key%"
                        secret: "%amazon.s3.secret%"
                    region: "%amazon.s3.region%"
                    # The version is not in the documentation
                    version: "2006-03-01"
                # I saw the other issue about bucket position
                bucket: "%amazon.s3.bucket%"
                get_options:
                    Scheme: https
                put_options:
                    CacheControl: "max-age=86400"
```

**Comment by rsaenen** [comment]
Fixed with:
```yml
services:
    app.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                credentials: { key: "%amazon.s3.key%", secret: "%amazon.s3.secret%" }
                region: "%amazon.s3.region%"
                # ADD VERSION !
                version: "%amazon.s3.version%"

    app.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@app.amazon_s3"
            - "%amazon.s3.bucket%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "amazon_s3" }
```

Hope this will help.

**Comment by robfrawley** [comment]
@rsaenen Is there something we should clarify in the documentation?

**Comment by rsaenen** [comment]
Yes, here's the current documentation in order to create resolver as a service:
```yml

services:
    acme.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                credentials: { key: "%amazon.s3.key%", secret: "%amazon.s3.secret%" }
                region: "%amazon.s3.region%"

    acme.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@acme.amazon_s3"
            - "%amazon.s3.bucket%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "amazon_s3" }
```

However, we has to add the version of amazon s3 below the region (like in my previous post).
