### ISSUE TITLE
Images not resolved on Symfony 3.4

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#1001]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9,1

I'm using Symfony 3.4 (beta).
I'm getting 404s on URLs like `/media/cache/resolve/my_filter/uploads/media/my_image_59f36a7c68cbb6.02575514.jpg` (e.g. when the bundle is trying to resolve the thumbnail)

Routes are correctly registered, here are last 2 lines from `console de:ro`
```
  liip_imagine_filter_runtime   GET        ANY      ANY    /media/cache/resolve/{filter}/rc/{hash}/{path}  
  liip_imagine_filter           GET        ANY      ANY    /media/cache/resolve/{filter}/{path}  
```

If I try the following command, the thumbnail is generated: `console liip:i:c:res uploads/media/my_image_59f36a7c68cbb6.02575514.jpg` (so, the image is then displayed correctly). Of course, I can't generate all thumbnails by hand...

The following is the output of `console de:conf liip_imagine`
```
liip_imagine:
    driver: gd
    loaders:
        default:
            filesystem:
                data_root:
                    - /project/releases/20171027162742/public
                    - /project/releases/20171027162742/public
                    - /project/releases/20171027162742/../../shared/public
                locator: filesystem
                bundle_resources:
                    enabled: false
                    access_control_type: blacklist
                    access_control_list: {  }
    resolvers:
        default:
            web_path:
                web_root: /project/releases/20171027162742/src/../web
                cache_prefix: media/cache
    filter_sets:
        my_filter:
            quality: 80
            filters:
                thumbnail:
                    size:
                        - 200
                        - 150
                    mode: outbound
            jpeg_quality: null
            png_compression_level: null
            png_compression_filter: null
            format: null
            animated: false
            cache: null
            data_loader: null
            default_image: null
            post_processors: {  }
    cache: default
    cache_base_path: ''
    data_loader: default
    default_image: null
    controller:
        filter_action: 'liip_imagine.controller:filterAction'
        filter_runtime_action: 'liip_imagine.controller:filterRuntimeAction'
        redirect_response_code: 301
    enqueue: false

```

notice the wrong value for `web_root`, even if I configured it correctly to point to `public`. Anyway, I added a symlink `web -> public` without solving my issue

I checked permissions of all dirs in `public/media/cache/my_filter/uploads/media/` and everything is writable by web server.

_Edit_: I forgot to specify that problems are only in prod, in dev everything is working
