### ISSUE TITLE
How  extends WebPathResolver and register in config

### ISSUE THREAD

**Issue by vldivn** [liip/LiipImagineBundle#1008]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9

Hi! Can you please explain? How I can extends "WebPathResolver" for override method resolve, and remove domain from url? 
Becouse in cludflare https don't work correctly and all pictures loads by http. 
Thank you, have a nice day.

**Comment by sebastianblum** [comment]
Hello!

We do the same by 

```yaml
# Liip Imagine Bundle
parameters:
 
  liip_imagine.cache.resolver.web_path.class: AppBundle\Binary\CacheResolver\TerrafinanzCacheResolver

With Symfony 4.0 & Flex we use the service container to register an own resolver

**Comment by vldivn** [comment]
Hi, thank you fro your answer! 

I did as you said and everything okay.

God bless you <3

**Comment by pshirmanov** [comment]
Hello!
I use symfony 5 and "liip/imagine-bundle": "2.3.0"
I try extend WebPathResolver, but load bundle class used original, not my

**config/services.yaml**
```
parameters:
    liip_imagine.cache.resolver.prototype.web_path: App\Service\Imagine\Resolver

services:    
    App\Service\Imagine\Resolver:
        public: true
        abstract: true
        arguments:
            - '@filesystem'
            - '@router.request_context'
```

**src/Service/Imagine/Resolver.php**
```
<?php

namespace App\Service\Imagine;

use Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver;

class Resolver extends WebPathResolver
{
    /**
     * {@inheritdoc}
     */
    public function resolve($path, $filter)
    {
        /* my code */
    }
}
```

What am I doing wrong?
