### ISSUE TITLE
[Feature Request] AwsS3 :: Access Denied due ACL permission

### ISSUE THREAD

**Issue by jvahldick** [liip/LiipImagineBundle#1034]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | *

Hi guys,
I had some problems to generate the cache images directly into Amazon S3, which I was getting the error's message of "**Access Denied**".

I figured out that the problem was in reason of this:
https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/AwsS3Resolver.php#L120

```php
$this->storage->putObject(
    array_merge(
        $this->putOptions,
        [
            'ACL' => $this->acl, // Problematic line
            'Bucket' => $this->bucket,
            'Key' => $objectPath,
            'Body' => $binary->getContent(),
            'ContentType' => $binary->getMimeType(),
        ]
    )
);
```
It requires a special permission on IAM of the Amazon's user called PutObjectAcl.
Is possible to make this ACL parameter optional? I tried to send this parameter as empty to the resolver, but it seems required.

```php
->scalarNode('acl')
    ->defaultValue('public-read')
    ->cannotBeEmpty()
->end()
```

**Comment by cedricziel** [comment]
I don't know about the specific ACL, but can you try to switch the driver to AmazonS3? That one uses the Amazon SDK and should facilitate a correct client. Should be worth a try.

**Comment by jvahldick** [comment]
It is the one I am using.

```yaml
liip_imagine:
    resolvers:
        s3:
            ### Amazon S3
            aws_s3:
                client_config:
                    credentials:
                        key:    "%env(AWS_S3_KEY)%"
                        secret: "%env(AWS_S3_SECRET)%"
                    region: "%env(AWS_S3_REGION)%"
                    version: 'latest'
                bucket: "%env(AWS_S3_BUCKET)%"
                get_options:
                    Scheme: 'https'

    loaders:
        s3:
            flysystem:
                filesystem_service: oneup_flysystem.cct_filesystem

    driver: "gd"
    cache: s3
    data_loader: s3
```
