### ISSUE TITLE
Cache prefix is missing '/resolve' by default

### ISSUE THREAD

**Issue by proArtex** [liip/LiipImagineBundle#1037]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | yes/no
| RFC? | no
| Imagine Bundle Version | 2.0.x-dev

There is a config:
```
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

#    resolvers:
#        default:
#            web_path:
#                cache_prefix: 'custom_path'

    # define your filter sets under this option
    filter_sets:

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail:

            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~

                # strip the image of all metadata
                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'

```

WebPathResolver's $cachePrefix is 'media/cache' by default, but routing is:
```
liip_imagine_filter:
    path: /media/cache/resolve/{filter}/{path}
```
So it cause 404 "No route found ..." error with path 'media/cache/squared_thumbnail' instead of 'media/cache/resolve/squared_thumbnail'

**Comment by proArtex** [comment]
I've caught how it really works - 'resolve' is used to generate cache and redirect to cached image. So my problem was different loader's data_root and resolver's web_root. Should we take attention to that in doc?

Now it looks like:
```
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
...
```
