### ISSUE TITLE
RelativeResize on width and height?

### ISSUE THREAD

**Issue by gagarine** [liip/LiipImagineBundle#104]
Can you have multiple filter?

```
  filters:
                #thumbnail: { size: [1142, 650], mode: inbound }
                relative_resize: { heighten: 650 }
                relative_resize: { widen: 1142 }
```

I try to scale a picture to fit in a height and width but without crop (one side can be shorter but not longer).
