### ISSUE TITLE
Chaining custom data loader in config

### ISSUE THREAD

**Issue by olegrom** [liip/LiipImagineBundle#1060]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

Is there any way to add custom data loader to a chain in config.yml?

**Comment by robfrawley** [comment]
You would [create a custom loader](https://symfony.com/doc/current/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader) and then reference when [using the chain loader](https://symfony.com/doc/current/bundles/LiipImagineBundle/data-loader/chain.html) by using the value you specified in the custom loader service definition.

```
# app/config/services.yml

services:
    imagine.data.loader.my_custom:
        class: AppBundle\Imagine\Binary\Loader\MyCustomDataLoader
        arguments:
            - "@liip_imagine"
            - "%liip_imagine.formats%"
        tags:
            - { name: "liip_imagine.binary.loader", loader: my_custom_data_loader }
```

```yaml
# app/config/config.yml

liip_imagine:
    loaders:
        foo:
            filesystem:
                # configure filesystem loader

        bar:
            chain:
                loaders:
                    - foo
                    - my_custom_data_loader
```
