### ISSUE TITLE
Symfony 4 configuration 

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1074]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| Imagine Bundle Version | 2.0-dev

I'm sure this is something simple, but I'm stuck with the Symfony4 setup.  I'm running with bin/console server:run, and I can access my image (http://127.0.0.1:8000/photos/Facebook-temp/ZACA5563-21.thumb.jpg) , but the thumbnail doesn't work (http://127.0.0.1:8000/media/cache/resolve/squared_thumbnail/photos/Facebook-temp/ZACA5563-21.thumb.jpg)

and instead gives the error:

    Source image for path "photos/Facebook-temp/ZACA5563-21.thumb.jpg" could not be found

I'm sure it's something in the setup.  Symfony4 uses /public instead of /web, and I think root_dir has been changed to project_dir.  My imagine.yaml file looks like this:

```yaml
liip_imagine:
     # valid drivers options include "gd" or "gmagick" or "imagick"
     driver: "gd"

     resolvers:
       profile_photos:
          web_path:
            web_root: "%kernel.project_dir%/public"
            cache_prefix: "media/cache"

     # define your filter sets under this option
     filter_sets:

         # an example thumbnail transformation definition
         # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
         squared_thumbnail:

             # set your image quality defaults
             jpeg_quality:          85
```

I keep playing around with different paths and settings, but can't figure out what I'm doing wrong.
