### ISSUE TITLE
Cache write error, The object could not be created on Amazon S3

### ISSUE THREAD

**Issue by macthemaster** [liip/LiipImagineBundle#1079]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | x1.9

Hello, I spent a lot of time trying upload cache files to S3 but I couldn't.  I really need help with this. Because idk if is my mistake or a bug.

I'm using symfony 3.3.6 vichuploaderbundle + gaufrette to upload files to S3 and it works ok, but when I try to use Liip to get the thumbnails It doesn't save the files to the S3 (with file system works ok).

I ran "app/console liip:imagine:cache:resolve 5aa9ab70d8656297382768.jpg" and this is the error:

[liip/imagine-bundle] Resolve Image Caches
==========================================
 - 5aa9ab70d8656297382768.jpg[my_thumb1] failure: The object could not be created on Amazon S3.
 Completed 0 operations (1 filter / 1 image)   encountered 1 failure

Same error running from service or resolver.

services.yml==========================================================
```
services:    
    app.amazon.s3.credentials:
        class: Aws\Credentials\Credentials
        arguments: ["%amazon.s3.key%", "%amazon.s3.secret%"]

    app.amazon.s3:
        class: Aws\S3\S3Client
        arguments:
            -
                version: %amazon.s3.version%
                region: %amazon.s3.region%
                credentials: "@app.amazon.s3.credentials"

    app.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@app.amazon.s3"
            - "%amazon.s3.bucket%"
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'image_thumbnails_cache' }
```

config.yml===========================================================
```
vich_uploader:
    db_driver: orm    
    storage: gaufrette
    mappings:
        pacienteimage:
            uri_prefix:         https://s3.amazonaws.com/mybucket
 #           upload_destination: %kernel.root_dir%/../imagenes
            upload_destination: aws
            namer: vich_uploader.namer_uniqid

liip_imagine:
    loaders:
        foo:
            stream:
                # This refers to knp_gaufrette filesystems configuration
                wrapper: gaufrette://bar/
        aws:
            stream:
                wrapper: gaufrette://aws/
    resolvers:
            default:
                aws_s3:
                    client_config:
                        credentials:
                            key:    "%amazon.s3.key%"
                            secret: "%amazon.s3.secret%"
                        region: "%amazon.s3.region%"
                        version: "latest"
                    bucket: "%amazon.s3.bucket%"
                    get_options:
                        Scheme: https
                    put_options:
                        CacheControl: "max-age=86400"

    filter_sets :        
        my_thumb1 :
                    data_loader: aws
                    cache: image_thumbnails_cache      
                    quality : 75
                    filters :
                        thumbnail  : { size : [90, 90], mode : outbound }

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        profile_photos:
            aws_s3:
                service_id: 'app.amazon.s3'
                bucket_name: 'mybucket'
                detect_content_type: true
                options:
                    directory: 'media'
        foo:
            local:
                directory:  %kernel.root_dir%/../imagenes
                create:     true
    filesystems:
        bar:
            adapter:    foo
            alias:      foo_filesystem
        aws:
            adapter:    profile_photos
            alias:      aws_filesystem
```
