### ISSUE TITLE
Artifacts in pictures

### ISSUE THREAD

**Issue by peter-gribanov** [liip/LiipImagineBundle#1086]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

```yml
# liip_imagine.yml
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/web'
                cache_prefix: 'media/suit'
    loaders:
        default:
            filesystem:
                data_root: '%liip_imagine.data_root%'
    filter_sets:
        product_cover_card:
            quality: 75
            filters:
                scale: { dim: [937, 600] }
```

There are very strange artifacts in the pictures.

![1021716637.jpg](https://user-images.githubusercontent.com/1954436/39131571-71fa3ccc-4718-11e8-9947-9c698e3f5205.jpg)

It all started with the fact that we have some of the pictures, it's PNG and for optimization we decided to convert them to JPEG.

```yml
liip_imagine:
    filter_sets:
        product_cover_card:
            quality: 75
            format: jpg # change format
            filters:
                scale: { dim: [937, 600] }
```

This led to very strange artifacts.

![1517913174009854_Angry_Birds.jpg](https://image.ibb.co/nEkE6x/1517913174009854_Angry_Birds.jpg)

Since the problem is clearly due to the transparent background, i just added a white background to the filter:

```yml
liip_imagine:
    filter_sets:
        product_cover_card:
            quality: 75
            format: jpg # change format
            filters:
                background: { color: '#ffffff' } # white bg
                scale: { dim: [937, 600] }
```

This fixed PNG, but broke JPEG files:

![1014527184 (1).jpg](https://i.imgur.com/EQIg10L.jpg)

I use GD only

```
$ php -v
PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

```
$ php --ri gd

gd

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.2.54
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

Interestingly, bug appears with a "thumbnail" filter.
With other filters this bug is not seen yet.

**Comment by peter-gribanov** [comment]
The problem is still relevant.
The problem is still with the `thumbnail` filter.

### Origin

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51619970-7bfd2100-1f42-11e9-83ff-7df336a59b9a.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51620351-3ab94100-1f43-11e9-9e6d-8d0eb4dfa9b8.jpg">
</details>

## Only thumbnail

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                thumbnail: { size: [300, 300], mode: inset }
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51618105-a816a300-1f3e-11e9-9110-2a8bcbcf436f.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51620388-5290c500-1f43-11e9-832b-2f4c02e284fb.jpg">
</details>

## thumbnail with white background

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                background: { color: '#ffffff' } # white bg
                thumbnail: { size: [300, 300], mode: inset }
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51664263-1f454900-1fca-11e9-9794-4181fdb0ee8c.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51664281-29ffde00-1fca-11e9-973a-2d7ed980be2c.png">
</details>

### Some fix

Add background after resizeng image.
This method works, but the result will not be a reduced preview with aspect ratio. The result a picture with a fixed size. Therefore, it is better to use a `fixed-size` filter in this case.

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                thumbnail: { size: [300, 300], mode: inset }
                background: { color: '#ffffff' } # white bg
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51671100-3c354880-1fd9-11e9-8c01-7057ed03b427.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51671155-5707bd00-1fd9-11e9-9199-7bbc374ab027.png">
</details>

### Summary

The problem exists. It is there for a long time and it is still not resolved.
Now i have this problem reproduced with a `thumbnail` filter. With a `fixed-size` filters, this problem **does not** reproduce.
I use CentOS 7.6.1810 (latest), [PHP 7.2.14 (latest)](http://php.net/releases/), [GD 2.2.5 (latest)](https://libgd.github.io/).

### Docker

Surprisingly, this problem does not reproduce in the Docker on Windows.

```Dockerfile
FROM php:7.2-fpm-stretch

RUN apt-get update; apt-get install -y --no-install-recommends openssl git

# GD
RUN apt-get install -y --no-install-recommends libgd-dev; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
    docker-php-ext-install gd
```

```
# php -v
PHP 7.2.13 (cli) (built: Dec 10 2018 14:32:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
```

```
# php --ri gd

gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.3
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.6.28
WBMP Support => enabled
XBM Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```
