### ISSUE TITLE
Merging configurations overwrites `web_path` of the default resolver

### ISSUE THREAD

**Issue by pamil** [liip/LiipImagineBundle#1099]
### Steps to reproduce

1. `app/config.yaml` containing:
```yaml
imports: 
  - { resource: "first.yaml" }
  - { resource: "second.yaml" }
```
2. `app/first.yaml` containing:
```yaml
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/web"
                cache_prefix: "media/cache"
```
3. `app/second.yaml` containing:
```yaml
liip_imagine:
    filter_sets:
        foo:
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

### Expected result
1. The configuration should be processed and merged into (`bin/console debug:config LiipImagineBundle`):
```yaml
liip_imagine:
    # ...
    resolvers:
        default:
            web_path:
                web_root: /Users/pamil/Projects/Sylius/Sylius/web
                cache_prefix: media/cache
```

### Actual result
1. The configuration is processed and merged into (`bin/console debug:config LiipImagineBundle`):
```yaml
liip_imagine:
    # ...
    resolvers:
        default:
            web_path:
                web_root: /Users/pamil/Projects/Sylius/Sylius/public
                cache_prefix: media/cache
```
