### ISSUE TITLE
can we use this bundle to create a dummy image when image is not existed? 

### ISSUE THREAD

**Issue by videni** [liip/LiipImagineBundle#1100]
in development environment,, it is very useful to return a dummy image when a request image is not existed,  does this bundle have this feature?  I don't find any documentation.

**Comment by robfrawley** [comment]
You can define a default image using  few different methods, as shown [in our configuration documentation](https://symfony.com/doc/2.0/bundles/LiipImagineBundle/configuration.html). For example to define a global default image, you would use:

```yml
liip_imagine:
    default_image: /path/to/default/image/foo
```

Or to define a custom image that applies only for a specific filter set, you would use:

```yml
liip_imagine:
    filter_sets:
        your_filter_set_name:
            default_image: /path/to/default/image/bar
```
