### ISSUE TITLE
Generated image is 44 times heavier than original image

### ISSUE THREAD

**Issue by Kocal** [liip/LiipImagineBundle#1104]
Today at work, one of our web integrator tell us about a problem about very VERY **VERY** heavy images.

After manual testings, we found out that the problem comes from this bundle. 

In our CMS, we can switch the use of `imagine_filter` Twig filter. When the filter is used, the generated images are way too heavy in comparison of their original images.

So since we were running a old version (1.5.3), we tried to update to 1.9, then to 2.0 but the problem is still here.

### Preconditions

1. LiipImagineBundle: 2.0.0 (66959e113d1976d0b23a2617771c2c65d62ea44b)
2. PHP 7.2.5-1
3. GD: 2.2.4

This is an extract of our config file:

```yml
liip_imagine:
    controller:
        filter_runtime_action: Path\To\ImagineController:filterRuntimeAction
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/web"
    loaders:
        default:
            filesystem:
                data_root:
                  - "%kernel.project_dir%/web/"
                  - "%nfs_media_path%"
    filter_sets:
        cache: ~
        dynamic:
            filters:
        Sw1500:
            filters:
                relative_resize: { widen: 1500 }
        # ... 
```

### Steps to reproduce

1. Upload an PNG image (~287 kB) (1366 x ... px)
2. Waits for [Kraken](https://kraken.io) optimization (~100 kB)
3. Link this image with an article
5. Configure the image filter(e.g.: `Sw1500` will wide images to 1500 pixels)
6. Save
7. Go to front office
8. The Twig filter generate the image with the selected filter 
9. Image is too heavy (~ 4.7 MB)

This is how we call the Twig filter:

```twig
{# Some refactoring to make this code much easier to read/understand #}
{% set imageFilename = '/media/original/' ~ article.articleMedias.0.media.filename %}
{% set imageFormat = article.[...] %} {# will be 'Sw1500' #}
{% set imageFormatOptions = ... %}

<img src="{{ imageFilename|imagine_filter(imageFormat, imageFormatOptions) }} />
```

This is the image that I will upload:
![original_483](https://user-images.githubusercontent.com/2103975/41298408-96f27ede-6e61-11e8-8169-2846e5b706f0.png)

This is the same image, but after upload and Kraken optimization:
![original_484](https://user-images.githubusercontent.com/2103975/41298391-8ef522fe-6e61-11e8-9f69-0862bf9ce363.png)

So at the final, the original image weight ~100 kB.

### Expected result

1. The generated image by LiipImagineBundle should not weight 44 times the size of the original image

### Actual result

When our image is passing to filter `Sw1500`, the generated image is too much heavy: 

![original_485](https://user-images.githubusercontent.com/2103975/41298217-271d5430-6e61-11e8-872f-b76f022367af.png)

We don't understand why this thing happens.
The original image has a width of 1366px. Upscaling it to 1500px can't make it soo heavy, right?

---

At the moment, we didn't try to change the driver (from GD to Imagemagick), or to change built-in processors...
We will try tomorrow and see if it's better.

... Maybe Kraken is doing some strange things to the image, I will disable it and see if it do something.

Thanks!
