### ISSUE TITLE
Unrecognized option "resource" under "liip_imagine"

### ISSUE THREAD

**Issue by stef59100** [liip/LiipImagineBundle#1111]
Hello,

First of all please forgive me if this issue has been already resolved.

 I'm a newbie to symfony 4, trying to build a catalog, i decided to install miip/imagine_bundle to manage image sizes. So i followed the documentation steps, although it's been written for symfony 2 i guess.
So in the configuration file routing.yml, i added the following 

`liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yml"`

When i run the server, i get the error message : Unrecognized option "resource" under "liip_imagine"

Any clue about the problem ?
The project is running under symfony 4.1 with flex/ php 7.1.16

Thank you

**Comment by stefantalen** [comment]
Maybe it's a typo (`liip_imagine` instead of `_liip_imagine`)?

```yml
# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
```

http://symfony.com/doc/2.0/bundles/LiipImagineBundle/installation.html
