### ISSUE TITLE
Fix installation documentation

### ISSUE THREAD

**Issue by lobodol** [liip/LiipImagineBundle#1120]
Hello,

In the official [installation documentation](http://symfony.com/doc/master/bundles/LiipImagineBundle/installation.html#step-3-register-the-bundle-s-routes) in step 3, its said to load routes like this:
```yml
# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```

But there is no such file. The routing file is routing.**yaml**: https://github.com/liip/LiipImagineBundle/blob/master/Resources/config/routing.yaml

It would be nice to update the documentation consequently.

Regards,
