### ISSUE TITLE
cache_prefix setting of default resolver ignored by SF4.1

### ISSUE THREAD

**Issue by gwschutte** [liip/LiipImagineBundle#1133]
When I'm overriding the configuration of the cache_prefix of the default resolver it doesn't seem to use the newly inserted value. But perhaps I'm overlooking something? All other configuration values like filters are working fine.

### Preconditions
* PHP 7.2.10
* Symfony 4.1
* LiipImagineBundle 2.1.0 

### Steps to reproduce
The config that I'm using in {project_dir}/config/packages/liip_imagine.yaml:
```
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: 'uploads/cache'
```
But when I run a debug:config LiipImagineBundle, it gives the following output:
```Current configuration for "LiipImagineBundle"
=============================================

liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '{my_root_path}/public'
                cache_prefix: media/cache`
```
In the routes.yaml file I added the following route:
```
liip_imagine_filter:
    path: /uploads/cache/{filter}/{path}
    defaults:
        _controller: '%liip_imagine.controller.filter_action%'
    methods:
        -GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+
```
### Expected result
I expected that the config of "cache_prefix" would be set to 'uploads/cache'  and that files would be accessible on https://{domain}/uploads/cache/etc..

### Actual result
The config value doesn't seem to be set and it keeps on using the "media/cache" value. In the AppProdProjectContainer file (in cache) it seems that the "media/cache" is hardcoded in the service definition. (when I look for: protected function getLiipImagine_Cache_Resolver_DefaultService())
