### ISSUE TITLE
Image not cached for .jpg format but .png is fine (Symfony 4)

### ISSUE THREAD

**Issue by JEJExHUNTER** [liip/LiipImagineBundle#1158]
### Preconditions

1.  localhost - wamp - php 7.2
2.  liip/imagine-bundle": "^2.1"

### Steps to reproduce

1.  In my template : `{{ property.filename | imagine_filter('thumb_property') }}`
2. In my liip configuration:
```
liip_imagine:
    filter_sets:
        thumb_property:
            data_loader: thumb_property
            cache: thumb_property
            quality: 75
            jpeg_quality: 75
            filters:
                thumbnail:
                    size:       [200, 200]
                    mode:       outbound
                    allow_upscale: false
                    
    resolvers:
        thumb_property:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        thumb_property:
            filesystem:
                data_root: "%kernel.project_dir%/public/images/properties"
```

### Expected result

1. Cache generated for all image mimetype

### Actual result

1. When the page is load, i can see cached image for .jpg but not for .jpg file.
2. In my cache folder, .png files are created but .jpg files are not.
3. In the console if i remove the cache by the following command:
`php bin/console liip:imagine:cache:remove`
After this i try to resolve the cache for a .png file with 
`php bin/console liip:imagine:cache:resolve my_image_png.png`
All is good, the file is created and this message appear:
`http://localhost/media/cache/thumb_property/my_image_png.png`
But when i run the following command:
`php bin/console liip:imagine:cache:resolve my_image_jpg.jpg`
An error message appear:
` Unable to open image C:\wamp64\www\AgenceImmo\public\images\properties\my_image_jpg.jpg`

**Comment by Kleinast** [comment]
I have the same problem, work with png and not jpg
I m on: 
symfony 4.2.3
liip_imagine 2.1
docker

Thanks for your help

**Comment by Arielblues** [comment]
Hi i can not even get this cache working at all for both .png .jpg

I tried to follow the exmaple and also looked at 
https://github.com/dustin10/VichUploaderBundle/issues/858

installed the bundle..
Have the correct routing in routes.yaml
```
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
```

Configured the liip_imagine.yaml

```
liip_imagine:
    filter_sets:
        my_thumb:
            data_loader: my_thumb
            cache: my_thumb
            quality: 75
            filters:
                thumbnail:
                    size:       [10, 10]
                    mode:       outbound
                    allow_upscale: false
                    
    resolvers:
        my_thumb:
            web_path:
                web_root: "%kernel.project_dir%/public/uploads/albums/photos"
                cache_prefix: "media/cache"

    loaders:
        my_thumb:
            filesystem:
                data_root: "%kernel.project_dir%/public/uploads/albums/photos"
```

and have my form/phototupex configured like this 

```
<?php
namespace App\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
class PhotoTypex extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label' => 'Name', 'empty_data' => 'Name','label_attr' => array('style'=> '') ))
            ->add('description', TextType::class, array('label' => 'Description', 'empty_data' => 'Description','label_attr' => array('style'=> '') ))
            ->add('imageFile', VichImageType::class, ['imagine_pattern' => 'my_thumb', 'label' => 'Image', 'empty_data' => 'Image', ])
        ;
    }
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Propimg'
        ));
    }
}
```

I upload though easyadmin. Aand files will be uploaded and stored in the normal uploads/albums/photos folder. but nothing in the cache.

When i force it php bin/console liip:imagine:cache:resolve
it gets create in the cache directory but i also get an error.  Source image not resolvable "photo-1980-1020.jpg" in root path(s) "C:\xampp\htdocs\mysite\public"

I tried both jpg and png files but i get the same non cahcing results when uploading through easyadmin. Did i miss soemthing? give rights to the cache folder etc?
