### ISSUE TITLE
Cached images are automatically rotated on iOS

### ISSUE THREAD

**Issue by alacroixAskin** [liip/LiipImagineBundle#1170]
I'm currently working on a website where we could upload live photos with smartphones. I'm blocked with an issue and I can't figured out how to resolve it.

I try to take a photo and upload it in application. On Android the photo is displayed with the correct way (portrait or landscape photos). On iOS the photo is displayed with à 90 degree in portrait mode and if I try to take a photo in landscape mode, the photo is well displayed.

Liip Imagine bundle version 2.0.x-dev

Symfony version 4.2.5

Previously I used the driver GD, now I try with imagick.

Liip configuration :

liip_imagine:
# valid drivers options include "gd" or "gmagick" or "imagick"
driver: "gd"

resolvers:
   default:
      web_path:
        web_root: "%kernel.project_dir%/public/"
filter_sets:
    live_feed_message:
        jpeg_quality:          85
        png_compression_level: 8
        filters:
            thumbnail:
                size:          [768, 768]
                mode:          outbound

I tried to comment all filters in live_feed_message, with no result.

Thank you in advance for your help...

**Comment by alacroixAskin** [comment]
Up please, I've tried a lot of configurations but still the bug...

**Comment by virtualize** [comment]
You could try to to apply the `auto_rotate` filter in front of other filters, like this
```
liip_imagine:
    filter_sets:
        og_image_default:
            filters:
                auto_rotate: ~ # fix rotation from exif data
                thumbnail: {size: [600, 600], mode: inset}
```
