### ISSUE TITLE
Confusion between filters and filter_sets in imagine_filter

### ISSUE THREAD

**Issue by luispabon** [liip/LiipImagineBundle#1171]
Given the doc's examples:
```yaml
liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        # the name of the "filter set"
        my_thumb :

            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [120, 90], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [124, 94], position : center, color : '#000000' }
```
```
{{ asset('/relative/path/to/image.jpg') | imagine_filter('my_thumb') }}
```

I'm very confused on how do I actually select between the thumbnail, or the background.
