### ISSUE TITLE
Image cannot be resolved if contains query parameters

### ISSUE THREAD

**Issue by proArtex** [liip/LiipImagineBundle#1172]
Stream loader via http/https may contain query params that are omitted during cache resolve.

### Preconditions

1. Symfony 4.2.7
2. liip/imagine-bundle: 2.1.0
3. imagine/imagine: v0.7.1

### Steps to reproduce
```
# services.yaml

Liip\ImagineBundle\Binary\Loader\StreamLoader:
        arguments:
            $wrapperPrefix: ''
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'remote_loader' }
```

```
# packages/liip_imagine.yaml

liip_imagine:
    driver: imagick
    resolvers:
        default:
            web_path:
                cache_prefix: '%thumbnails_path%'
    filter_sets:
        user_640x640:
            data_loader: remote_loader
            filters:
                strip: ~
                upscale:
                    min: [640, 640]
                thumbnail:
                    size: [640, 640]
                    mode: outbound
```

```
# template.twig

<img src="{{ 'https://pp.userapi.com/Ezx-RHE3h-pOqTrvqi3jrWnYGWTNW-F_yG5uoA/Wppvp-5waFQ.jpg?ava=1' | imagine_filter('user_640x640') }}">
```

### Expected result
Resolved image /thumbnails/user_640x640/https://pp.userapi.com/Ezx-RHE3h-pOqTrvqi3jrWnYGWTNW-F_yG5uoA/Wppvp-5waFQ.jpg?ava=1

### Actual result
Exception "No route found for "GET /thumbnails/user_640x640/https://pp.userapi.com/Ezx-RHE3h-pOqTrvqi3jrWnYGWTNW-F_yG5uoA/Wppvp-5waFQ.jpg"
