### ISSUE TITLE
how to crop image by top

### ISSUE THREAD

**Issue by florent6001** [liip/LiipImagineBundle#1174]
Hi all.
I try to use liip for the first time. 
I have a long height image and low width. 
Liip crop the image by Middle. How to keep the top please ? Ty

**Comment by Akiletour** [comment]
Hey,

You could try this way : 

```
filter_sets:
    my_thumb:
      quality: 75
      filters:
        relative_resize: { widen: 320 }
        crop: { start: [0, 0], size: [320, 240] }
```
