### ISSUE TITLE
Background filter issue (grey noise)

### ISSUE THREAD

**Issue by picks44** [liip/LiipImagineBundle#1177]
Hi all,

Since we migrated into a new Azure server using PHP7.2 ( and without touching the config data), the filter sets that implements the backgroun filter display an image with grey noise all over 

1. https://www.desouttertools.com/media/cache/resolve/thumb_350x350/bundles/desiwid/images/press/LOGO_Desoutter.jpg
2. https://www.desouttertools.com/media/cache/resolve/thumb_1140x400_tools/uploads/catalog/products/ELB12-600-P.jpg

Here is an example of the config we use  
```
thumb_1140x400_small:
            filters:
                background:
                    size: [1140, 400]
                    color: '#ffffff'
            post_processors:
                jpegoptim: { strip_all: true, max: 90, progressive: true }
                pngquant: { quality: '50-60' }

```

Did anybody expereinced this issue? Can anyone help? Thanks

In case it helps, we are using these versions of the post-processors 

- optipng                            0.7.6-1+deb9u1
- jpegoptim                          1.4.4-1+b1 
- pngquant                           2.5.0-2
