### ISSUE TITLE
Thumbnail with fixed size

### ISSUE THREAD

**Issue by nkoyan** [liip/LiipImagineBundle#1181]
How to create a thumbnail with fixed size in version 2.1.0 ?
I tried with `allow_upscale` but it has no effect
```
filters:
    thumbnail:
         size: [800,530]
         mode: outbound
         allow_upscale: true
```
I tried with `fixed` filter : https://symfony.com/doc/1.0/bundles/LiipImagineBundle/filters/sizing.html#fixed-size
but this filter is not present in version 2.1
