### ISSUE TITLE
cacheManager->getBrowserPath() is cripplingly slow with S3

### ISSUE THREAD

**Issue by plamenh** [liip/LiipImagineBundle#1188]
### Preconditions

1. PHP 7.3
2. Gaufrette/S3/vichuploader/

```
loaders:
        stream.photo_fs:
            stream:
                wrapper: gaufrette://photo_fs/
        local:
            filesystem: ~

    cache: cached_s3

    data_loader: stream.photo_fs
```

3. CacheResolver wrapping S3 resolver

```
app.s3:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: 'latest'
                region: 'fra1'
                endpoint: '%env(S3_BASE_URL)%'
                credentials:
                    key: '%env(S3_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'

    app.imagine.cache.resolver.s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@app.s3"
            - '%env(S3_BUCKET_NAME)%'

    apccache:
        class: Apcucache

    cache.apccache:
        class: Doctrine\Common\Cache\ApcuCache

    acme.imagine.cache.resolver.s3.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@cache.apccache"
            - "@app.imagine.cache.resolver.s3"
            - { prefix: "s3" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_s3" }
```

4. JMS Serializer with postserialize cache generation for images

```
public function onPostSerialize(ObjectEvent $event)
    {
        $object = $event->getObject();
        $visitor = $event->getVisitor();
        /* @var $visitor GenericSerializationVisitor */
        $path = $this->uploaderHelper->asset($object, 'file');
        $urls = [];
        foreach (['carouselImage', 'carouselImage2x', 'profilePhoto', 'profilePhoto2x', 'companyLogo'] as $pattern) {
            $urls[$pattern] = $this->cacheManager->getBrowserPath($path, sprintf('%s', $pattern));
        }
        $visitor->addData('image_urls', $urls);
    }
```

### Steps to reproduce

1. Request resource
2. Huge wait

### Expected result

1. Get a normally fast response, i.e. between 1 and 2 seconds (this is what we get with a regular local filesystem setup)

### Actual result

1. Process takes anywhere from 15 to 40 seconds.
