### ISSUE TITLE
jpeg color profil lost when thumbnail filter size < original file size (not all os)

### ISSUE THREAD

**Issue by florianajir** [liip/LiipImagineBundle#1205]
When imagine bundle filter is called, if the original image size is upper than the thumbnail filter size, the jpeg result file loose profil metadata (like with magick -strip option).

The weird thing is with the same source code it does not happen on windows OS or ubuntu but only on my centos 7 servers.

And if I run manually the convert command on centos with `magick convert test.jpg -thumbnail '500x500' output.jpg` my output.jpg is correct.

I tried to upgrade ImageMagick and imagick version to the latest, same result. 
The only different thing I can see between windows and linux environment is the "Delegates (built-in)" info:

Windows

```
magick --version
Version: ImageMagick 7.0.8-51 Q16 x64 2019-07-01 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```

CentOS7

```
magick --version
Version: ImageMagick 7.0.8-60 Q16 x86_64 2019-08-16 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype jng jp2 jpeg lzma openexr pangocairo png tiff wmf x xml zlib
```

### Preconditions

1.  latest bundle +imagick version
2.  imagick
3.  php 7.2

Here is my config:

```yaml
liip_imagine:
    driver: "imagick"
    filter_sets:
        thumb:
            filters:
                thumbnail:
                    size:     [500, 500]
                    mode:     inset
``` 

### Expected result

Keep color profile if no strip option
