### ISSUE TITLE
Resolve cache images in background not working

### ISSUE THREAD

**Issue by indapublic** [liip/LiipImagineBundle#1228]
### Preconditions

```
symfony/framework-bundle            v4.2.11 Symfony FrameworkBundle

enqueue/dsn                         0.9.2   Parse DSN
enqueue/enqueue                     0.9.12  Message Queue Library
enqueue/enqueue-bundle              0.9.13  Message Queue Bundle
enqueue/fs                          0.9.12  Enqueue Filesystem based transport
enqueue/null                        0.9.12  Enqueue Null transport

PHP 7.2.21 (cli) (built: Aug  2 2019 06:05:35) ( NTS )

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
```

### Steps to reproduce
1. `composer require enqueue/enqueue-bundle enqueue/fs`
2. Set enqueue config as:
```
enqueue:
    default:
#        transport: '%env(resolve:ENQUEUE_DSN)%'
        transport: 'file://%kernel.root_dir%/../var/enqueue'
        client: null
```
3. Set liip_imagine.enqueue = true as
```
liip_imagine:
    ...
    enqueue: true
```
4. `bin/console enqueue:consume --setup-broker -vvv`

### Actual result

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
> 
>   [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
>   The service "liip_imagine.async.resolve_cache_processor" has a dependency on a non-existent service "enqueue.producer"
>   .
>
