### ISSUE TITLE
Add support for Symfony 5

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#1241]
Symfony 5 is out since yesterday

**Comment by michellesanver** [comment]
Everything is prepared for this one, and I hope that we will soon be able to support Symfony 5. Currently blocked by other packages, which there are open MR's for 👍

**Comment by greg606** [comment]
Hello, what is the status of it?

**Comment by dbu** [comment]
work has been started in #1246 

if you want to contribute, please take the `symfony5` branch, rebase it on master to solve conflicts, and then add further changes to get the build green (e.g. allowing enqueue 0.10)

**Comment by michellesanver** [comment]
Done and released in 2.3.0!

**Comment by Aruno-Dev** [comment]
Not that simple to use it with symfony 5...or am i doing wrong ? probably :-)
I tried here : https://symfony.com/doc/2.0/bundles/LiipImagineBundle/basic-usage.html

But i don't even have a config.yaml in my config folder...

**Comment by slaubi** [comment]
@Aruno-Dev 
if you installed the bundle via composer, you got a new file ` config/packages/liip_imagine.yaml` automatically. that is the new "config".  but you can create that file also by yourself.

Here an example:

```
# config/packages/liip_imagine.yaml
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'imagick'

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media'

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"


    # your filter sets are defined here
    # sets the desired resize method: 'outbound' crops the image as required,
    # while 'inset' performs a non-cropping relative resize.
    filter_sets:
        detail:
            filters:
                relative_resize: { heighten: 1080 }
                strip: ~

        square:
            quality: 75
            filters:
                upscale: { min: [770, 770] }
                thumbnail: { size: [770, 770], mode: 'outbound' }
                strip: ~

        # use the default cache configuration
        cache: ~
```
