### ISSUE TITLE
Image "auto_rotate"-filter is not rotating my images correctly

### ISSUE THREAD

**Issue by kaahulkkonen** [liip/LiipImagineBundle#1247]
Hello,

I have an issue with my website running Symfony 3.4 and using LIIP Imagine Bundle 2.2.0. Images shot on some mobile devices are not being rotated correctly, even though `auto_rotate` filter is on.

**Example image:**
https://drive.google.com/open?id=1GuqPsZICYQ_OKk6BMAPIODud_GyCuUBt

**Exif data**
```
Camera Model Name:
iPhone X

Orientation:
Rotate 90 CW
```

### Preconditions
1. Symfony v3.4
2. Liip Imagine Bundle v2.2.0
3. PHP v7.1.30 (with exif extension enabled)
4. Driver: imagick (ImageMagick v6.8.9-9)
5. Ubuntu 16.04

Imagine `filter_sets` config:
```yaml
filter_sets:
        workingbase:
            format: jpg
            quality: 90
            filters:
                auto_rotate: ~
                strip: ~
                maxsize: { maxWidth: 1280, maxHeight: 1280 }
```

### Steps to reproduce
1.  Download attached image
2. Run the attached image trough Imagine with auto_rotate filter on

### Expected result
The image should be rotated from exif data "Rotate 90 CW"

### Actual result
The image is not rotated correctly
