### ISSUE TITLE
liipimagine create a thumbnail mode lists?

### ISSUE THREAD

**Issue by Davis-PHP** [liip/LiipImagineBundle#1250]
```
filter_sets:
        cache: ~
        heighten100:
            filters:
                relative_resize: { heighten: 100 }
        widen100:
            filters:
                relative_resize: { widen: 100 }
        home_banner:
            filters:
                thumbnail: { size: [630, 534], mode: outbound }
```
- mode: outbound  //positioning the thumbnail at its center
Are there any more mode?
positioning the thumbnail at its top?
positioning the thumbnail at its bottom?
......
Please forgive my curiosity 😀
thanks
