### ISSUE TITLE
Bundle does not render image with filter

### ISSUE THREAD

**Issue by zskiredj** [liip/LiipImagineBundle#1252]
I followed all instructions to install LiipImagineBundle, with default configuration :

```
# app/config/config.yml
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [124, 94], position: center, color: '#000000' }
```

The problem is that it does not render with the default filter :

`<img src="{{ asset('/relative/path/to/image.jpg') | imagine_filter('my_thumb') }}" />`

If i put the image without the filter, it renders, so it is not a problem of image location.

With the filter, the link to the image that is generated is :

`http://localhost/projets/test/web/app_dev.php/media/cache/resolve/my_thumb/projets/test/web/tabadoul-cover.jpg`

And no image is created, no media folder (which normaly should be created for caching the image).

I really dont know where is the problem, but i suspect it is related with APACHE.

Any help would be apreciated

For information, when I use the console command, the images are created :

`php bin/console liip:imagine:cache:resolve app/img/tabadoul-cover.jpg`

Edit 1 :
I tried to install the bundle on a new symfony project (3.4.36), and the problem persists when I use wampserver. BUT when i use the symfony server :
`php bin/console server:run`

the image is displayed !

So it is a problem of apache configuration ...

**Comment by bogdandovgopol** [comment]
Same here

**Comment by bogdandovgopol** [comment]
#1253 Same here

**Comment by mwoynarski** [comment]
What is the actual response code/content if you request the generated url directly?

If these are public assets, you could try
```
loaders:
    default:
        filesystem:
            locator: filesystem_insecure
````

That can sometimes be a magic bullet for unresolvable assets.
