### ISSUE TITLE
imagine_filter does not generate a https url

### ISSUE THREAD

**Issue by wyllyjon** [liip/LiipImagineBundle#1266]
Hello ! 

I use imagine_filter to generate thumbnails. My app is secured, but the url generated by `imagine_filter` does not have "https".

Here is my code : 
`<img src="{{ photo  | imagine_filter('my_thumb')}}" />`

And the liip_imagine conf : 
```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [200, 112], mode: outbound }
```

I haven't found any info on the documentation about https url...
I think that this should be generated automatically, but I don't understand according what rule...

Is there a way to generated https url in order to have all my requests that are secured ?

Thanks for your help !

Jonathan
