### ISSUE TITLE
It doesn't work for me in Symfony 4.4

### ISSUE THREAD

**Issue by EliuFlorez** [liip/LiipImagineBundle#1269]
It doesn't work for me in Symfony 4.4
The size I want is not copying or generating the new image.

PHP: 7.3
Server: Xginx
Symfony 4.4.3
LiipImagineBundle: 2.3

**Config**
```
liip_imagine:
    default_image: '%kernel.project_dir%/assets/noimage/assets/images/img_logo.png'
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
    filter_sets:
        cache: null
        small:
           quality: 100
           png_compression_level: 8
           default_image: '%kernel.project_dir%/assets/noimage/assets/images/img_logo.png'
           filters:
               thumbnail: {size: [400, 300], mode: 'inset'}
```

**PHP**
```
public function index(Request $request)
{
	/** @var CacheManager */
	$imagineCacheManager = $this->get('liip_imagine.cache.manager');

	/** @var string */
	$resolvedPath = $imagineCacheManager->getBrowserPath('/custom/domain_1/image_files/sitemgr_photo_100.jpg', 'small');

	print_r($resolvedPath); die();
}
```

**Results**
```
in: uploads/10/photo.jpg
out: media/cache/resolve/small/10/photo.jpg
folder: empty (the image that was filtered is not found, the new size was not copied.)
```
Any idea why? What else do I need or if it is an error with the version of Symfony 4.4
