### ISSUE TITLE
Images not generated into the cache in function of the cache_prefix parameter

### ISSUE THREAD

**Issue by dubitoph** [liip/LiipImagineBundle#1275]
I'm using Symfony 5.0, Php 7.4 and LiipImagineBundle 2.3.0.

There is my LiipImagineBundle configuration : 

```
liip_imagine:
 resolvers:
     default:
         web_path:
             web_root: "%kernel.project_dir%/public"
             cache_prefix: "images/cache"
 filter_sets:
   thumb:
     quality: 75
     filters:
       thumbnail:
         size: [360, 360]
         mode: outbound
         allow_upscale: true
   medium:
     quality: 75
     filters:
       thumbnail:
         size: [500, 500]
         mode: outbound
         allow_upscale: true
   tiny:
     quality: 75
     filters:
       thumbnail:
         size: [35, 35]
         mode: outbound
```
When I try to show an image this way : 

`<img id="photo_{{ user.profile.photo.id }}"  src="{{ vich_uploader_asset(user.profile.photo, 'file') | imagine_filter('thumb') }}" width="100" alt="Photo{{ user.profile.photo.id }}">`

I have this error : 

> GET http://127.0.0.1:8000/media/cache/resolve/thumb/images/profiles/2/5e89c4998cd20407919301.png 404 (Not Found)

In fact, images aren't created in the cache.

**Comment by bogdandovgopol** [comment]
If you run a command: ```php bin/console liip:imagine:cache:resolve empty.jpg --filter=filter_name```, images are created?

You might have the same issue #1260

**Comment by OlivierMongeot** [comment]
Hello,
I have the same  problem. 
I use Symfony 5.0, Php 7.4 and LiipImagineBundle 2.3. 

When i run the command :  php bin/console liip:imagine:cache:resolve empty.jpg --filter=filter_name : 
The image is well created in media/cache/thumb/images/properties/my_thumb.jpg. 

Second, I've try to disable cache in my browser Chrome like in the issue #1260, but i have no result. 

Maybe should we automatically call this command when the image was uploaded ?

**Comment by dubitoph** [comment]
> If you run a command: php bin/console liip:imagine:cache:resolve empty.jpg --filter=filter_name, images are created?

Yes, in this case, images are created.

**Comment by diegoiglesias** [comment]
I have the same issue. Actually it does work on localhost (MacOS Mojave) but it doesn't on production (Ubuntu 20.04). Images are correctly being uploaded but cache files are not being created. 

> If you run a command: php bin/console liip:imagine:cache:resolve empty.jpg --filter=filter_name, images are created?
Yes, running that command images are created.

I use Symfony 5.0, Php 7.4 and LiipImagineBundle 2.3.

**Comment by kkrieger85** [comment]
Same for me:

Twig: 3.0.3
PHP 7.4 with PHP7.4-gd
Symfony 5.x
liip/imagine-bundle 2.3.1


Twig template:

``` 
<img src="{{ asset('captures/'~domain.screenCapture)  | imagine_filter('my_thumb') }} " >
```

liip_imagine.yaml

``` 
liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/public' # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)
        cache_prefix: 'media/cache' # media/cache
  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%/public'

  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  filter_sets:
    cache: ~

    # the name of the "filter set"
    my_thumb:

      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:

        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [120, 90], mode: outbound }

        # create a 2px black border: center the thumbnail on a black background
        # 4px larger to create a 2px border around the final image
        background: { size: [124, 94], position: center, color: '#000000' }
``` 

Command `php bin/console liip:imagine:cache:resolve captures/filname.png --filter=my_thumb` works fine
