### ISSUE TITLE
404 on resolve Symfony 5

### ISSUE THREAD

**Issue by Romaixn** [liip/LiipImagineBundle#1279]
I have a 404 on resolve path on Symfony 5

### Preconditions

1. Bundle version : 2.3
2. Symfony 5.0.7

`https://app.localhost/media/cache/resolve/thumb/uploads/images/projects/5e447a47a9667634464219.jpg` 
this url is generated after making : 
`<img src="{{ vich_uploader_asset(project, 'imageFile') | imagine_filter('thumb') }}">`

I can generate image cache with the command `liip:imagine:cache:resolve` without errors.

My config file : 
```
liip_imagine:
    filter_sets:
        cache: ~

        thumb:

            quality: 75

            filters:
                thumbnail: { size: [360, 230], mode: outbound }

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound
```

Thanks for your help !
