### ISSUE TITLE
Browser path returns local URL when using Flysystem S3 loader and resolver

### ISSUE THREAD

**Issue by machacjan** [liip/LiipImagineBundle#1298]
Hello, I ran into a problem when trying to switch to S3 storage on my Symfony project. After uploading an image file, the application proceeds to create a thumbnail using the `file_thumb` filter set. For this my controller calls `$this->imagineCacheManager->getBrowserPath('/path/to/image.jpg', 'file_thumb')`, and that returns a URL pointing locally to `https://local.server/media/cache/resolve/file_thumb/path/to/image.jpg` instead of pointing to my S3 storage.

Are my assumptions about this function wrong, or do I have an error in my configuration files? Upload to my S3 and other storage-related operations are working fine, so I assume my Flysystem config is good.

Using version ^3.5 of **oneup/flysystem-bundle**, ^2.3 of **liip/imagine-bundle** and **Symfony** 5.1.5 running in a Vagrant box (Homestead).

My `config/packages/liip_imagine.yaml` configuration:
```
liip_imagine:
    driver: gd
    loaders:
        system_loader:
            flysystem:
                filesystem_service: oneup_flysystem.system_filesystem
    resolvers:
        system_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.system_filesystem
                cache_prefix: /
                root_url: '%env(DO_SPACE_URL)%'
                visibility: public
    data_loader: system_loader
    cache: system_resolver
    filter_sets:
        file_thumb:
            cache: ~ 
            quality: 80
            filters:
                downscale: 
                    max: [68, 52]
        # Other filter sets omitted
```

My `config/packages/oneup_flysystem.yaml` configuration:
```
oneup_flysystem:
    adapters:
        development:
            local:
                directory: '%kernel.project_dir%/public/%env(DO_SPACE_PREFIX)%/default'
        spaces:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(DO_SPACE_NAME)%'
                prefix: '%env(DO_SPACE_PREFIX)%/default' 
    filesystems:
        system:
            adapter: spaces
            visibility: public

services:
    Aws\S3\S3Client:
        class: Aws\S3\S3Client
        arguments:
            - endpoint: 'https://ams3.digitaloceanspaces.com'
              version: latest
              region: ams3
              credentials:
                  key: '%env(DO_SPACE_KEY)%'
                  secret: '%env(DO_SPACE_SECRET)%'
```

**Comment by brizzz** [comment]
Have you found a solution?

**Comment by machacjan** [comment]
> Have you found a solution?

Sadly, I have not. I intended to use DigitalOcean's [Spaces](https://docs.digitalocean.com/products/spaces/), but this issue forced me to use [Volumes](https://docs.digitalocean.com/products/volumes/) with Flysystem's local adapter instead.

**Comment by brizzz** [comment]
I found a solution. Perhaps it will be useful to someone.

`https: //local.server/media/cache/resolve/file_thumb/path/to/image.jpg` is correct. When requesting this address, a 301 redirect to the generated image is returned. The problem is different. Cache resolver for Flysystem (FlysystemV2Resolver) cannot work with endpoint where bucket is part of url path (as I think)

So you need to configure Aws \ S3 \ S3Client to use an endpoint like `https://your-bucket.ams3.digitaloceanspaces.com` instead of `https://ams3.digitaloceanspaces.com/your-bucket`:

```
Aws \ S3 \ S3Client:
         arguments:
             ...
             endpoint: "https://your-bucket.ams3.digitaloceanspaces.com"
             bucket_endpoint: true

```
And accordingly:
```
liip_imagine:
     resolvers:
         system_resolver:
             flysystem:
                 ...
                 root_url: "https://your-bucket.ams3.digitaloceanspaces.com"

```
