### ISSUE TITLE
WebP support is broken

### ISSUE THREAD

**Issue by fbourigault** [liip/LiipImagineBundle#1319]
Given the following code:
```
<img src="{{ asset('DSC_3644.JPG') | imagine_filter('thumbnail') }}" alt="DSC_3644.JPG" />
```

When there is no cache, the src value is `https://localhost:8000/media/cache/resolve/thumbnail/DSC_3644.JPG` which is handled by the `ImagineController` and redirect to `https://localhost:8000/media/cache/thumbnail/DSC_3644.JPG.webp`

When the cache is warmed, the src value is `https://127.0.0.1:8000/media/cache/thumbnail/DSC_3644.JPG` which is not handled by the `ImagineController` and returns the JPEG version of the image.

I think we should not support WebP this way and consider using proper content negotiation which will require users to use the `<picture>` HTML element but will allow deterministic behavior and also support other formats such as AVIF (see https://github.com/liip/LiipImagineBundle/issues/1314).

I didn't tested it, but this WebP implementation may break HTTP Caching.

I propose to revert https://github.com/liip/LiipImagineBundle/pull/1307 and then to follow this plan:

- Move to GitHub Actions as travis-ci.com does not support webp (see #1318).

- Ensure that WebP can be used as a supported format by adding tests and strong configuration validation to ensure that when webp format is requested by the end user, the used driver also support it. This would avoid issues about webp format not working.

At this point, it's possible to do content negotiation through the use of multiple filters_set (one per format).

- Allow to use configure multiple formats per filter set to avoid filters_set duplications because of the format and add a `format` option to the `imagine_filter` twig filter.

At this point, it's possible to do content negotiation with `<picture>` and a single filters_set (configured with multiple formats).

- Allow server-side content-negotiation. IMHO, this should be done at the twig level. to avoid the issue I described above. A service could also be provided to ease integration with other systems (APIs ?).

At this point, it will be possible to do both client-side and server-side content negotiation with no compromise and also being open to add AVIF and any future format.

**Comment by martinbroos** [comment]
I'm still very exited to use webp with LiipImagine, but haven't tried the new implementation yet. But your cache issue makes sense.. I'm still not against using html picture element as content negotiation.

**Comment by lsmith77** [comment]
sorry. I didn’t see the issue before releasing 2.4.0. 

I will look at how to proceed today. 

@peter-gribanov can you maybe also have a look at the issue?

**Comment by lsmith77** [comment]
@fbourigault proper content negotiation is indeed the way to go.

that being said, the feature as is has been released since I didn't see this ticket in time (my bad).

so what if we basically deprecate #1307 and then rather work on a 3.0 which features content negotiation?

@fbourigault would you be willing to take the lead here?
@peter-gribanov what is your point of view here? would you be motivated to collaborate with @fbourigault on the proposal outlined above?

in that case we would merge #1323 and release 2.4.1 with this fix and a deprecation notice.

**Comment by peter-gribanov** [comment]
> I didn't tested it, but this WebP implementation may break HTTP Caching.

The controller uses a 302 Moved Temporarily redirect, not a 301 Moved Permanently redirect. It is normal practice to use a 302 redirect to redirect to different URLs depending on conditions. Redirects with 302 code are not cached without explicitly specifying cache `Cache-Control` or `Expires` headers. The user's browser can cache the redirect, but in the case of a specific browser, the redirect will be correct. Another browser will have a different cache and a different redirect. The problem can only be with caching proxies and only if you are not using HTTPS. HTTP caching does not work with HTTPS.

> * Ensure that WebP can be used as a supported format by adding tests and strong configuration validation to ensure that when webp format is requested by the end user, the used driver also support it. This would avoid issues about webp format not working.

Has already.

> I think we should not support WebP this way and consider using proper content negotiation which will require users to use the <picture> HTML element but will allow deterministic behavior and also support other formats such as AVIF.

This subject has already been [discussed](https://github.com/liip/LiipImagineBundle/pull/1307#issuecomment-730293610). Implementing what you want will be difficult and will break BC. The link to the picture should contain not only the name of the filter, but also the expected format.

```
https://localhost:8000/media/cache/resolve/thumbnail/jpeg/DSC_3644.JPG
https://localhost:8000/media/cache/resolve/thumbnail/webp/DSC_3644.JPG
```

Do you want to receive something like this?

```yaml
liip_imagine:
    filter_sets:
        thumbnail:
            formats:
                webp:
                    quality: 100
                    post_processors:
                        my_custom_post_processor: { }
                jpeg:
                    quality: 80
                    post_processors:
                        my_custom_post_processor: { }
                png:
                    quality: 100
                    post_processors:
                        my_custom_post_processor: { }
            filters:
                thumbnail: { size: [223, 223], mode: inset }
```

I repeat once again, the main idea of ​​my feature is to enable WebP support in the project with minimal effort, without changing the project code as much as possible. Very soon, the need for such tricks will disappear. https://caniuse.com/webp
