### ISSUE TITLE
relative_resize and auto_rotate not working together

### ISSUE THREAD

**Issue by steveking198** [liip/LiipImagineBundle#1352]
### Preconditions

Running nginx on WSL, php 7.4, bundle version is 2.4 and using Imagick as the driver

### Steps to reproduce

My config

```
    driver: "imagick"

    filter_sets:
      cache: ~

      gallery_thumb:
        quality: 95
        filters:
          auto_rotate: ~
          thumbnail: { size: [250, 250], mode: outbound }
          background: { size: [250, 250], position: center, color: '#000000' }

      gallery_large:
        quality: 95
        filters:
          auto_rotate: ~
          relative_resize:
            heighten: 800
```

### Expected result

Both should show the image with the correct orientation

### Actual result

The `gallery_thumb` filter does exactly as I expect, it outputs the image at the correct size with the correct orientation

The `gallery_large` filter doesn't auto rotate but does output at the correct size

Twig code

```
{{ asset("gallery/" ~ image.filename) | imagine_filter('gallery_thumb') }}
{{ asset("gallery/" ~ image.filename) | imagine_filter('gallery_large') }}
```

Is it somehow stripping the image info before it does the auto rotate for the large config?
