### ISSUE TITLE
True image conversion

### ISSUE THREAD

**Issue by lebadapetru** [liip/LiipImagineBundle#1372]
I've been looking around for a way to convert images and i tried to put different pieces together but i think i've hit a wall.
My use case is this:

A user can request an image like this: `http://app.com/image/{id}/scale/{size}/{name}`

id = the file id so i can retrieve it from storage
scale&size = the dynamic filter that i'm applying to the image with the value like `500x500`
name = the desired name&extension of the image

My controller:

```
$imageExtension = pathinfo($data['name'], PATHINFO_EXTENSION);
        $filter = match ($imageExtension) {
            'jpg', 'jpeg' => 'jpg',
            'png' => 'png',
            default => throw new BadRequestHttpException('The image format is not supported.'),
        };

$config = [
            'scale' => [
                'dim' => $size
            ],
        ];
$path = $this->filterService->getUrlOfFilteredImageWithRuntimeFilters(
            $this->fileStorage->getRealFileLocation($file, false),
            $filter,
            $config
        );

return new StreamedResponse(
            function () use ($path, $file, $fileStorage) {
                //streaming it to output stream
            },
            200,
            [
                'Content-Type' => File::ACCEPTED_MIME_TYPES['images'][$imageExtension]

            ]
        );
```

liipimagine.yaml
```
filter_sets:
        # the name of the "filter set"
        png:
            format: png
            # list of transformations to apply (the "filters")
            filters:
            post_processors:
                optipng: { strip_all: true, level: 5 }
        jpg:
            format: jpg
            filters:
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
```

The idea is this, no matter the file original name, format, extension i'm using the id parameter to get it's real attributes and i'm using the scale and name parameters to modify the output. If the original image is a jpg and the `name` parameter is `image.png`, i'll apply the `png` filter which converts the image to png.
The output is fine, if i save the image and check it's mimetype, is a png but if i go to /media/cache and check for that image, the mimetype and extension is still a jpg. So it looks like `format` isn't really working that way i expect it to.
Is there a better way to convert an image in such a way that the cached version reflects the desired mimetype?
