### ISSUE TITLE
Get WebP urls

### ISSUE THREAD

**Issue by xf-** [liip/LiipImagineBundle#1386]
**Is your feature request related to a problem? Please describe.**

At the moment I can't get the WebP image for a picture tag with type webP

**Describe the solution you'd like**

Some way to get the WebP URL or be constant and only `webp` needs to be added.

**Describe alternatives you've considered**

 I found no way based on docu to create a new thumbnail in webp format or get the URL that will be created in redirect.

**Additional context**
Instead of using request for 302 the browser requests the supported format. This is properly done in PHP, so the request can be avoided (especially with a long thumbnail list).

```html
<picture>
  <source srcset="logo.webp" type="image/webp">
  <img src="logo.png" alt="logo" loading="lazy">
</picture>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#the_type_attribute

**Comment by peter-gribanov** [comment]
You can solve the problem by configure several filters in different formats. See PR #1380

```yaml
# app/config/config.yml
liip_imagine:
    filter_sets:
        my_thumb_jpeg:
            format: jpeg
            quality: 80
            filters:
               thumbnail: { size: [223, 223], mode: inset }
       my_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [223, 223], mode: inset }
```

```twig
<picture>
  <source srcset="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb_webp') }}" type="image/webp">
  <source srcset="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb_jpeg') }}" type="image/jpeg">
  <img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb_jpeg') }}" alt="Alt Text!">
</picture>
```
