### ISSUE TITLE
Webp generation broken

### ISSUE THREAD

**Issue by 7system7** [liip/LiipImagineBundle#1409]
With webp settings nothing happening. It generates jpg only.

### Preconditions

1. PHP 7.4, GD 2.3.0, Imagick 3.5.1, Symfony 5.3.10
2. Liip bundle version: 2.7.0

### Steps to reproduce

1. Install bundle and setup
```yaml
    driver: "gd" # I tried this w/ imagick also but that was not worked also.
    resolvers:
        default:
            web_path: ~
    controller:
        redirect_response_code: 302
    webp:
        generate: true
    filter_sets:
        cache: ~
        thumbnail_big:
            quality: 75
            filters:
                thumbnail: { size: [ 800, 450 ], mode: inset }
                background: { size: [ 800, 450 ], position: center, color: '#000000' }
        thumbnail_small:
            quality: 50
            format: webp
            filters:
                thumbnail: { size: [ 90, 50 ], mode: inset }
                background: { size: [ 90, 50 ], position: center, color: '#000000' }
```
2. Upload `jpg` images to the system.
3. Use resolver
```php
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Liip\ImagineBundle\Imagine\Data\DataManager;
use Liip\ImagineBundle\Imagine\Filter\FilterManager;

...

    private const BIG_FILTER   = 'thumbnail_big';
    private const SMALL_FILTER = 'thumbnail_small';

    public function __construct(
        DataManager $dataManager,
        FilterManager $filterManager,
        CacheManager $cacheManager
    ) { ... }

...

        $urlBig = $this->cacheManager->isStored($path, self::BIG_FILTER)
            ? $this->cacheManager->resolve($path, self::BIG_FILTER)
            : $this->generateUrl(self::BIG_FILTER, $path);

        $urlSmall = $this->cacheManager->isStored($path, self::SMALL_FILTER)
            ? $this->cacheManager->resolve($path, self::SMALL_FILTER)
            : $this->generateUrl(self::SMALL_FILTER, $path);

...

    private function generateUrl(string $filter, string $picPath): string
    {
        $image = $this->dataManager->find($filter, $picPath);
        $image = $this->filterManager->applyFilter($image, $filter);
        $this->cacheManager->store($image, $picPath, $filter);
        return $this->cacheManager->resolve($picPath, $filter);
    }
```

### Expected result

As I know from documentation, by default there should be `.webp` images next to the `.jpg` because the 
```yaml
webp:
        generate: true
```
option. The `thumbnail_small` filter should only generate webps for thumbnails.

```console
public/media/cache
├── thumbnail_big
│   └── media
│       └── news
│           ├── 1vpWGn-609c1ca783d243.72915944.jpg
│           ├── 1vpWGn-609c1ca783d243.72915944.webp
│           ├── ALkpaA-609cd51b0afa45.56825315.jpg
│           ├── ALkpaA-609cd51b0afa45.56825315.webp
│           ├── ZPQNzq-609c1c99ee1932.95451227.jpg
│           └── ZPQNzq-609c1c99ee1932.95451227.webp
└── thumbnail_small
    └── media
        └── news
            ├── 1vpWGn-609c1ca783d243.72915944.webp
            ├── ALkpaA-609cd51b0afa45.56825315.webp
            └── ZPQNzq-609c1c99ee1932.95451227.wepb
```

### Actual result

The generated files are
```console
public/media/cache
├── thumbnail_big
│   └── media
│       └── news
│           ├── 1vpWGn-609c1ca783d243.72915944.jpg
│           ├── ALkpaA-609cd51b0afa45.56825315.jpg
│           └── ZPQNzq-609c1c99ee1932.95451227.jpg
└── thumbnail_small
    └── media
        └── news
            ├── 1vpWGn-609c1ca783d243.72915944.jpg
            ├── ALkpaA-609cd51b0afa45.56825315.jpg
            └── ZPQNzq-609c1c99ee1932.95451227.jpg
```
