### ISSUE TITLE
Image metadata is removed without filter strip

### ISSUE THREAD

**Issue by wiseguy1394** [liip/LiipImagineBundle#1420]
We are using the following config for our filters:
```yaml
reading_plans_thumb:
    jpeg_quality:    75
    png_compression_level: 8
    filters:
        auto_rotate: ~
        thumbnail:
            size:          [32,18]
            mode:          outbound
            allow_upscale: true
```

We explicitly not using the filter "strip", but all image metadata is removed.
Is there any possibility to preserve at least some IPTC tags?

In germany it is necessary to keep IPTC copyright tags in the image metadata.
