### ISSUE TITLE
How to fix these depreciations ?

### ISSUE THREAD

**Issue by bastien70** [liip/LiipImagineBundle#1442]
Since last version of the package, we have some depreciations.

### Preconditions
PHP 8.0
liip/imagine-bundle v2.7.0
symfony v5.3

### Depreciations

1. User Deprecated: The Liip\ImagineBundle\Templating\FilterTrait trait is deprecated since version 2.7 and will be removed in 3.0; use Twig instead.

2. User Deprecated: The Liip\ImagineBundle\Templating\FilterExtension class is deprecated since version 2.7 and will be removed in 3.0; configure "twig_mode" to "lazy" instead.

3. The Liip\ImagineBundle\Templating\FilterTrait trait is deprecated since version 2.7 and will be removed in 3.0; use Twig instead.

![image](https://user-images.githubusercontent.com/53140475/147247451-cd9e2044-1350-4393-a62a-da7f759a7bc1.png)

Each time, the stacktrace refers to files that are part of the bundle. Does that mean I don't have to take care of it?

**Comment by dbu** [comment]
the one that says "configure twig_mode" to "lazy" you can already act on. unless you did customization with the twig integration, it will work. if you customized, you need to adjust your customization (which is why we did not make the new mode the default one for 2.x)

the other 2 i think is our BC logic that uses the deprecated code, yes. if you already use the twig functions for your imagine needs, the deprecation should vanish when you upgrade to liip-imagine 3.0 (once it is released) without the need to change your code.

**Comment by bastien70** [comment]
> 

Hum, how can I configure the twig_mode please ? :) I don't see in the twig.yaml file an option to define the mode

**Comment by dbu** [comment]
that is a configuration of liip_imagine: look for "mode" https://symfony.com/bundles/LiipImagineBundle/current/configuration.html

hm, twig_mode in that message is confusing. can you do a PR to change that to liip_imagine.twig.mode instead? i think then it should no longer be confusing.

**Comment by bastien70** [comment]
Yes, no problem

**Comment by EvilSpartans** [comment]
@bastien70  Hello, how did you fix this ? This my config : 

```
liip_imagine:
    driver: "gd"
    filter_sets:
    
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
```
Thanks for your help :)

**Comment by dbu** [comment]
as the deprecation message tells you, you should set the twig mode to lazy
```
liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
```
