### ISSUE TITLE
 Closed Image not generated and "resolve" in path

### ISSUE THREAD

**Issue by Geod-exe** [liip/LiipImagineBundle#1450]
Heyy !
I have the same probleme in symfony 5, when I'm in prod on my computer its okkay but when i push on OVH in production, liip imagine not generate images....
I just read and test all solutions but didnt work....
![Screenshot_20220128_195528](https://user-images.githubusercontent.com/79382688/151605366-36c255c2-c303-4a52-8f2e-ed244ab828f8.png)
```
liip_imagine:
    driver: "imagick"
    default_filter_set_settings:
        format: webp
    resolvers:
        default:
            web_path: ~
    twig:
        mode: lazy
    filter_sets:
        cache: ~
        miniature:
            quality: 75
            filters:
                thumbnail: { size: [390, 220], mode: outbound }
        post:
            quality: 85
            filters:
                thumbnail: { size: [780, 440], mode: outbound }
        crud:
            quality: 75
            filters:
                scale:
                    dim: [600, 600]
        full:
            quality: 95
            filters:
                scale:
                    dim: [1000, 1000]
        about:
            quality: 75
            filters:
                thumbnail: { size: [330, 275], mode: outbound }
```

The default image path is public/img/home/jpg and use full filter

In dev the path is /public/media/cache/<filter>
But in prod path is /public/media/cache/resolve/<filter>/img/.... and its not generate image...

_Originally posted by @Geod-exe in https://github.com/liip/LiipImagineBundle/issues/784#issuecomment-1024517556_
