### ISSUE TITLE
Possible to dynamically define cache directory?

### ISSUE THREAD

**Issue by benr77** [liip/LiipImagineBundle#1497]
How would I go about setting up a dynamic cache directory? e.g.

```yaml
    resolvers:
        media_cache:
            flysystem:
                filesystem_service: oneup_flysystem.media_filesystem
                cache_prefix: '_cache/<INSERT DYNAMIC VALUE HERE>'
```

Is there a service I can override perhaps?

Thanks
