### ISSUE TITLE
Update documention to include phpleague/flysystem

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1500]
**Is your feature request related to a problem? Please describe.**

The Symfony documentation describes a configuration with oneup, but I would like use to phpleague/flysystem

**Describe the solution you'd like*

https://symfony.com/doc/current/LiipImagineBundle/cache-resolver/flysystem.html

```yaml
liip_imagine:
    resolvers:
        profile_photos:
            flysystem:
                filesystem_service: oneup_flysystem.profile_photos_filesystem
                root_url:           "http://images.example.com"
                cache_prefix:       media/cache
                visibility:         public
```

What is an example setting for 

                filesystem_service: # ?? phpleague flysystem class
