### ISSUE TITLE
Generated WebP files have the original file extension, not `.webp`

### ISSUE THREAD

**Issue by quentint** [liip/LiipImagineBundle#1508]
This is not really an issue, as file extensions do not mean much, but it might be a bug, or something that could be covered in the docs (I looked around but didn't find anything about it).

### Preconditions

1. Bundle version: 2.10.0
2. PHP version: 8.1.14
3. GD version: bundled (2.1.0 compatible)

### Steps to reproduce

1. Configure the bundle with `default_filter_set_settings.format: webp`
2. Generate a cached version of a `jpg` or a `png` using a filter set

### Expected result

I **think** the generated files should be named `{original-name}.{original-extension}.webp` or `{original-name}.webp`.

### Actual result
The generated files are name exactly like the original ones, including the original extension.

The generated files are indeed WebP ones (the first characters are `RIFF(   WEBPVP8`), so I'm confident the `default_filter_set_settings` were honored, but the file names are a bit surprising 😉 

As I lost some time trying to figure out why the format was not respected (I was wrong), I was wondering:
- Is this on purpose?
- If so, should the docs be updated to explain it?

Thanks for such a handy bundle!

**Comment by AnthonyDUSART** [comment]
I'm currently having the same problem

**Comment by stuba** [comment]
Same here with bundle version 2.11.0

**Comment by quentint** [comment]
I found how to fix that.

I'm not entirely sure why, but if you want your files to end up with the `.webp` extension, you have to explicitly configure your bundle with:

```yaml
liip_imagine:
    webp:
        generate: true
```

It appears in the docs here: https://symfony.com/bundles/LiipImagineBundle/current/basic-usage.html#use-webp-if-supported

I'm not sure I fully understand how `format: webp` and `web.generate: true` cooperate 😉  
I hope this helps!

**Comment by quentint** [comment]
And now I realize setting `web.generate: true` generates both original and webp images, and then redirects to the best option based on browser support (as stated in the docs).

So I guess what we'd need is a proper way to use [WebP for all](https://symfony.com/bundles/LiipImagineBundle/current/basic-usage.html#webp-for-all) and have the correct `.webp` extension 🤔 (Google's PageSpeed Insights seems to care about this).

**Comment by stuba** [comment]
Yes I'm using webp for all images and not bothered if there is less than 4% of global audience not supporting this format. I prefer keeping things nice and simple. HTML for supporting both formats seems more complex (and might be easier to break by mistake).

SO far I have not noticed any issues with images having wrong extension, but would prefer webp as it should.

**Comment by virtualize** [comment]
For generated webp images to have the `.webp` extension use the [FormatExtensionResolver](https://symfony.com/bundles/LiipImagineBundle/2.x/cache-resolver/format_extension.html) like this:

services.yaml
```yaml
    # https://symfony.com/bundles/LiipImagineBundle/2.x/cache-resolver/format_extension.html
    Liip\ImagineBundle\Imagine\Cache\Resolver\FormatExtensionResolver:
        arguments:
            - '@liip_imagine.cache.resolver.default'
            - '@liip_imagine.filter.configuration'
        tags: [{ name: "liip_imagine.cache.resolver", resolver: "format_extension" }]
```

lip_imagine.yaml
```yaml
liip_imagine:
    cache: format_extension
    #...
```
