### ISSUE TITLE
Resolve Programmatically not generate cache

### ISSUE THREAD

**Issue by ziat1988** [liip/LiipImagineBundle#1512]
I want to pre-generate the cache, by doing:
```php
public function yourControllerMethod(CacheManager $imagineCacheManager)
    {
        /** @var string */
        $resolvedPath = $imagineCacheManager->getBrowserPath('/relative/path/to/image.jpg', 'my_thumb');

        // ...
    }
```
But there are no cache generated in media/cache. I tried the console `php bin/console liip:imagine:cache:resolve relative/path/to/image.jpg --filters=my_thumb` then it works perfectly. 
So is it possible to resolve in the code, controller or service? The reason I want to do this is because I have some heavy task image and I want to pre generate the cache before the client request.

Here is my config: 
```yaml
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default :
            web_path : ~
    filter_sets:
        my_thumb:
            quality: 70
            filters:
                thumbnail: { size: [120, 90], mode: outbound, allow_upscale: true  }
                background: { size: [124, 94], position: center, color: '#000000' }
```
Thanks
