### ISSUE TITLE
Question about Loaders

### ISSUE THREAD

**Issue by genby8** [liip/LiipImagineBundle#1513]
1. PHP Version 8.1.14
2. GD 2.1.0 compatible
3. Symfony 5.4.24
4. liip/imagine-bundle 2.10.0

my real file path: `/public/upload/my_media/filename.jpg`

my config:
```
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: "/upload/media/cache"
    loaders:
        default:
            filesystem:
                data_root:
                    photo: '/upload/my_media'
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
```

in Twig template use:
`{{ asset('@photo:filename.jpg')|imagine_filter('my_thumb') }}`

result:
`https://my_domain/media/cache/resolve/my_thumb/@photo:filename.jpg`

Photo not show.
Why url not: `https://my_domain/upload/media/cache/my_thumb/upload/my_media/filename.jpg`

From documentation [(here)](https://symfony.com/bundles/LiipImagineBundle/current/data-loader/filesystem.html)

> Given the above configuration, you can explicitly request a root path using the format @index:path/to/file.ext. For example, to request the file /a/foo/path/with/file.ext you can pass @foo:with/file.ext as the filename.

Or are loaders not for that? Or does this functionality no longer exist, but remains in documentation?
