### ISSUE TITLE
Transparent background with gmagick

### ISSUE THREAD

**Issue by ro0NL** [liip/LiipImagineBundle#1519]
Hi,

We try to put a scaled transparent image on a fixed transparent background, using gmagick.

Our filter looks like:

```yaml
liip_imagine:
    driver: gmagick
    default_filter_set_settings:
        format: webp
    filter_sets:
        some_thumb:
            filters:
                strip: ~
                scale:
                    dim: [ 100, 100 ]
                background:
                    size: [ 100, 100 ]
                    transparency: 100
```

However the final image is not transparent anymore due `background`.

Im wondering if this is a gmagick issue, or a config one.
