### ISSUE TITLE
Overriding configuration for specific env is broken

### ISSUE THREAD

**Issue by Seb33300** [liip/LiipImagineBundle#1534]
I am trying to use the `when@dev` syntax to override the config for a specific env, but this seems to not work as expected.

For example:

``` yaml
liip_imagine:
    driver: "imagick"

    twig:
        mode: lazy

    loaders:
        default:
            filesystem:
                locator: filesystem_insecure

    resolvers:
        default:
            web_path:
                cache_prefix: cache

when@dev:
    liip_imagine:
        driver: "gd"
```

On dev environment the resolver option defined previously is no longer taken in account.
