### ISSUE TITLE
How to correct set cachePrefix for S3 resolver?

### ISSUE THREAD

**Issue by indapublic** [liip/LiipImagineBundle#1542]
```
acme.imagine.cache.resolver.aws_s3_resolver:
    class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
    arguments:
        - '@aws.s3'
        - '%env(S3_BUCKET)%'
    tags:
        - { name: 'liip_imagine.cache.resolver', resolver: 'aws_s3_resolver' }
    calls:
        - [setCachePrefix, ["cache"]]
```

But when I debug `getObjectPath` cachePrefix is nullable
