### ISSUE TITLE
Is it possible to configure a path prefix for loaders?

### ISSUE THREAD

**Issue by WishCow** [liip/LiipImagineBundle#157]
I'm using 0.9.1, and have the following config:

``` yaml
data_root: %kernel.root_dir%/../web/media/
    filter_sets:
        avatar:
            filters:
                thumbnail: { size: [ 150, 150 ], mode: outbound }
```

The web root is web/, the uploaded avatars go into web/media/avatar/, the cache directory is web/media/cache/. Cached avatars land in web/media/cache/avatar/avatar/ (notice the double avatar).

I have a user object that has a "picture" property, which stores the filename of uploaded file (I'm using VichUploader), and I'm showing the thumbnails in my twig templates with:

``` jinja
<img src="{{ ('/avatar/' ~ user.picture)|imagine_filter('avatar') }}"/>
```

Everything is working fine, but I would like to render an image without including the /avatar/ part, like this:

``` jinja
<img src="{{ user.picture|imagine_filter('avatar') }}"/>
```

Is it possible to do this somehow? I have looked into the configuration attribute "path" under filter_sets, but that seems to only alter where the files are cached, and not where they are looked up. I tried implementing a custom loader, but the loader does not get any information of the filter set being used, only the path that was passed to the twig filter.

Am I missing something? Should I try to tackle this problem from the uploading side and include the prefix with the filename?
