### ISSUE TITLE
Images are automatically rotated

### ISSUE THREAD

**Issue by MichaelBrauner** [liip/LiipImagineBundle#1580]
I have the following config: 

```yaml
        my_filter:
            quality: 85
            jpeg_quality: 85
            filters:
                auto_rotate: ~

```
And if this is then applied to an image that was taken upright with an iPhone, for example, then the image is always rotated. 

### Preconditions
PHP: 8.2.18
GD: bundled (2.1.0 compatible)
Liip: 2.12.2

### Steps to reproduce

Here is such a picture. It should be rotated, regardless of whether autorate is switched on or not.
![image](https://github.com/liip/LiipImagineBundle/assets/4937572/d7a08e33-1238-4477-8815-e182713b9168)
