### ISSUE TITLE
bad yaml in documentation

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1581]
```yaml
cache: aws_s3_resolver
    filter_sets:
        cache: ~
        user_thumbnail:
            cache: aws_s3_resolver
            quality: 75
            filters:
```

on https://symfony.com/bundles/LiipImagineBundle/current/events.html

This YAML isn't right.  I'm not sure what it's supposed to be.  I don't use OneUp, I was looking for an example using flysystem that has the _cached_ images stored on s3 instead of locally.
