### ISSUE TITLE
Imagine Bundle and AssetMapper

### ISSUE THREAD

**Issue by ebitkov** [liip/LiipImagineBundle#1608]
### Discussed in https://github.com/liip/LiipImagineBundle/discussions/1605

<div type='discussions-op-text'>

<sup>Originally posted by **ebitkov** August 19, 2024</sup>
The current recommendation to handle assets is to use the AssetMapper component (https://symfony.com/doc/current/frontend/asset_mapper.html), which integrates with the Twig `asset` function and automatically adds versioning to images.

As stated in the documentation, the bundle should automatically detect the versioning and handle it: https://symfony.com/bundles/LiipImagineBundle/current/asset-versioning.html.

But for me it seems not to do it. I get a "404 - Source image for path could not be found" error.

So I'm wondering: Does this bundle support the new AssetMapper component? And if yes, am I the only one, who has problem with it? </div>

---

As described in the discussion above, [Symfony recommends the relative new AssetMapper component as the preferred way to handle your assets](https://symfony.com/doc/current/frontend.html#assetmapper-recommended), especially for new projects. The documentation of the Imagine Bundle describes, [that it supports asset versioning](https://symfony.com/bundles/LiipImagineBundle/current/asset-versioning.html), but I noticed, that the AssetMapper component is currently not supported.

When using AssetMapper, accessing a file via the `asset` Twig function and then applying a filter on it results in a `404 - source image for path could not be found` error.

Here is a simple reproducer to test with: https://github.com/ebitkov/liip-imagine-bundle-and-asset-mapper

**Comment by celsoandrade** [comment]
I've tried to add 

```yaml
loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public'
                    - '%kernel.project_dir%/assets/images'
 
```
                    
but it didn't work
