### ISSUE TITLE
Document how to share filter sets with multiple data loaders

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1613]
I have several data loaders in flysystem.  In the liip configuration, I can either set the default data loader for all filter sets, OR set a data loader within each filterset.  

But I want to apply the same filter to multiple sets.  

```yaml
    loaders:
        flysystem_loader:
            flysystem:
                # this comes from flysystem.yaml
                filesystem_service: default.storage

    # default loader to use for all filter sets
    data_loader: flysystem_loader
    filter_sets:
        auto_rotate: ~
        large_s3:
            data_loader: s3.storage
            filters:
                thumbnail:
                    size:          [400, 400]
                    allow_upscale: true
                    mode: inset
        large:
            filters:
                thumbnail:
                    size:          [400, 400]
                    allow_upscale: true
                    mode: inset
```

in flysystem

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/src'
        uploads.storage:
            adapter: 'local'
            options:
                 directory: '%kernel.project_dir%/private/uploads'
        s3.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance,
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                streamReads: true
                prefix: '%env(S3_STORAGE_PREFIX)%'

```

I know which flysystemOperator I have, I want to pass it into the `imagine_filter` filter in twig, and the `cache->getBrowserPath()` method in php, but there seems to be no way to indicate which datasource.

I see I can use a [chain loader](https://symfony.com/bundles/LiipImagineBundle/current/data-loader/chain.html), but that could get expensive if I have multiple could-based loaders and it has to loop through them to find the right one.  

Thoughts on how this might be done?
