### ISSUE TITLE
WebP caching issue: 301/302 redirects cause the browser to reload images on every request

### ISSUE THREAD

**Issue by BriceFab** [liip/LiipImagineBundle#1617]
### Preconditions
1. **LiipImagineBundle version**: "liip/imagine-bundle": "^2.13"
2. **Symfony version**: 6.4
3. **PHP version**: 8.2
4. **Web Server**: Apache
5. WebP support enabled in `liip_imagine.yaml` with the following configuration:

```yaml
liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    webp:
        generate: true
        quality: 75
        cache: true
    controller:
        redirect_response_code: 302
    twig:
        mode: lazy

    filter_sets:
        cache: ~

        dynamic_webp:
            format: webp
            quality: 85
            filters:
                thumbnail: { mode: inset, position: center }

        dynamic_jpeg:
            format: jpeg
            quality: 85
            filters:
                thumbnail: { mode: inset, position: center }
```

### Steps to reproduce
1. Configure `liip_imagine.yaml` to enable WebP generation (`webp.generate: true`).
2. Implement the WebP with dynamic filter
  ```
  {% set webpLgSrc = this.src|imagine_filter('dynamic_webp', {'thumbnail': {'size': [scaledLgWidth, scaledLgHeight]) %}
  ```
3. Request an image with a filter applied, for example:
   ```
   GET /media/cache/resolve/my_filter/path/to/image.jpg
   ```
4. Observe the response:
   - A `301` or `302` redirect is returned to the WebP variant.
   - The browser then requests the redirected WebP image.
5. Headers cache is ignored on the redirect request. Apache config:
```
   <FilesMatch "\.(js|jpg|jpeg|gif|png|css|tgz|gz|rar|bz2|doc|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|woff|woff2|svg|mp3|mp4|webp)$">
        Header always set Pragma "public"
        Header always set Cache-Control "max-age=2592000, public"
        Header always set X-Image "cached"
    </FilesMatch>
```

### Expected result
1. The browser should cache the WebP image after the first request and avoid reloading it unless the cache is invalidated.

### Actual result
1. The browser reloads the WebP image on every request, despite valid `Cache-Control` headers being present.
2. Example response headers for the redirected WebP image:
   ```
   HTTP/1.1 200 OK
   Cache-Control: max-age=2592000, public
   ```
3. The repeated reloading causes unnecessary server load and impacts page performance.

### Additional notes
- Changing `redirect_response_code` to `301` in `liip_imagine.yaml` does not resolve the issue.
- It seems that the 301/302 redirect interferes with browser caching mechanisms.
- Suggested improvement: Provide an option to serve WebP images directly without using redirects, or enhance documentation on optimizing caching for WebP ?
- Online reproducing issue: https://test.fitmetrics.ch/en/about-us
- Video of the issue: https://github.com/user-attachments/assets/078c1fa3-c21b-454a-9af6-5a2a5d2ff594 (image reload issue) in comparaison with png/jpg https://github.com/user-attachments/assets/e14a2bec-cb58-42d1-9f05-70b40cb7d326 (image no reload issue)

Thank you in advance for any support!
