### ISSUE TITLE
Complete S3 Setup: Original Images and cached Images on AWS S3

### ISSUE THREAD

**Issue by KeKs0r** [liip/LiipImagineBundle#203]
I have already commented on this issue ( #63 ), but the whole thing might be worth an own topic. It might be the case that I just misconfigured the whole thing but I can't find out which part i misconfigured or is not working.

I try to create a full S3 setup, which means that the original images come from S3 (which should be handlet by the stream data loader, as far as I understood it) and also the cache should be saved onto S3 which should be handled via the S3 cache resolver.

However parts or the whole thing is not working in my setup:

Services:

```
services:
    amazonS3:
        class: AmazonS3
        arguments:
            options:
                key:      '%aws_key%'
                secret:   '%aws_secret_key%'
                certificate_authority: "%kernel.root_dir%/Resources/cert/cacert.pem"


    liip_imagine.data.loader.stream.profile:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - 'gaufrette://profile/'
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'stream.profile' }

    liip_imagine.cache.resolver.amazon_s3:
          class: Liip\ImagineBundle\Imagine\Cache\Resolver\AmazonS3Resolver
          arguments:
              - "@amazonS3"
              - "%aws_s3_bucket%"
          tags:
              - { name: 'liip_imagine.cache.resolver', resolver: 'cache.amazon_s3' }
```

Imagine and Gaufrette Setup:

```
knp_gaufrette:
    stream_wrapper:
        filesystems:
            profile: profile_fs
    adapters:
        team_adapter:
            amazon_s3:
                amazon_s3_id: amazonS3 
                bucket_name: %aws_s3_bucket%
                options:
                    create: true
                    directory:  teams
        profile_adapter:
            amazon_s3:
                amazon_s3_id: amazonS3 
                bucket_name: %aws_s3_bucket%
                options:
                    create: true
                    directory:  profile
    filesystems:
        team_fs:
            adapter:    team_adapter
        profile_fs:
            adapter:    profile_adapter


liip_imagine:
    cache: cache.amazon_s3
    formats:              []
    filter_sets:           
        profile_thumb:
            data_loader: stream.profile
            quality: 75
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        profile_thumb_small:
            data_loader: stream.profile
            quality: 75
            filters:
                thumbnail: { size: [30, 30], mode: outbound }

```

The original Images are uploaded via VichUploaderBundle which is working perfectly fine. But the cache images are not created anywhere and the url returned by the view helper looks also very odd:

```
<img class="img-profile" src="/web/app_dev.php/media/cache/profile_thumb/gaufrette://profile_fs/51d44401a4bd5.jpeg">
<img class="img-profile" src="gaufrette://profile_fs/51d44401a4bd5.jpeg">

```

The referenced view looks like this

```
            <img class="img-profile" src="{{ user.profilePic | imagine_filter('profile_thumb', false) }}" />
            <img class="img-profile" src="{{ user.profilePic }}" />
```

 Has someone a working setup with both the gaufrette stream data loader and a cache resolver? Maybe @neilferreira?

Or could someone point me in the right direction to figure this out?

------------------ edit -------------------
For the referenced Issue here is my VichUploaderConfig:

```
vich_uploader:
    db_driver: orm # or mongodb
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        team_logo:
            uri_prefix:  https://s3-eu-west-1.amazonaws.com/%aws_s3_bucket%/teams # you'll need this set to use the Vich URL generator
            upload_destination: team_fs
        profile_image:
            uri_prefix: https://s3-eu-west-1.amazonaws.com/%aws_s3_bucket%/profile # you'll need this set to use the Vich URL generator
            upload_destination: profile_fs
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
```
