### ISSUE TITLE
Grab image from web and display it

### ISSUE THREAD

**Issue by ghost** [liip/LiipImagineBundle#213]
Hello,

I try to write a function that grab an image from an external website and display it on mine.
I read in the issue #187 to use Gaufrette and streamloader but the documentation don't help me very much...

I try this in my config 

``` yml
knp_gaufrette:
    adapters:
        local_adapter:         
            local:
                directory: %kernel.root_dir%/../web/media/gaufrette

    filesystems:
        covers:
            adapter:    local_adapter

    stream_wrapper: ~

liip_imagine:
...
    filter_sets:
        covers:
            data_loader: stream
            filters:
                thumbnail: { size: [480, 760], mode: outbound }
```

And services

``` yml
    liip_imagine.data.loader.stream.covers:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - 'gaufrette://covers/'
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'stream.covers' }
```

But I don't understand how to use it in my controller and in my twig templates.

Can someone write me a very simple exemple with the controller, services and twig template or tell me what is wrong?

Thx
