### ISSUE TITLE
Thumbnail filter calculation issue

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#215]
This relates to https://github.com/avalanche123/Imagine/issues/239

I am not sure if there is something we can do on the bundles end to resolve this?

Here is my filter set

``` yaml
file_manager_thumb:
            quality: 70
            filters:
                strip: ~
                thumbnail: { size: [80, null], mode: inset }
```
