### ISSUE TITLE
No images created in cache

### ISSUE THREAD

**Issue by kweij** [liip/LiipImagineBundle#218]
I don't seem to get the bundle working for me and after several hours of searching I can't find out what I am doing wrong.

Here is my config:

```
liip_imagine:
    cache_prefix: /bundles/lsgcms/uploads/employee-photos/cache
    filter_sets:
        cms_employee_photo_thumb:
            quality: 50
            filters:
                thumbnail: { size: [60, 80], mode: outbound }
```

Here is my twig:

```
<img src="{{ employee.webPathPhoto | imagine_filter('cms_employee_photo_thumb') }}" />
```

"employee.webPathPhoto" contains the string:

```
bundles/lsgcms/uploads/employee-photos/55efa63629ffde4e75f5a06a8ea2492c2c3e6664.jpeg
```

This script runs at:

```
http://www.example.org/workspace/kweij/dev/web/app_dev.php/
```

This results in:

```
<img src="/workspace/kweij/dev/web/app_dev.php/bundles/lsgcms/uploads/employee-photos/cache/cms_employee_photo_thumb/bundles/lsgcms/uploads/employee-photos/55efa63629ffde4e75f5a06a8ea2492c2c3e6664.jpeg">
```

The "/bundles/lsgcms/uploads/employee-photos/cache" directory has chmod 0777, so is writable. However, no images get made/cached.

Also, the generated link to the image contains "/app_dev.php/". That cannot not be right, can it?
