### ISSUE TITLE
Impossible to generate thumbs and cache folder

### ISSUE THREAD

**Issue by neovea** [liip/LiipImagineBundle#223]
I worked on it all the day long and I can't find any answer.
I have : 
in composer.json -> 

```
    "imagine/imagine": "0.4.1",
    "liip/imagine-bundle": "dev-master"
```

in routing.yml -> 

```
     _imagine:
        resource: .
        type:     imagine
```

in appkernel -> 

```
    new Liip\ImagineBundle\LiipImagineBundle(),
```

in config.yml -> 

```
    liip_imagine:
        formats: ['jpg', 'jpeg', 'png', 'gif']
        filter_sets:
            thumb:
                quality: 80
                filters:
                    thumbnail: { size: [150, 150], mode: inset, allow_upscale: true}
```

All my images are in http://localhost/my_project/web/uploads/gallery/

In my db I have my pictures with a unique name (generated by OneUpUploaderBundle

In twig -> 
        img src="{{ path }}{{ file.name | imagine_filter('thumb') }}"

the url generated looks like -> http://localhost/my_project/web/uploads/gallery//my_project/web/app_dev.php/media/cache/thumb/51fd0d41dad3a.jpeg

And when I try :

In twig -> 
        img src="{{ file.name | imagine_filter('thumb') }}" (so I dont have the path anymore)

the url generated looks like -> 
http://localhost/my_project/web/app_dev.php/media/cache/thumb/51fd0d41dad3a.jpeg

What am I doing wrong ?

EDIT : Actually it only works for : 
{{ 'real/path/and/name.ext' | imagine_filter('thumb') }}
not for : 
{{ file.twig.tag | imagine_filter('thumb') }}

is it right ?
