### ISSUE TITLE
Can't use different input and output formats

### ISSUE THREAD

**Issue by jaikdean** [liip/LiipImagineBundle#224]
If I had an image in one format and want to generate an image in another, things appear to break. For example:

``` yaml
liip_imagine:
    …
    filter_sets:
        test_size:
            quality: 50
            format:  jpg
            filters:
                thumbnail: { size: [280, 152], mode: inset, allow_upscale: true }
```

``` twig
{{ 'path/to/image.png'|imagine_filter('test_size') }}
```

This attempts to load a URL ending in `image.jpg`. This is the correct output format, but it means the original image can't be found.
