### ISSUE TITLE
Perfomance Issues

### ISSUE THREAD

**Issue by KeKs0r** [liip/LiipImagineBundle#225]
Hi,

I am having several sites where I show a lot of user profile picture thumbs. Those sites are extremely slow. I think it is related to the imagine filter. I have created a performance test, that collects the exact same data as my controller and then accesses the exact same variables / functions as my view. 

All those calculations take about 8ms, but as soon as I add the following line it takes already 2 seconds ( for 2 users, exponentially growing with number of users, because its in a loop):

``` php
$imagineCManager = $this->get('liip_imagine.cache.manager');

foreach($group->getUsers as $user){
$data[] = $imagineCManager->getBrowserPath($user->getProfilePic(), 'profile_thumb_small', false);
}
```

Why is that so slow? My backend is Gaufrette with AmazonS3. I thought there would be a CacheManager in between, that might cache the paths or something. Or the path itself can easily calculated from $user->getProfilePic(), because the original file is in my bucket under profile/$profilePicName  and the filtered file would be under profile_thumb_small/$profilePicName. But to "calculate" this, it still takes about a second.

Also in prod the request goes through my webserver instead of just resolving the link:

``` html
<img src="/web/app.php/media/cache/profile_thumb_small/52136f2930e36.jpeg" alt="degi" class="thumbnail-small">
```

**Comment by plamenh** [comment]
Ok, I setup the CacheResolver wraper, but we still get a huge slowdown (about 30 seconds). This happens on serializing entities:

```
public function onPostSerialize(ObjectEvent $event)
    {
        $object = $event->getObject();
        $visitor = $event->getVisitor();
        /* @var $visitor GenericSerializationVisitor */
        $path = $this->uploaderHelper->asset($object, 'file');
        $urls = array();
        foreach (array('carouselImage', 'carouselImage2x', 'profilePhoto', 'profilePhoto2x', 'companyLogo') as $pattern) {
            $urls[$pattern] = $this->cacheManager->getBrowserPath($path, sprintf('%s', $pattern));
        }
        $visitor->addData('image_urls', $urls);
    }
```

Cache settings:

```
app.s3:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: 'latest'
                region: 'fra1'
                endpoint: '%env(S3_BASE_URL)%'
                credentials:
                    key: '%env(S3_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'

    app.imagine.cache.resolver.s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@app.s3"
            - '%env(S3_BUCKET_NAME)%'
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "default" }

cache.apcucache:
        class: Doctrine\Common\Cache\ApcuCache

    acme.imagine.cache.resolver.s3.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@cache.apcucache"
            - "@app.imagine.cache.resolver.s3"
            - { prefix: "s3" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_s3" }
```

Imagine settings:

`cache: cached_s3`
