### ISSUE TITLE
Including filters inside filters

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipImagineBundle#255]
Is there anyway to include a filter inside a filter?

We are uploading very large images (4000 pixels by 4000 pixels). For most of the image sizes we don't want the server to use the full sized image to complete a resize.

Instead, it would be best if it used a smaller image size for processing (eg 800x800). This will save memory/cpu.

``` yaml
filter_sets:
    base:
        filters:
            strip: ~
            thumbnail: { size: [800, 800], mode: inset }
    small:
        filters:
            prefilter: base
            thumbnail: { size: [120, 120], mode: inset }
    medium:
        filters:
            prefilter: base
            thumbnail: { size: [300, 300], mode: inset }
```

I was thinking about putting something like this together in a filter. However, I don't think it belongs in a filter because it needs to extract the base image using the cache as if the system normally would.

If you were to render the "small" and "medium" filter it would first create an image for "base" (once only) and then use that base image to render the others.

I am happy to try and work on something like this. Would love some input from others that are more involved before proceeding though.
