### ISSUE TITLE
Thumbnail filter parameter allow_upscale doesn't work

### ISSUE THREAD

**Issue by USvER** [liip/LiipImagineBundle#264]
allow_upscale doesn't do anything
This produce cached images smaller than 150x150

``` yaml
liip_imagine:
    filter_sets:
        thumb150x150:
            quality: 75
            filters:
                strip: ~
                thumbnail: 
                    size: [150, 150]
                    mode: outbound
                    allow_upscale: true
```

Workaround to use "upscale" filter before thumbnail. But it will give some overhead...
I'm using ImageMagick
