### ISSUE TITLE
can't store generated cache files in the right emplacement

### ISSUE THREAD

**Issue by ikodev** [liip/LiipImagineBundle#289]
Hello,

(sorry in advance for my pooooor english...)

I am using a Custom Filter that crop images from fixed values (config.yml) and dynamic values (sent by Form).

The problem is that the re-generation of the cache-files FROM my dynamic treatment (a listener that use datamanager, cachemanager etc...) doesn't target the right directory specified in config.yml, it's simply put the file under the web_root without consider any of prefix_cache or filter path.

There is the famous line (return line) :

``` php
$response = $filterManager->get($this->getRequest(), $filter, $image, $file->getFilename());
return $cacheManager->store($response, $file->getFilename(), $filter);
```

There is my config :

``` yml
liip_imagine:
    web_root:     %kernel.root_dir%/../web
    data_root:    %kernel.root_dir%/../web/uploads
    filter_sets:
        custom_filter:
          path: /toto/titi
          filters:
            crop: { start: [0, 0], size: [1200, 200] }
```

If I do a first page load (on my browser), the cache file is well generated by the view which simply do this : 

``` html
<img src="{{ ('group.png') | imagine_filter('custom_filter') }}" />
```

I can see the file in the right emplacement : /web/media/cache/toto/titi/group.png
Good !

But when I use my dynamic cropping, the cache file is generated here : 
/web/group.png

Any idea ?

This works but of course, I don't want this...... : 

``` php
...
return $cacheManager->store($response, 'media/cache/toto/titi/' . $file->getFilename(), $filter);
```

Thanks for help !
