### ISSUE TITLE
jpg image quality? avoid recoding jpg when not needed?

### ISSUE THREAD

**Issue by dbu** [liip/LiipImagineBundle#296]
i have a case where usually the uploaded jpg is exactly the resolution that is needed. i would still love to pass this through a filter to ensure the size is always the expected one. this works out:

```
           upscale: { min: [270, 152] }
           thumbnail: { size: [270, 152], mode: outbound }
```

the problem is that a) the image quality gets quite a lot worse, even when i do `quality: 100` and even when making the `format: png` (the uploaded image was still jpg - the quality gets a bit better, but far from good).

my full configuration is:

```
    two_columns:
        data_loader: cmf_media_doctrine_phpcr
        format: jpg
        # also tried to comment out the quality in the hope to avoid recoding
        quality: 100
        # also tried with commenting out all filters
        filters:
            upscale: { min: [270, 152] }
            thumbnail: { size: [270, 152], mode: outbound }
```

the configured data_loader only loads a binary stream and returns that, no further manipulations done. 

so i have two questions:
1. why is my quality so inferior?
2. if i did not do something stupid and the behaviour already is there: can we do something to avoid recoding the jpg altogether when nothing has to be done? the filters could notice they can skip their job and in the end we deliver the raw image. that would probably be faster, and for sure give the best result.

original image:
![original](https://f.cloud.github.com/assets/76576/1879193/209bbd1e-7946-11e3-9d9f-f3723fcea2ec.jpg)

with the above filter:
![imagine](https://f.cloud.github.com/assets/76576/1879194/248e7ac4-7946-11e3-84eb-05924bcf63ce.jpg)
