### ISSUE TITLE
S3 configured setup still uses we_path for cache

### ISSUE THREAD

**Issue by dotstormz** [liip/LiipImagineBundle#324]
Hi,

I am attempting to move my cache images over to an S3 bucket to save space on my server. I have followed the setup guide for the AwsS3Resolver but it is not working.

No errors are being thrown, though all newly cached images are still pointing to the default web_path are are displaying (but not with an S3 bucket path)

Config is as follows: 

```
services:
    acme.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method:  factory
        arguments:
            -
                key: %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%

    acme.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@acme.amazon_s3"
            - "%amazon_s3.bucket%"
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'amazon_s3' }

liip_imagine:
    driver:               imagick
    cache:                'amazon_s3'
```

The key, secret and region parameters have been set correctly.

I am on Symfony 2.1.13 using imagine/Imagine v0.5.0 and liip/imagine-bundle v0.19.0 (have tried dev-master and v0.20.0 with no luck)
