### ISSUE TITLE
Does LiipImagineBundle support remote image? 

### ISSUE THREAD

**Issue by saharabear** [liip/LiipImagineBundle#328]
I have try the following code: 

```
{{'http://www.other-domain.com/img.jpg'|imagine_filter('face')}}
{{'http://www.my-domain.com/my-img.jpg'|imagine_filter('face')}}
```

LiipImagineBundle does not generate cache, but I tried the following code: 

```
{{'/my-img.jpg'|imagine_filter('face')}}
```

Now it works. 

Any way to process pictures with absolute URL or remote pictures? 

Thanks.

**Comment by flug** [comment]
@makasim Is there a reason why this is not built-in the bundle ? This would be a great feature. I could contribute it if necessary.

**Comment by makasim** [comment]
@flug Could you please remember me what problem you are trying to solve?

**Comment by greg0ire** [comment]
@makasim he was trying to get this bundle to work with remote images, gave up and wrote this : https://github.com/flug/imagine-bundle

**Comment by makasim** [comment]
sorry, but I am trying to understand the real problem which you all guys want to solve. It is not clear too me. the code posted is not looking good and clear too. So please describe the problem so I can help you with the solution.

**Comment by greg0ire** [comment]
We have images stored on a remote server. We want to resize them and store them locally.

**Comment by makasim** [comment]
Try https://github.com/liip/LiipImagineBundle/blob/master/Binary/Loader/StreamLoader.php loader. I believe it must fit your needs.

**Comment by greg0ire** [comment]
We'll have a look at that, thanks a lot !

**Comment by aistis-** [comment]
Could someone post a clean solution with `StreamLoader`?

**Comment by ibasaw** [comment]
the solution of : @mechanicalgux doesn't work anymore. How to use CDN url absolute path asset with filter ?

    image.absolutepath|imagine_filter('my_filter_medium')

**Comment by maxlipsky** [comment]
@ibasaw You need define StreamLoader as service:
```
app.imagine.cdn_data_loader:
    class: "%liip_imagine.binary.loader.stream.class%"
    arguments:
        - '' # if you store full path in the database
    tags:
        - { name: 'liip_imagine.binary.loader', loader: 'cdn_data_loader' }
```

And to config:

```
filter_sets:
    my_filter_medium:
        data_loader: cdn_data_loader
        filters: # your filter
```

**Comment by xmon** [comment]
@maxlipsky I can not run the code, do you know of any place where there is a complete functional example? 

thanks a lot

**Comment by alainib** [comment]
i followed @mechanicalgux advice. i didn't have a services.yml file so i create one in app/config but i get the following error :

An exception has been thrown during the rendering of a template ("Could not find resolver "my_remote_resolver" for "square_thumb" filter type") in PlantnetDataBundle:Backend\Admin:gallery.html.twig at line 39. 

where to put services.yml file and how to load it please ( i'm not familiar with symfony at all)

**Comment by mechanicalgux** [comment]
I was using version LiipImagineBundle 0.21.1 with Symfony 2.6.4 at the time I wrote the posts. I haven't use this bundle on other projects and haven't updated anything since so I don't know what are the changes made that make the code fail in new versions.

@alainib you need to define crops in your config.yml

## config.yml
```
liip_imagine:
    filter_sets:
        cache: ~
        square_thumb:
            cache: my.remote_resolver
            data_loader: my.remote_loader
            quality: 75
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
```

Place your service.yml file in app/config/service.yml

**Comment by alainib** [comment]
@mechanicalgux thank for the very fast response.
I use symfony 2.3 and liip dev-master

the error :
There is no extension able to load the configuration for "my.remote_loader" (in /var/www/testclean/publishv2/app/config/services.yml).

My config.yml

        liip_imagine:
            #cache_clearer: false
            #cache_mkdir_mode: 0777
            # configure resolvers
            resolvers :
                # setup the default resolver
                default :
                    # use the default web path
                    web_path : ~

            # your filter sets are defined here
            filter_sets :
                # use the default cache configuration
                cache: ~
                square_thumb:
                    cache: my.remote_resolver
                    data_loader: my.remote_loader
                    quality: 75
                    filters:
                        thumbnail: { size: [64, 64], mode: outbound }
                max_width_900:
                    filters:
                        relative_resize: { widen: 900 }
                thumb_100_100:
                    filters:
                        thumbnail: { size: [100, 100], mode: outbound }
                thumb_template:
                    filters:
                        crop: { start: [0, 0], size: [270, 350] }
                thumb_idao:
                    filters:
                        thumbnail: { size: [120, 80], mode: outbound }
                thumb_180_120:
                    filters:
                        thumbnail: { size: [180, 120], mode: outbound }
                thumb_370_210:
                    filters:
                        thumbnail: { size: [370, 210], mode: outbound }
                thumb_130_75:
                    filters:
                        thumbnail: { size: [130, 75], mode: outbound }
                thumb_max_width_100:
                    filters:
                        relative_resize: { widen: 100 }
        `
 my twig :
        `<a href="{{ asset(img) }}" class="grouped_elements" rel="group" title="{{ row.copyright }}">
						<img src="{{ asset(img) | imagine_filter('square_thumb') }}" alt="{{ imgspe }}" border="0" />
					</a>        `

i put RemoteStreamLoader.php in
        `.../vendor/liip/imagine-bundle/Liip/ImagineBundle/Binary/Loader/`

i put RemoteCacheResolver.php in
        `.../vendor/liip/imagine-bundle/Liip/ImagineBundle/Imagine/Cache/Resolver/`

What i'm missing ? thanks

**Comment by mechanicalgux** [comment]
@alainib did you assign the correct class to your my.remote_loader service?
In my previous snippet I wrote:
```
my.remote_loader:
        class: %my.remote_loader.class%
```
But you need to define the parameter ```my.remote_loader.class```, or simply directly point to your class:
```
my.remote_loader:
        class: AppBundle\Service\RemoteStreamLoader
```
(in service.yml)

**Comment by alainib** [comment]
ok the `%my.remote_loader.class%` is a variable defined in another config file. no i didn't do it, just past it like that ;) 

my services.yml file : 

       my.remote_loader:
		    class: AppBundle\Service\RemoteStreamLoader
		    arguments: [@liip_imagine, %liip_imagine.formats%]
		    tags:
		        - { name: liip_imagine.data.loader, loader: my_remote_loader }

		my.remote_resolver:
		    class: AppBundle\Service\RemoteCacheResolver
		    arguments: [@filesystem]
		    tags:
		        - { name: liip_imagine.cache.resolver, resolver: my_remote_resolver }


but the error is the same : 

        PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException' with message 'There is no extension able to load the configuration for "my.remote_loader" (in /var/www/testclean/publishv2/app/config/services.yml). 

	Looked for namespace "my.remote_loader", found "framework", "security", "twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "jms_aop", "jms_di_extra", "jms_security_extra", "raul_fraile_ladybug", "doctrine_mongodb", "stof_doctrine_extensions", "jms_translation", "white_october_pagerfanta", "fos_js_routing", "fos_user", "nelmio_api_doc", "escape_wsse_authentication", "fos_rest", "jms_serializer", "plantnet_user", "plantnet_data", "plantnet_file_manager", "liip_imagine", "web_profiler", "sensio_distribution"' in /var/www/testclean/publishv2/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:290\nStack trace:\n#0 /var/www/testclean/plantn in /var/www/testclean/publishv2/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 104, referer: http://publish.testclean/app_dev.php/admin/module/collection/58298b988a2c17a10f8b4567/module/582c64b18a2c17c2654762a8/import_data


I think it come from : `class: AppBundle\Service\RemoteCacheResolver`

**Comment by AxelBriche** [comment]
Hello upgrade.md has:
[Configuration] `liip_imagine.formats` option was removed.
[Configuration] `liip_imagine.data_root` option was removed.

And I have this error:
The service "app.remote_loader" has a dependency on a non-existent parameter "liip_imagine.formats". Did you mean this: "liip_imagine.gd.class"?

**Comment by sewnboy** [comment]
Hello,

After trying several ways to get the job done, I succeeded with the following configuration.

I hope this can help :)

## LiipImagineBundle basic configuration

_**composer.json**_
```
"liip/imagine-bundle": "^1.9" 
```

**_routing.yml_**
```
# LiipImagineBundle 
_liip_imagine: 
    resource: "@LiipImagineBundle/Resources/config/routing.xml" 
```

## Remote image configuration

**_services.yml_**
```
services:
    app.imagine.cdn_data_loader:
        class: "%liip_imagine.binary.loader.stream.class%"
        arguments:
            - '' # if you store full path in the database
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'cdn_data_loader' }
```

**_config.yml_**
> **data_loader: cdn_data_loader** is the important part here
```
# LiipImagineBundle 
liip_imagine: 
    filter_sets: 
        header_logo: 
            data_loader: cdn_data_loader
            quality: 100 
            filters: 
                thumbnail: { size: [150, 90], mode: outbound } 
```

## Usage in a twig file

```
<img src="{{ INSERT YOUR URL HERE |imagine_filter('header_logo') }}" /> 

```
