### ISSUE TITLE
need https option for aws stream

### ISSUE THREAD

**Issue by PaddyLock** [liip/LiipImagineBundle#335]
Hi, I need to be able to produce paths to https where needed for paths generated to AWS S3

At the moment I can only pull images from s3 over http.

My config is like so:

```
knp_gaufrette:
    adapters:
        amazon:
            amazon_s3:
                amazon_s3_id: amazonS3
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        amazonS3:
            adapter: amazon

    stream_wrapper: ~

liip_imagine:
    cache: 'amazon_s3'
    filter_sets:
        product:
            data_loader: stream.amazon
            quality: 60
            filters:
                thumbnail: { size: [194, 194], mode: inset }
```

The path produced for my image is like this:

http://helios-production.s3.amazonaws.com/product/uploads/images/products/bluebell-2.jpg

The issue is, I have no control over the http or https part. I would like to either produce a path with the correct scheme depending on if it's a secure page or not or like this:

//helios-production.s3.amazonaws.com/product/uploads/images/products/bluebell-2.jpg

ideally both.

Thanks
