### ISSUE TITLE
Problem with runtime config

### ISSUE THREAD

**Issue by Ziiweb** [liip/LiipImagineBundle#351]
Hi,

I have these lines in my template:

```
      {% set runtimeConfig = {"thumbnail": {"size": [ 100, 100 ] }} %}
      <img class="producto" src="{{ ('/images/' ~ producto.imageName) | imagine_filter('jander', runtimeConfig) }} ">
```

and those in config.yml

```
liip_imagine:
    filter_sets:
        jander:
            filters:
                thumbnail: { size: [ 20, 20 ] }
```

but I can not get the the resultant image 100x100. I always get the 20x20.

Any help?

Symfony 2.3.11
