### ISSUE TITLE
Trying to use the runtime configuration

### ISSUE THREAD

**Issue by Ziiweb** [liip/LiipImagineBundle#356]
I have this code:

```
       {% set runtimeConfig = {"relative_resize": {"widen": 100} } %}
      <img class="producto" src="{{ ('/images/' ~ producto.imageName) | imagine_filter('my_thumb3', runtimeConfig ) }} ">
```

and this:

```
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        my_thumb3:
            quality: 30 
            filters:
                relative_resize: { widen: 50 }
```

and I get this error:

```
404 Not found
http://mareva/media/cache/my_thumb3/JlXqIdlT/images/532728ade52f8.jpg
```

I have checked inside my_thumb3 and the directory JlXqIdlT/ is not created.

I can find the image at `my_thumb3/JlXqIdlT/images/532728ade52f8.jpg` but it does not have width 100 but 50.
