### ISSUE TITLE
The given context is no valid resource

### ISSUE THREAD

**Issue by PaddyLock** [liip/LiipImagineBundle#357]
I have just updated to use AWS PHP SDK 2. Now when I try and load an image the cache file is not created on the server

The file is on the server and the image path is changed from

```
http://s3-eu-west-1.amazonaws.com/bucket_name/uploads/images/products/imagename.png

to    
http://mydomain.co.uk/media/cache/product/uploads/images/products/imagename.png
```

But I get the following error for the image

```
liip/imagine-bundle/Liip/ImagineBundle/Imagine/Data/Loader/StreamLoader.php at line 34

The given context is no valid resource.
```

I have the following services.yml

```
services:
amazonS3:
    class: Aws\S3\S3Client
    factory_class: Aws\S3\S3Client
    factory_method:  factory
    arguments:
        -
            key: %aws_key%
            secret: %aws_secret%
            region: %aws_s3_region%
            ssl.certificate_authority: %aws_cert%
            # more S3 specific options, see \AmazonS3::__construct()

liip_imagine.data.loader.stream.profile:
    class: "%liip_imagine.data.loader.stream.class%"
    arguments:
        - "@liip_imagine"
        - 'gaufrette://amazonS3/'
    tags:
        - { name: 'liip_imagine.data.loader', loader: 'stream.amazon' }

helios.imagine.cache.resolver.amazon_s3:
    class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
    arguments:
        - "@amazonS3"
        - "%s3_bucket%"
    calls:
         # This calls $service->setObjectUrlOption('https', true);
         - [ setObjectUrlOption, [ 'https', false ] ]
    tags:
        - { name: 'liip_imagine.cache.resolver', resolver: 'amazon_s3' }
```

And the following config

```
knp_gaufrette:
    adapters:
        amazon:
            aws_s3:
                service_id: amazonS3
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        amazonS3:
            adapter: amazon

    stream_wrapper: ~

liip_imagine:
    cache: 'amazon_s3'
    filter_sets:
        product:
            data_loader: stream.amazon
            quality: 60
            filters:
                thumbnail: { size: [194, 194], mode: inset }
```
