### ISSUE TITLE
The `cache` option does not work at filter_sets level

### ISSUE THREAD

**Issue by sixty-nine** [liip/LiipImagineBundle#36]
In the configuration file, the following will work:

``` yaml
liip_imagine:
    cache: my_custom_cache
```

But this does not work:

``` yaml
liip_imagine:
    filter_sets:
        my_special_style:
            cache: my_custom_cache
            filters:
                my_custom_filter: { }
```

It will cause the following exception:

```
InvalidConfigurationException: Unrecognized options "cache" under "liip_imagine.filter_sets.liip_rasterize"
```
