### ISSUE TITLE
Images don't appear in dev environment

### ISSUE THREAD

**Issue by ansnap** [liip/LiipImagineBundle#361]
I've updated the bundle to the last commit. Before, it worked perfectly. Now, I changed config to:

```
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

and:

```
web_profiler:
    intercept_redirects: false
```

And I have urls to images like:
`http://localhost/media/cache/profile/uploads/images/profile/1/img.jpg`

But they should be:
`http://localhost/subfolder/web/media/cache/profile/uploads/images/profile/1/img.jpg`

I.e. `/subfolder/web/` is missed. How can I fix it?
