### ISSUE TITLE
Image not generated

### ISSUE THREAD

**Issue by Neokortex** [liip/LiipImagineBundle#391]
My config.yml

``` yml
liip_imagine:
    filter_sets:
        my_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

``` twig
<img src="{{ '/upload/images/47066.jpeg' | imagine_filter('my_thumb') }}"/> {# NOT WORKING #}
<img src="{{ asset('/upload/images/47066.jpeg'|imagine_filter('my_thumb')) }}"> {# NOT WORKING #}
<img src="{{ asset('/upload/images/47066.jpeg') }}"/> {# working fine #}
```

But if i use liipImagineBundle in cotroller, **image generated:**

``` php
$imagemanagerResponse = $container->get('liip_imagine.controller');
$imagemanagerResponse->filterAction($this->getRequest(), '/upload/images/47066.jpeg', 'my_thumb');
```

why bundle not working with twig?
