### ISSUE TITLE
last update show me array_key_exists() expects parameter 2 to be array, null given invendor/liip/imagine-bundle/Liip/ImagineBundle/DependencyInjection/Configuration.php line 80

### ISSUE THREAD

**Issue by sdecandelario** [liip/LiipImagineBundle#394]
When i updated to the last version i don'¡t know why the bundle show me this error in console

1/1ContextErrorException: Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/vab/vendor/liip/imagine-bundle/Liip/ImagineBundle/DependencyInjection/Configuration.php line 80

And i don't change anything in the config

``` yaml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %cs_image_path%
    resolvers: ~
    filter_sets:
        momentos_thumbnails_lightbox:
            data_loader: default
            filters:
                thumbnail: { size: [718, 718], mode: outbound }
        momentos_private_thumbnails_list:
            data_loader: default
            filters:
                thumbnail: { size: [390, 390], mode: outbound }
        momentos_public_thumbnails_list:
            data_loader: default
            filters:
                thumbnail: { size: [311, 311], mode: outbound }
        momentos_public_thumbnails_detail:
            data_loader: default
            filters:
                thumbnail: { size: [641, 641], mode: outbound }
        momentos_public_thumbnails_category:
            data_loader: default
            filters:
                thumbnail: { size: [67, 67], mode: outbound }
```

Any idea? thanks!
