### ISSUE TITLE
Watermark filter should be executed last in all cases

### ISSUE THREAD

**Issue by ama3ing** [liip/LiipImagineBundle#404]
With following configuration

```
thumb:
        quality: 100
        filters:
            watermark:
                   position: topright
                   image: Resources/images/watermark.png
            thumbnail: { size: [1024, 768], mode: outbound }
            upscale: { min: [1024, 768] }
            crop: { start: [0, 0], size: [1024, 768] }

```

Watermark will be cropped, so I think this behavior is weird.
