### ISSUE TITLE
no image created in cache (no problem on local)

### ISSUE THREAD

**Issue by eexbee** [liip/LiipImagineBundle#408]
Hi

everything is working properly on localhost. I uploaded my website on a shared host and now LiipImagineBundle does not create thumbnails for new pictures I upload (previous pics that I use to uploaded locally and have thumbnail are working. So the address I am providing Is OK)
(cache folder permission is 755)

this is my config

``` yml
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        gallery_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [73, 73], mode: outbound }
```

what am I doing wrong?
tnx
