### ISSUE TITLE
About runtime configuration

### ISSUE THREAD

**Issue by Ziiweb** [liip/LiipImagineBundle#412]
Hi,

after following the docs, I have this lines:

```
        {% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
          <img src="{{ 'images/532bf9be7ab77.jpg' | imagine_filter('thumbnail_web_path', runtimeConfig) }}">
```

And this:

```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        thumbnail:
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

but Im getting this error when loading the page:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_imagine_thumbnail_web_path" as such route does not exist.")
