### ISSUE TITLE
'cache_prefix' parameter does not work

### ISSUE THREAD

**Issue by naydav** [liip/LiipImagineBundle#424]
Config example:

```
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: content/cache # it is not default value
```

But \Liip\ImagineBundle\Routing\ImagineLoader stiil obtains 'media/cache' value.
https://github.com/liip/LiipImagineBundle/blob/master/Routing/ImagineLoader.php#L36

Look like as this parameter is hardcoded in
https://github.com/liip/LiipImagineBundle/blob/master/DependencyInjection/LiipImagineExtension.php#L59
https://github.com/liip/LiipImagineBundle/blob/master/Resources/config/imagine.xml#L110

Thanks
