### ISSUE TITLE
InvalidConfigurationException: Unrecognized options "filesystem" under "liip_imagine.loaders.default"

### ISSUE THREAD

**Issue by nmathon** [liip/LiipImagineBundle#434]
I have an invalidConfigurationException on data_root configuration but I used the same configuration than in  the documentation :

```
liip_imagine:
    cache: default
    resolvers:
       default:
            web_path: 
                web_root: "%kernel.root_dir%../www"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%../www/"
```

I can't see what is wronh
