### ISSUE TITLE
Crop filter renders black image

### ISSUE THREAD

**Issue by AurL-Anto** [liip/LiipImagineBundle#442]
Hi,

I've been trying to crop an image using this code

```
filter_sets:
    cache: ~
    profile_pic:
        filters:
            crop: { start: [0, 20], size: [90, 120] }
```

It renders the right dimensions, but the image is just plain black... It works well with all the other filters I tried, but not this one
