### ISSUE TITLE
Resized image is big than original image

### ISSUE THREAD

**Issue by Lutacon** [liip/LiipImagineBundle#443]
Hi there,

I'm applying this filter:

```
 works_view:
     quality: 100
     filters:
         relative_resize: { heighten: 800 , widen: 1200  }
```

Original image: 292KB, width:843  height: 1200
Resized image: 395KB, width: 562 height: 800

How is that possible ?

**Comment by Hoannv** [comment]
I have same problem here. Resized image is so big

```
teaser:
            quality: 100
            filters:
                relative_resize: { widen: 600 }
```
Original image: 213KB, width: 600 height: 720
Resized image: 1.9 MB, width: 600 height: 720
