### ISSUE TITLE
Symfony, Liip Imagine bundle not working on server in prod environment

### ISSUE THREAD

**Issue by EnoahNetzach** [liip/LiipImagineBundle#450]
I have a project where I keep my uploaded images in _src/My/Bundle/Resources/uploads/images/full_ and use the twig filter `imagine_filter` to dynamically create thumbnails.

On my local machine it works flawlessly and so does on my server, but there only under the dev environment. When I delete the previously created thumbnails (leaving only the _full_ directory), clear the prod cache and load any web page, the images are not created, their url always remains under _media/cache_, and the logger gives me the `request.ERROR`:

```
"No route found for "GET /uploads/images/avatar/354026c94b773b77ca945b4a6323e15c84102f6b.jpg"" at /<path>/app/cache/prod/classes.php line 1964 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /uploads/images/avatar/354026c94b773b77ca945b4a6323e15c84102f6b.jpg\" at /<path>/app/cache/prod/classes.php:1964, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at /<path>/app/cache/prod/appProdUrlMatcher.php:1816
```

Some additional infos:
- I have symlinked _src/My/Bundle/Resources/uploads_ to _web/uploads_
- my config is (`thumbnail_min` is a custom filter):
  
  ```
  liip_imagine:
      loaders:
          default:
              filesystem:
                  data_root: %kernel.root_dir%/../web%images_full.dir%
      resolvers:
          default:
              web_path: 
                  web_root: %kernel.root_dir%/../web
                  cache_prefix: %images.dir%
      cache: default
      filter_sets:
          avatar:
              quality: 90
              filters:
                  thumbnail_min: { size: 50, mode: inset }
          xsmall:
              quality: 90
              filters:
                  thumbnail_min: { size: 125, mode: inset }
          small:
              quality: 90
              filters:
                  thumbnail_min: { size: 250, mode: inset }
          medium:
              quality: 90
              filters:
                  thumbnail_min: { size: 500, mode: inset }
          large:
              quality: 90
              filters:
                  thumbnail_min: { size: 800, mode: inset }
          full:
              quality: 100
  ```
- permissions are always at least group rw (that's what is needed on the server)
