### ISSUE TITLE
PNG heavier than source

### ISSUE THREAD

**Issue by NV-iloweb** [liip/LiipImagineBundle#456]
I used the same picture, saved as a PNG (1.5Mb) and as a JPG (1Mb) and used this filter 
```
slideshow_front:
            quality: 100
            filters:
                relative_resize: { widen: 1170 }
```
As a result, my png cached picture was 2.9Mb and my jpg was 430Kb.
I tried with various pictures and if I use a PNG file I always end up with a cached file heavier than the source.

Am I missing something or is there really something wrong ?
