### ISSUE TITLE
cache_prefix override and 'resolve' path

### ISSUE THREAD

**Issue by ogizanagi** [liip/LiipImagineBundle#470]
Changing the cache path for another path than under `media/cache` produces an issue. (Ex: `public/cache`)
Indeed, if the image isn't already in cache, the url is `http://acme.com/media/cache/resolve/app_icon/public/uploads/icon.png` instead of `http://acme.com/public/cache/resolve/app_icon/public/uploads/icon.png`.

If the `console liip:imagine:cache:resolve` command is used to generate the image, then the path is correct, without the `resolve` part: `http://acme.com/public/cache/app_icon/public/uploads/icon.png`.

This only happens when trying to generate the image cache for the first time, and might be induced by this fix: #467 about the Too many http redirects Safari #429.

Of course, I can create the `media/cache` folder and give permissions on it, but then, what would be the utility of the `cache_prefix` parameter ?

Here is my configuration:

``` yaml
liip_imagine:
    driver: gd
    cache: default

    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: public/cache

    filter_sets:
        cache: ~
        app_icon:
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
```
