### ISSUE TITLE
Cannot get PdfTransformer working

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#475]
I'm using v0.21.1 and I'd like to generate thumbnails for pdf files. Documentation is not helping so much, showing an example about a custom transformer, but omitting this simple use case.
Here is a relevant part of my services.xml:

``` xml
<service id="imagick_object" class="Imagick"/>
<service id="acme.imagine_pdf_transformer" class="Liip\ImagineBundle\Imagine\Data\Transformer\PdfTransformer">
    <argument type="service" id="imagick_object"/>
</service>
<service id="acme.imagine_data_loader.extended_filesystem" class="Liip\ImagineBundle\Imagine\Data\Loader\ExtendedFileSystemLoader">
    <tag name="liip_imagine.binary.loader" loader="extended_filesystem" />
    <argument type="service" id="liip_imagine" />
    <argument>%liip_imagine.formats%</argument>
    <argument>%liip_imagine.data_root%</argument>
    <argument type="collection">
        <argument type="service" id="acme.imagine_pdf_transformer"/>
    </argument>
</service>
```

Here is a relevant part of my config.yml:

``` yaml
liip_imagine:
    driver:               imagick
    cache_mkdir_mode:     0750
    filter_sets:
        pdf362x362:
            data_loader: extended_filesystem
            filters:
                thumbnail: { size: [362, 362], mode: outbound }
```

Unfortunately, when I try to recall `imagine_filter('pdf362x362')` from a template, applied to a pdf url, it's just not working. I'm getting an url pointing to `/app_dev.php/media/cache/pdf362x362/uploads/1284553847foo.pdf`, instead of an image url. Anyway, that url does not exist on filesystem
I tried to debug and it looks like ExtendedFileSystemLoader class is never called, so maybe I did some mistakes in configuration? Is it possible to get an example in documentations?
Thanks in advance
