### ISSUE TITLE
New subdirectory "resolve" in cache directory - How to remove ?

### ISSUE THREAD

**Issue by stijink** [liip/LiipImagineBundle#493]
Hi :)

After a recent vendor update, the cache directrory changed from "media/cache/" to "media/cache/resolve". Even if the configuration explicitly points to "media/cache/".

```
resolvers:
    default:
        web_path:
          web_root: %kernel.root_dir%/../web
          cache_prefix: media/cache
```

Is this a change introduced by the bundle or maybe a bug in my code ? If the first one, whats the reason, and how can i avoid this folder in the path generated ? :)

Thanks,
Stephan
