### ISSUE TITLE
Create thumbnail and cache for usage on the site until image change

### ISSUE THREAD

**Issue by reypm** [liip/LiipImagineBundle#502]
I've a image upload handled through AJAX, basically I get the `src` attribute from a image which is a `data:image/png;base64` and then in controller I create the image on the FS. I need to create a thumb, in cache if is possible, for that image, how I can do that? I read the docs but is not clear for me. Any help?
# Some extra information

I've this in my `parameters.yml` file:

```
upload_dir: %kernel.root_dir%/../web/uploads/products
thumbs_dir: %kernel.root_dir%/../web/uploads/products/thumbs
```

And this at `config.yml`:

``` yaml
    liip_imagine:
        resolvers:
            default:
                web_path:
                    web_root: %kernel.root_dir%/../web
                    cache_prefix: /cache

        filter_sets:
            cache: ~
            tanane_thumb:
                quality:              75
                filters:
                    thumbnail: { size: [40, 40], mode: outbound }
```

if I want images to be created under `/web/uploads/products/cache`, is that configuration right?

Thanks in advance
