### ISSUE TITLE
Add support for asset version

### ISSUE THREAD

**Issue by hason** [liip/LiipImagineBundle#507]
If I change the settings of filter set, I want to reload the browser cache (see http://symfony.com/doc/current/reference/configuration/framework.html#ref-framework-assets-version): 

The proposed configuration:
```yaml
liip_imagine:
  driver: imagick
  asset_version: 3 # global version for all filter sets
  filter_sets:
    admin_thumbnail:
      quality: 75
      asset_version: 5 # version for current filter set
      filters:
        thumbnail: { size: [120, 120], mode: inset }
```
