### ISSUE TITLE
Questions about the use with https

### ISSUE THREAD

**Issue by hugohenrique** [liip/LiipImagineBundle#512]
I'm in an application that runs on HTTPS compulsorily and I'm finding some problems. 
First of all wanted to expose my configurations and then report on what I'm facing.

```yaml
liip_imagine:
    driver: imagick
    cache: amazon_s3
    filter_sets:
        advertisement:
            data_loader: stream.advertisement
            cache: amazon_s3
            quality: 90
            filters:
                thumbnail: { size: [200, 200] }
        avatar:
            data_loader: stream.avatar
            quality: 85
            filters:
                thumbnail: { size: [160, 160], mode: outbound }
        avatar_thumbnail:
            data_loader: stream.avatar_thumbnail
            quality: 85
            filters:
                thumbnail: { size: [70, 70], mode: outbound }
```

My services.yml

```yaml
my_app.aws_s3.client:
    class: 'Aws\S3\S3Client'
    factory_class: 'Aws\S3\S3Client'
    factory_method: factory
    arguments:
        - { key: %amazon.key%, secret: %amazon.secret% }

my_app.imagine.cache.resolver.amazon_s3:
    class: 'Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver'
    arguments:
        - @my_app.aws_s3.client
        - %amazon.bucket%
        - 'public-read'
        - { Scheme: https }
    tags:
        - { name: 'liip_imagine.cache.resolver', resolver: 'amazon_s3' }

liip_imagine.data.loader.stream.avatar_thumbnail:
    class: %liip_imagine.binary.loader.stream.class%
    arguments:
        - 'gaufrette://avatar_fs/'
    tags:
        - { name: 'liip_imagine.binary.loader', loader: 'stream.avatar_thumbnail' }

liip_imagine.data.loader.stream.avatar:
    class: %liip_imagine.binary.loader.stream.class%
    arguments:
        - 'gaufrette://avatar_fs/'
    tags:
        - { name: 'liip_imagine.binary.loader', loader: 'stream.avatar' }

liip_imagine.data.loader.stream.advertisement:
    class: %liip_imagine.binary.loader.stream.class%
    arguments:
        - 'gaufrette://advertisement_fs/'
    tags:
        - { name: 'liip_imagine.binary.loader', loader: 'stream.advertisement' }
```
Going back to the problem:
When doing an upload realize the asset to generate the following path:
"http://domain.dev/media/cache/avatar/484140b453eee69e1588e63f398b745a.jpeg"

And then if I run a reload on page: 
"https://bucket.s3.amazonaws.com/avatar/484140b453eee69e1588e63f398b745a.jpeg"

And always remember that I need to always run https.
The browser sends me an alert for the cross domain issue. 
Anyone have any ideas?
