### ISSUE TITLE
Issues using KnpGaufretteBundle + LiipImagineBundle on S3

### ISSUE THREAD

**Issue by JulienRamel** [liip/LiipImagineBundle#522]
Hi,

Thanks for this bundle (from Lausanne, Swizerland).

I have an issue using the combo KnpGaufretteBundle + LiipImagineBundle for a full-S3-based system : I'm able to upload a file to S3 manually with an upload class using KnpGaufretteBundle, and I'm able to create a cache of my LOCAL photos on S3 using LiipImagineBundle. BUT I'm not able to generate the cache on S3 for my files which are on S3.

This is my configuration :

Liip Imagine
```
liip_imagine:
    driver: gd
    cache: cache_s3
    data_loader: photos_s3
    filter_sets:
        home:
            quality: 90
            filters:
                thumbnail: { size: [542, 396], mode: outbound, format: jpg }
        home2:
            quality: 80
            filters:
                thumbnail: { size: [283, 206], mode: outbound, format: jpg }
    resolvers:
        cache_s3:
            aws_s3:
                client_config:
                    key: "%amazon_aws_key%"
                    secret: "%amazon_aws_secret_key%"
                    region: "%amazon_aws_region%"
                bucket: "%amazon_s3_bucket_name%"
    loaders:
        photos_s3:
            stream:
                wrapper: gaufrette://photo_storage/
```

Gaufrette
```
knp_gaufrette:
    adapters:
        photo_storage:
            aws_s3:
                service_id: netinfluence_storage.amazon_s3
                bucket_name: moto.okaz
                options:
                    create: true
                    directory: "photos"
    filesystems:
        photo_storage:
            adapter: photo_storage
            alias: photo_storage_filesystem
```

Services
```
parameters:
    netinfluence_storage.amazon_s3.class: Aws\S3\S3Client
    netinfluence_storage.amazon_s3.factory_class: Aws\S3\S3Client
    netinfluence_storage.photo_uploader.class: Netinfluence\StorageBundle\Upload\PhotoUploader

services:
    netinfluence_storage.amazon_s3:
        class: "%netinfluence_storage.amazon_s3.class%"
        factory_class: "%netinfluence_storage.amazon_s3.factory_class%"
        factory_method: "factory"
        arguments:
            -
                key: "%netinfluence_storage.amazon_s3.aws_key%"
                secret: "%netinfluence_storage.amazon_s3.aws_secret_key%"
                region: "%netinfluence_storage.amazon_s3.aws_region%"

    netinfluence_storage.photo_uploader:
        class: "%netinfluence_storage.photo_uploader.class%"
        arguments:  
            service: "@photo_storage_filesystem"

    netinfluence_storage.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@netinfluence_storage.amazon_s3"
            - "%amazon_s3_bucket_name%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cache_s3" }
        calls:
            - [setCachePrefix, ["cache"]]
```

If I want to show a picture on S3, I'm trying something like this : 
```
<img src="{{ "Bg3sbds4i2W6PVLVyJm1/1.jpeg"|imagine_filter("home") }}" />
```

Assuming that I have this picture in my bucket : 
```
photos/Bg3sbds4i2W6PVLVyJm1/1.jpeg
```

I have an error message, the source image is not loadable. It tries to open this URL :
```
http://my-website.local/app_dev.php/fr/media/cache/resolve/home/Bg3sbds4i2W6PVLVyJm1/1.jpeg
```

The error message is :
```
NotLoadableException: Source image gaufrette://photo_storage/Bg3sbds4i2W6PVLVyJm1/1.jpeg not found.
```

And the cache file is not generated...

Thanks for your help :-\
