### ISSUE TITLE
Watermark filter dynamic path

### ISSUE THREAD

**Issue by SoulviES** [liip/LiipImagineBundle#537]
Hi, I was trying to apply a different watermark path depending of the user who uploaded a photo, i tried with a runtimeConfig but i don't know how to do correctly.

I do this:

```
{% set runtimeConfig = {"watermark": {"size": 0.5, "image": premium.watermark, "position": 'bottomright' }} %}
                    <img  src="{{asset(photo.path | imagine_filter('grid_thumb', runtimeConfig))}}" >
```

In the config.yml i have this:

```
        grid_thumb:
            quality: 50
            filters:
                thumbnail: { size: [244, 244], mode: outbound }
```

This is the error in the profiler:

Signed url does not pass the sign check for path "PHOTO-ROUTE" and filter "grid_thumb" and runtime config {"watermark":{"size":"0.5","image":"WATERMARK-ROUTE","position":"bottomright"}}

**Comment by trsteel88** [comment]
@Ipshal, I believe you will need a base configuration for watermark in your config to do this.

e.g you need:

```yaml
        grid_thumb:
            quality: 50
            filters:
                thumbnail: { size: [244, 244], mode: outbound }
                watermark:
                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
                    image: Resources/data/watermark.png
                    size: 0.5
                    position: center
```

Once you have the base configuration, you can then override the options. Also, where you position the filter will determine when it will be applied (e.g, if you want the watermark applied to the image before the thumbnail filter is run, you need to move it above the thumbnail filter).
