### ISSUE TITLE
Trying to change the path where the images are saved after applying the filter

### ISSUE THREAD

**Issue by Ziiweb** [liip/LiipImagineBundle#542]
I have this this config: 
```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        subitem_in_category: 
            path: ~  ///how to change the default path where the images are saved?
            filters:
                my_custom_filter: { }
                relative_resize: { heighten: 210 }
```
Im trying to change the name of the directory wheren the images are saved, but I get 

`InvalidConfigurationException: Unrecognized options "path" under "liip_imagine.filter_sets.subitem_in_category"`

I have read this: https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/configuration.md

**Comment by makasim** [comment]
this is responsibility of resolver hence you have to configure it not the filters:

```
resolvers:
        default:
            web_path:
              web_root: ~ # %kernel.root_dir%/../web
              cache_prefix: ~ # media/cache
```

also I think that `path` option is not used any more and has to be removed from the docs.
