### ISSUE TITLE
Default image generated in its original size only

### ISSUE THREAD

**Issue by mgcode** [liip/LiipImagineBundle#563]
While using the getBrowserPath method:
```php
$this->imagineResolver->getBrowserPath($imagePath, 'user_avatar_tiny');
````
if my image does not exist, i get default image, but in its original size, not resized to 'user_avatar_tiny' dimmensions.

Am I doing it wrong, should I add some additional configuration?

My configuration:
````yml
liip_imagine:
    resolvers:
        default:
            web_path:
              web_root: %kernel.root_dir%/../web
              cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../files
                
    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        /bundles/tdcore/images/defaszyzując
        
    filter_sets:
        user_avatar_tiny:
            filters:
                thumbnail: { size: [40, 40], mode: inbond, cache_type: public}
````
