### ISSUE TITLE
How do I redirect to CloudFront url, not the S3 url?

### ISSUE THREAD

**Issue by websirnik** [liip/LiipImagineBundle#568]
I'm using AWS S3 cache resolver. http://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolver/aws_s3.html

It works well, after requesting a thumbnail, I'm getting redirected to the direct S3 thumbnail url.

Now I need to add CloudFront into equation. I need Imagine to generate a thumbnail on the S3, but return the CloudFront Url for the thumbnail, not the S3 url. How do I achive that?

**Comment by makasim** [comment]
use proxy decorator resolver.

**Comment by websirnik** [comment]
Specifying proxies like this solved it:
```yml
liip_imagine:
    resolvers:
       profile_photos:
          aws_s3:
              ...
              proxies: ['http://yourID.cloudfront.net']
```

Here it mentions `cache` setting: http://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolver/aws_s3.html#additional-options
... but it throws an error for me `The service "liip_imagine.cache.resolver.profile_photos" has a dependency on a non-existent service "1".'` Without `cache:true` woks fine. What is the role of `cache:true` there?

**Comment by makasim** [comment]
>  What is the role of cache:true there?

it addes another decorator which cache the api calls to amazon. like does amazon has image, what is the  url of it and so on.

**Comment by appeltaert** [comment]
@websirnik how did you deal with the bucket name thats appended to the cloudfront url?

My S3 url thats returned by the S3Client:
//s3.eu-central-1.amazonaws.com/<bucket>/<path>

The proxy just changes the hostname, which results in:
//<id>.cloudfront.net/<bucket>/<path>, but it the bucket part shouldnt be there when using cloudfront.

Did you manage to get the bucket name part of the hostname when working with the client? (<bucket>.s3.eu-central-1.amazonaws.com) This would solve it but i cant figure it out..

**Comment by makasim** [comment]
@appeltaert your case is not supported right now, There must be amazon specific wrapper for resolver or event listener.

**Comment by appeltaert** [comment]
Ok, shouldnt be a problem. But @websirnik just said he got it to work?

**Comment by dincho** [comment]
> Ok, shouldnt be a problem. But @websirnik said he got it to work?

It was working with SDK v2, after v3 the SDK operate with path-style bucker URLs see https://github.com/aws/aws-sdk-php/issues/692.

You can write custom resolver as @makasim wrote.

**Comment by desmax** [comment]
> but it throws an error for me The service "liip_imagine.cache.resolver.profile_photos" has a dependency on a non-existent service "1".' Without cache:true woks fine. What is the role of cache:true there?
same for me, how to resolve this?

**Comment by polantis** [comment]
Hello, is it going to be supported soon or we still need to write a custom resolver?

Thanks

**Comment by yamilovs** [comment]
@polantis 
You can make a workaround, like this:
```
liip_imagine.cache.resolver.amazon_s3.cache.proxy:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver
        arguments:
            - "@liip_imagine.cache.resolver.amazon_s3"
            - [ "https:/" ]
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "proxied_cached_amazon_s3" }
```

It will replace [schema]://[amazon_url]/[bucket_name] with [https:/]/[bucket_name]
