### ISSUE TITLE
When and why "resolve" is added to the path?

### ISSUE THREAD

**Issue by Ziiweb** [liip/LiipImagineBundle#573]
Hi,

Im experiencing that sometimes "resolve" is added to the path like here below. In that case the image is not generated.

`http://procom/app.php/media/cache/resolve/subitem_in_category_alto/images/0a7705837dad5b40e168f0e0fe0e2db746486e7b`

This is another one: `http://procom/app_dev.php/media/cache/resolve/subitem_in_category_alto/media/cache/clipped_images/6d5a3645f74ee1c1b2dc9ab1eb7495dc7cd8de64`

Well, I don't know If it is related to my problem, but if look at the last one, you will guess that Im applying two filters to an image separately, I mean firstly one and then another one. The first one is a custom filter to clip and image that I apply inside a onFlush() event, and the second one is just to adjust the size of the clipped image resultant from the first filter. Could be any problem becuase of that??

This is my configuration:
```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        clipped_images:
            filters:
                my_custom_filter: { }

        subitem_in_category_ancho: 
            filters:
              relative_resize: { widen: %fixed_width_of_subitem_image_in_list% }

        subitem_in_category_alto: 
            filters:
              relative_resize: { heighten: %maximum_height_of_subitem_image_in_list }
```
This is the code in twig:  `src="{{ ('/media/cache/clipped_images/' ~ subitemColor.fileName) | imagine_filter('subitem_in_category_alto') }}"`

![screenshot from 2015-03-20 04 10 12](https://cloud.githubusercontent.com/assets/179063/6745452/5210ae6e-ceb7-11e4-9994-6f5f59613f91.png)

The numbers in textarea input are the white dots of the red line.

Do you understand me? Any help or advice to handle/improve all this will be welcome..
