### ISSUE TITLE
Trim filter

### ISSUE THREAD

**Issue by igormukhingmailcom** [liip/LiipImagineBundle#586]
Hi.

Will be nice if trim filter will be implemented to remove white (or whatever) edges.
http://php.net/manual/en/imagick.trimimage.php

**Comment by makasim** [comment]
I think it is better to open this issue https://github.com/avalanche123/Imagine here first.

**Comment by igormukhingmailcom** [comment]
You're right, @makasim

**Comment by igormukhingmailcom** [comment]
@makasim WDYT? 
I can make PR if you're interested to have that available from the box.
Now all decorated for using as extension in some AppBundle.

```yml
# app/config.yml
parameters:
    liip_imagine.trim.fuzz: 20

liip_imagine:
    # Use imagick driver for built-in (and faster) trim
    # driver: imagick
    filter_sets:
        hires:
            ...
            filters:
                trim:
                  fuzz: %liip_imagine.trim.fuzz%
```

```yml
# services.yml
services:
    liip_imagine.filter.loader.trim:
        class: AppBundle\Imagine\Filter\Loader\TrimFilterLoader
        tags :
            - { name: liip_imagine.filter.loader, loader: trim }
```

```php
<?php

namespace AppBundle\Imagine\Filter\Loader;

use Liip\ImagineBundle\Imagine\Filter\Loader\LoaderInterface;
use Imagine\Image\ImageInterface;

use AppBundle\Imagine\Filter\Basic\Trim;

/**
 * @author Igor Mukhin <igor.mukhin@gmail.com>
 */
class TrimFilterLoader implements LoaderInterface
{
    private $palette = null;

    /**
     * {@inheritDoc}
     */
    public function load(ImageInterface $image, array $options = array())
    {
        if (!empty($options['fuzz'])) {
            $fuzz = $options['fuzz'];
        }

        $filter = new Trim($fuzz);
        return $filter->apply($image);
    }
}
```

```php
<?php

namespace AppBundle\Imagine\Filter\Basic;

use Imagine\Filter\FilterInterface;
use Imagine\Image\ImageInterface;
use Imagine\Image\Palette\Color\ColorInterface;
use Imagine\Image\Box;
use Imagine\Image\Point;

use Imagine\Imagick\Image as ImagickImage;

/**
 * A trim filter
 *
 * @see http://zavaboy.com/2007/10/06/trim_an_image_using_php_and_gd
 * @author Igor Mukhin <igor.mukhin@gmail.com>
 */
class Trim implements FilterInterface
{
    private $fuzz;

    /**
     * @param integer $fuzz How much tolerance is acceptable to consider two colors as the same
     */
    public function __construct($fuzz = 0)
    {
        $this->fuzz = $fuzz;
    }

    /**
     * {@inheritdoc}
     */
    public function apply(ImageInterface $image)
    {
        if ($image instanceof ImagickImage) {
            $imagick = $image->getImagick();
            $imagick->trimImage($this->fuzz);

            return $image;
        }

        $size = $image->getSize();
        $origWidth = $size->getWidth();
        $origHeight = $size->getHeight();

        $xMin = $origWidth;
        $xMax = 0;

        // Scanning for the edges
        for ($iy = 0; $iy < $origHeight; $iy++) {
            $first = true;
            for ($ix = 0; $ix < $origWidth; $ix++) {
                $checkColor = $image->getColorAt(new Point($ix, $iy));

                // Take color of top-left corner as background
                if ($iy == 0 && $ix == 0) {
                    $background = $checkColor;
                }

                if (!$this->isSimilar($background, $checkColor)) {
                    if ($xMin > $ix) {
                        $xMin = $ix;
                    }

                    if ($xMax < $ix) {
                        $xMax = $ix;
                    }

                    if (!isset($yMin)) {
                        $yMin = $iy;
                    }

                    $yMax = $iy;

                    if ($first) {
                        $ix = $xMax;
                        $first = false;
                    }
                }
            }
        }

        if (!isset($yMin)) {
            $yMin = 1;
        }

        if (!isset($yMax)) {
            $yMax = $origHeight;
        }

        // The new width and height of the image. (not including padding)
        $croppedWidth = 1+$xMax-$xMin;
        $croppedHeight = 1+$yMax-$yMin;

        $start = new Point($xMin, $yMin);
        $size = new Box($croppedWidth, $croppedHeight);

        return $image->crop($start, $size);
    }

    /**
     * @param  ColorInterface $color1
     * @param  ColorInterface $color2
     * @return boolean
     */
    private function isSimilar(ColorInterface $color1, ColorInterface $color2) {

        $components = array(
            ColorInterface::COLOR_RED,
            ColorInterface::COLOR_GREEN,
            ColorInterface::COLOR_BLUE
        );

        foreach ($components as $component) {
            if (abs($color1->getValue($component) - $color2->getValue($component)) > $this->fuzz) return false;
        }

        return true;
    }
}
```
