### ISSUE TITLE
404 error when try to use filter

### ISSUE THREAD

**Issue by NovikovViktor** [liip/LiipImagineBundle#591]
Hello, I configure bundle as described in docs, but when I try to set filter for my image, I getting path like this:
```
http://localhost/my_project/web/app_dev.php/media/cache/resolve/poster_thumb/my_project/web/uploads/posters/default_photo.jpg 
```
Its my problem? Or your documentation is deprecated?

My config:
```yml
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        poster_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
```

Usage:

```twig
<img src="{{ asset('uploads/posters/'~show.path)|imagine_filter('poster_thumb') }}">
```
