### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by hotgeart** [liip/LiipImagineBundle#594]
Hi,

I was on symfony 2.4.x and today I updated all of my project for symfony 2.6. Everything work except LiipImagineBundle.

I'll explain what I do.

I had this error when I get a page: 

FileLoaderImportCircularReferenceException in FileLoader.php line 97:
Circular reference detected in "C:\wamp\www\XXXXXXX\app/config/routing_dev.yml" ("C:\wamp\www\XXXXXXX\app/config/routing_dev.yml" > "C:\wamp\www\XXXXXXX\app/config\routing.yml" > "C:\wamp\www\XXXXXXX\app/config/routing_dev.yml").

And in my console : 
![console](http://image.noelshack.com/fichiers/2015/16/1429190918-capture1.jpg)

So I search who want to load "." and it's LiipImagineBundle.

In my routing.yml: 
```
# Imagine
_imagine:
    resource: .
    type:     imagine
```

So I go to the doc and you change the load. So I edit my routing.yml: 

```
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```

With this change I can access to my website. But I've a problem. The old images cached work, but I tried to upload a new image and that's not working. 

![resolve](http://image.noelshack.com/fichiers/2015/16/1429191421-capture2.jpg)

- The first is the new upload who return a 404 and a strange URL.
- The second is a old upload before the update

I did my best (i've a terrible english) to explain the problem. How can I fix this issue ?

Thanks

**Comment by makasim** [comment]
Did you have an 0.x version of LiipImagineBundel and upgraded it up to 1.0 version. If so please read the UPGRADE.md file https://github.com/liip/LiipImagineBundle/blob/master/UPGRADE.md

**Comment by hotgeart** [comment]
I'm with the `dev-master`.

I change my routing.yml : 

```
# Imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```

And I've no idea what I need to change in my config.yml 
```
# LiipImagine
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: cache
    filter_sets:
        avatar:
            quality: 75
            filters:
                resize_crop_filter: { size: 45 }
                crop: { start: [0, 0], size: [45, 45] }
                strip: ~
        thumb:
            quality: 75
            filters:
                resize_crop_filter: { size: 268 }
                crop: { start: [0, 0], size: [268, 268] }
                strip: ~
```
