### ISSUE TITLE
An image could not be created from the given input

### ISSUE THREAD

**Issue by iiNku** [liip/LiipImagineBundle#595]
I have this error when I want to display a png or jpeg image. jpg files work fine. Is this something that I missed ? 
Here is my config.yml

```
# LiipImagineBundle
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        avatar:
            quality: 75
            filters:
                thumbnail: { size: [270, 270], mode: outbound }
        avatar_thumb:
            quality: 75
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        avatar_thumb_admin:
            quality: 75
            filters:
                thumbnail: { size: [45, 45], mode: outbound }
        recipe_thumb:
            quality: 75
            filters:
                thumbnail: { size: [270, 200], mode: outbound }
        recipe:
            quality: 75
            filters:
                thumbnail: { size: [570, 420], mode: outbound }
```
