### ISSUE TITLE
Generated image size way bigger than original

### ISSUE THREAD

**Issue by picks44** [liip/LiipImagineBundle#637]
I have a filter that does
``` 
thumb_1140x400:
            jpeg_quality: 75
            png_compression_level: 7
            filters:
                thumbnail: { size: [1140, 400], mode: outbound }
                upscale: { min: [1140, 400] }
                crop: { start: [0, 0], size: [1140, 400] }
                strip: ~
```
If I upload a 1140x400 PNG, (same dimensions as the generated image), the size of the generated image (521kb) is bigger than the original one (459kb).
I even tried with the biggest compression rate for PNG (ie 9), and the result is still bigger (529kb).

How comes ?
