### ISSUE TITLE
pb with setting custom hostname 

### ISSUE THREAD

**Issue by rccc** [liip/LiipImagineBundle#641]
Hello,

Here is my version of liip_imagine : 

```
        "symfony/symfony": "2.7.*",
        "liip/imagine-bundle": "^1.3",

```

I want to be able to set the hostname in generated path, so that i can use "*dev.project.net*" and "*prod.project.net*", all my images are in the "*prod.project.net*" server.

With the **Avalanche123/ImagineBundle**, i was able to do this : 
```
{{ project_url }}{{ image.path|aply_filter('y_filter') }}
```
But this is not possible with **liip_imagine** as the *imagine_filter* return the complete url with the hostname.

I found this advice to set host parameter in *config.yml* : https://github.com/liip/LiipImagineBundle/issues/258, but this don't work for me as this line : 

```
 resource: .
```
give me an error because of the dot.

So i created a custom loader so that i can debug and find a way to set the hostname : 

```
namespace ACME\Bundle\CoreBundle\Loader;

use Liip\ImagineBundle\Binary\Loader\LoaderInterface;
use Imagine\Image\ImagineInterface;

class EnvironmentAwareLoader implements LoaderInterface
{
    protected $imagine;
    protected $wrapperPrefix;
    protected $project_url;

    public function __construct(ImagineInterface $imagine, $project_url)
    {
        $this->imagine = $imagine;
        // $this->wrapperPrefix = $wrapperPrefix;
        $this->project_url = $project_url;
       die('loader construct');
    }

    public function find($path)
    {
       die('loader find');

        // The http:// becomes http:/ in the url path due to how routing urls are converted
        // so we need to replace it by http:// in order to load the remote file
        $path = preg_replace('@\:/(\w)@', '://$1', $path);
        return $this->imagine->load(file_get_contents($path));
    }
}
```

with the corresponding service : 

```
    acme.env_aware_loader:
        class: ACME\Bundle\CoreBundle\Loader\EnvironmentAwareLoader
        arguments: [@liip_imagine, %project_url%]
        tags:
            - { name: liip_imagine.binary.loader, loader: env_aware_loader }
```

i also tried *liip_imagine.data.loader* as tag name.

And i set the config as told in the doc : 

```
liip_imagine:

    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: /media/cache/

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          env_aware_loader
    default_image:        null
```

It seems the *data_loader* key is not working for me.

So i tried this in *config.yml*: 

```
        thumb_540_405:
            data_loader:  env_aware_loader
            filters:
                thumbnail: { size: [540, 405], mode: outbound }
```

But this is not working too.

I tried to debug directly in liip_imagine bundle and put a *var_dump* and *die* in this file  *Liip\ImagineBundle\Binary\Loader\FileSystemLoader * but i only got a nearly blank page with no dump inside

Cheers

**Comment by makasim** [comment]
try configure proxy resolver over your origin one http://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolver/proxy.html

**Comment by rccc** [comment]
Thanks for advice,

i tried add this service : 

```
    bvm.imagine.cache.resolver.proxy:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver
        arguments:
            - "@liip_imagine.cache.resolver.default"
            - [ 'http://prod.project.net' ]
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'proxy' }
```

But this have no effect on generated urls.

Cheers
