### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by AxelBriche** [liip/LiipImagineBundle#644]
Hello, during `cache:clear` or `composer.phar update`, I have this error:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized options "cache_mkdir_mode, cache_prefix" under "liip_imagine"
```

I use:
``` yml
liip_imagine:
    resolvers:
       default:
          web_path: ~
    cache_mkdir_mode: 0777
    cache_prefix: /cache/Images
    filter_sets:
        cache: ~
        my_custom_filter:
            quality: 50
            filters:
                crop: { start: [0, 45], size: [480, 270] }
                thumbnail: { size: [252, 142], mode: outbound }

```
A problem with the configuration inside the doc ? Thank you.
