### ISSUE TITLE
Conversion from JPG to PNG

### ISSUE THREAD

**Issue by tobias-r** [liip/LiipImagineBundle#660]
Hi there,

after 2 hours of research without finding a solution, I could really appreciate some help:

I want to convert a JPG-file with this bundle to a PNG file (applyMask with transparency).

The output of my file is Mime-Type and content PNG, however, the filename sticks to ".jpg".

I find this a little confusing, is there a way to change the filename to ".png" or at least to loose the ending?

```
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: media/cache
    filter_sets:
        cache: ~
        hexagon_large:
            quality: 75
            format: png
            filters:
                hexagon:
                    size: [201,175] #size of mask png
```
