### ISSUE TITLE
Crop without maintaining proportions

### ISSUE THREAD

**Issue by javiereguiluz** [liip/LiipImagineBundle#677]
I'm getting crazy trying to solve this issue. Could someone please give me a hint or tell me if this bundle ca do what I want to do?

1. I have a bunch of very different screenshots (some of them have a very long height).
2. I want to create thumbnails which are of the same height and width.
3. If I use `thumbnail: { size: [324, 238], mode: inset }`, the width is always `324`, but for long screenshots, the height is not limited.
4. I'd like to add a new filter after `thumbnail` to crop the images.
5. I don't know how to create this filter: "crop the image maintaining the same width (324px) but limiting its height at 238px. If the image is taller, just remove the bottom of the image. Don't rescale the image, just get rid of the part that doesn't fit vertically."

**Comment by jupediaz** [comment]
Hello javier:
I was using this bundle some days ago and found the same problem. It seems not working consistently.

I used this:
```
liip_imagine:
    (...)
    filter_sets:
        (...)
        home_packages:
            quality: 85
            filters:
                thumbnail: { size: [320, 240], mode: inset, allow_upscale: true }
                crop: { start: [0, 0], size: [320, 240] }
```

Trying to get an image of max 320 width x 240 height. To avoid distort on images, `thumbnail` supossedly limits the image to 320x240. It seems only respecting max width, as I get all images on max width of 320 but different heights.

To crop that extra height, I added `crop` filter. But instead cropped image above 240 height, I get a redimensioned image with max height, with a black background bar on the right side, filling the blank space to fill the 320 width specified on `crop` filter.

I will take a look at it on how those two filters are executed. I also tried with `downscale` filter.
