### ISSUE TITLE
How to add width and height attributes to img tag?

### ISSUE THREAD

**Issue by TangMonk** [liip/LiipImagineBundle#712]
I have following code for generate thumb:

```
<img src="{{ vich_uploader_asset(post, 'imageFile') | imagine_filter('thumb')}}">
```

my config.yml

```
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                relative_resize: { widen: 200 }
```
But I need to add width and height attributes to img tag, how to archive this
