### ISSUE TITLE
Cache image not generated if app_dev.php is not in url

### ISSUE THREAD

**Issue by florianajir** [liip/LiipImagineBundle#716]
Your bundle works fine in dev env but not in prod.. 

The first time the image is load , if the url doesnt contains app_dev.php, the cache is not generated and url show original image. 
Do you know how to debug ?
my conf : 

```
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        checkout_thumb:
            default_image: /images/placeholder_100x100.png
            filters:
                thumbnail: { size: [100, 100], mode: inset }
                background: { size: [100, 100], color: '#fff' }
                strip: ~
```

Any help will be much appraciated
