### ISSUE TITLE
Cache paths 404 response since upgrade to AWS SDK 3

### ISSUE THREAD

**Issue by PaddyLock** [liip/LiipImagineBundle#726]
The paths to my images are returning 404 responses since upgrading to AWS SDK 3

Packages installed

```
"aws/aws-sdk-php-symfony": "~1.0",
"aws/aws-sdk-php": "3.2.6",
"liip/imagine-bundle": "dev-master",
```

And in my config

```
services:
    helios.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@aws.s3"
            - "%s3_bucket%"
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'profile_aws' }

aws:
    version: latest
    region: us-east-1
    credentials:
        key: '%aws_key%'
        secret: '%aws_secret%'
    S3:
        version: '2006-03-01'

knp_gaufrette:
    adapters:
        amazon:
            aws_s3:
                service_id: aws.s3
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        amazonS3:
            adapter: amazon

    stream_wrapper: ~

liip_imagine:
    cache: 'profile_aws'
    filter_sets:
        product_list:
            data_loader: stream.amazon
            quality: 80
            filters:
                thumbnail: { size: [100, 100], mode: inset }
```

This is an example of a path generated for an image which returns a 404 response

`/media/cache/resolve/product_list/uploads/images/products/ee1d4c25caff7b7c0b14f017af92b6d63d861.jpg`

**Comment by Nightbr** [comment]
hey, same error here
Also my folder `media` is symlink (maybe the problem), it works fine without the symlink...

**Comment by jehaby** [comment]
Is there anything useful in your log files? ( {{your_project_root}}/var/log/ }} by default in symfony )

**Comment by Nightbr** [comment]
`Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Source image could not be found" at /var/www/welp/shared/vendor/liip/imagine-bundle/Controller/ImagineController.php line 101`

I resolved the problem:

1. fix the version  `"liip/imagine-bundle": "1.6.*",`
2. remove the symlink /var/www/welp/current/web/media -> /var/www/welp/shared/media
3. recreate and chmod  /var/www/welp/current/web/media

NOTE: I am using capistrano to deploy my app (capistrano automaticaly create symlink to shared dir).

Also in the log:

"previous":{"class":"Liip\\ImagineBundle\\Exception\\Binary\\Loader\\NotLoadableException","message":" **Source image invalid \"/var/www/welp/shared/web/uploads/tmp/43b04f0afab14e6c440418bda56c28917a2552b1.png\" as it is outside of the defined root path**","code":0,"file":"/var/www/welp/shared/vendor/liip/imagine-bundle/Binary/Loader/FileSystemLoader.php:67","trace":["/var/www/welp/shared/vendor/liip/imagine-bundle/Imagine/Data/DataManager.php:125","/var/www/welp/shared/vendor/liip/imagine-bundle/Controller/ImagineController.php:95","{\"function\":\"filterAction\",\"class\":\"Liip\\\\ImagineBundle\\\\Controller\\\\ImagineController\",\"type\":\"->\",\"args\":[\"[object] (Symfony\\\\Component\\\\HttpFoundation\\\\Request: GET /media/cache/resolve/user_small/uploads/tmp/43b04f0afab14e6c440418bda56c28917a2552b1.png

So that was it, the Loader followed the symlink and throw and error because the media was outside the defined root. 

NOTE2: it was working well in older version of liip

**Comment by robfrawley** [comment]
@Nightbr You don't have to remove the symbolic link, you simply need to set an appropriate `data_root` value. For example:

```
liip_imagine:
  loaders:
    default:
      filesystem:
        data_root: "/var/www/welp"
```
