### ISSUE TITLE
Ignore config and service 

### ISSUE THREAD

**Issue by chadyred** [liip/LiipImagineBundle#733]
Hello,

User storie: I want to use your bundle with the Gaufrette bundle wich allow me to config the abstract layer to connect to the OpenCloud server (Rackspace, it use OpenCloud and it's in France).

In a next time, I use the VichUploader bundle which allow me to put UploadedFile to my cloud container. All is done and no problem. I load my image like this 

`<img src="{{ vich_uploader_asset(app.user.getAvatar, 'file' ) }}" alt="{{ app.user.getAvatar.getUrl }}" />`

My Avatar entity use a file field to handle the file and a url field which contain the file name.

THis is my config: 

```
knp_gaufrette:

    adapters:
        static:
            opencloud:
                object_store_id: opencloud.object_store
                container_name: static
    filesystems:
        static:
            adapter:    static
            alias:      static_filesystem

    #stream_wrapper: ~ # Needed fore vich_uploader with gaufrette, access with gaufrette://static/file.txt anywhere

    stream_wrapper:
        protocol: data # Needed fore vich_uploader with gaufrette, access with data://static/file.txt anywhere


vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    storage:   gaufrette

    mappings:
        avatar:
            uri_prefix:        http://static.domain.tld/
            upload_destination: static

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
```

Now I want to resize my avatar with your bundle. So I want to get the image, cache locally (becouse their is no cache resolver for OpenCloud service) to store image created.

So my config which use the class factory to use the wrapper (container) of my OpenCLoud  : 

```
liip_imagine:     
    loaders:
        stream.profile_avatar:
            stream:
                wrapper: data://static/

    data_loader: stream.profile_avatar

    # cache:                cache_global    
    filter_sets:
        mon_avatar_crop_profile:
            data_loader: stream.profile_avatar
            quality:              100
            filters:
                thumbnail: { size: [100, 100], mode: outbound, allow_upscale: true }
```

This is my whole service: 

```
# app/config/services.yml 
services:
  opencloud.connection:
        class: OpenCloud\OpenStack
        arguments:
          - %openstack_identity_url%
          - {username: %openstack_username%, password: %openstack_password%, tenantName: %openstack_tenant_name%}

  opencloud.object_store:
      lazy: true 
      class: OpenCloud\ObjectStore\Service
      factory: ["@opencloud.connection", objectStoreService]
      arguments:
        - %object.storage.type%
        - %object.storage.region%
        - %storage.url.type%

  kark.liip_imagine.binary.loader.stream.profile_avatar:
      class: "%liip_imagine.binary.loader.stream.class%"
      arguments:
          - 'data://static/'
      tags:
          - { name: 'liip_imagine.binary.loader', loader: 'stream.profile_avatar' }
```

So, on my view, I precise the file name and show must go on : 

```
<img src="{{ app.user.getAvatar.getUrl | imagine_filter('mon_avatar_crop_profile') }}" alt="{{ app.user.getAvatar.getUrl }}" />
```

Ths link remote a "resolve" folder in cache :

```
<img src="http://domain.local/media/cache/resolve/mon_avatar_crop_profile/Evolution-of-Walter-White.jpg" alt="Evolution-of-Walter-White.jpg">
```

All permission is on the www-data user and is group and this method override the previous local upload which worked, so I don't think it's a permission problem...
- Can I use this Liip like this, without a cache resolver ?
- My config is good or not ?
- Aws3 is a good alternative ? ( Everybody seems to use it with Google...)
