### ISSUE TITLE
Cached image paths not generated

### ISSUE THREAD

**Issue by PaddyLock** [liip/LiipImagineBundle#735]
I have the following config (it might be a bit mixed up as I'm not sure what each part does)

```
services:
    helios.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@aws.s3"
            - "%s3_bucket%"
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'helios_images' }
    helios.amazon.s3Credentials:
        class: Aws\Credentials\Credentials
        arguments: ["%aws_key%", "%aws_secret%"]

    helios.amazon.s3:
        class: Aws\S3\S3Client
        arguments:
            - version: %aws_s3_version%
              region: %aws_s3_region%
              credentials: "@helios.amazon.s3Credentials"
              ssl.certificate_authority: %aws_cert%

aws:
    version: latest
    region: us-east-1
    credentials:
        key: '%aws_key%'
        secret: '%aws_secret%'
    S3:
        version: '%aws_s3_version%'

knp_gaufrette:
    adapters:
        adapter_aws_s3_images:
            aws_s3:
                service_id: "helios.amazon.s3"
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        filesystem_aws_s3_images:
            adapter: adapter_aws_s3_images

    stream_wrapper: ~

liip_imagine:
    loaders:
        loader_aws_s3_images:
            stream:
                # This refers to knp_gaufrette filesystems configuration
                wrapper: gaufrette://filesystem_aws_s3_images/
    resolvers:
       cache_resolver_aws_s3:
          aws_s3:
              bucket: %s3_bucket%
              client_config:
                  credentials:
                      key:    %aws_key%
                      secret: %aws_secret%
                  region: %aws_s3_region%
                  version: %aws_s3_version%

              get_options:
                  Scheme: 'https'
              put_options:
                  CacheControl: 'max-age=86400' # 24 hours
    filter_sets:
        product:
            data_loader: loader_aws_s3_images
            cache: cache_resolver_aws_s3
            jpeg_quality: 80
            filters:
                thumbnail: { size: [194, 194], mode: inset }
```

When I preview a page with an image, only the full path is used. The cached image path is not generated.

Example page

https://www.helios.co.uk/shop/abundance-bush-flower-combination-30ml

Image path generated for main product image

https://s3-eu-west-1.amazonaws.com/helios-production/product/existing/products/Abundance.jpg

I am expecting something like the following on the second page load (after caching)

/media/cache/...

I am using the following packages

```
"aws/aws-sdk-php-symfony": "~1.0",
"aws/aws-sdk-php": "3.2.6",
"liip/imagine-bundle": "dev-master",
"knplabs/gaufrette": "~0.2",
"knplabs/knp-gaufrette-bundle": "~0.3",
```

And in my twig template

`{{ product.path | imagine_filter('product') }}`
