### ISSUE TITLE
Directory namer custom with liip

### ISSUE THREAD

**Issue by chadyred** [liip/LiipImagineBundle#736]
Hello,

I use this bundle with Vich upload + Aws3 + Gaufrette + Liip.

 I use a custom directory namer with VichUpload using in service. Is it possible to add the directory namer to the data loader of the cache resolver ? 

This is my directory namer and I use it as a service

```
<?php

namespace Kark\Utils\Namer;

use Vich\UploaderBundle\Naming\DirectoryNamerInterface;
use Vich\UploaderBundle\Mapping\PropertyMapping;

class MyDirectoryNamerAvatar implements DirectoryNamerInterface {

	function directoryName($entity, PropertyMapping $mapping) {

		return $entity->getUser()->getId();
	}
}
```

So I use it and work well without imagine filter. 

I use this data loader and I think (maybe) I have to add this to this service but how can i do that ?

```
# app/config/services.yml 
services:
  kark.directory_namer_avatar:
        class: Kark\Utils\Namer\MyDirectoryNamerAvatar
  kark.liip_imagine.binary.loader.stream.profile_avatar:
      class: "%liip_imagine.binary.loader.stream.class%"
      arguments:
          - 'gaufrette://filesystem_aws_s3_avatar/'
      tags:
          - { name: 'liip_imagine.binary.loader', loader: 'loader_aws_s3_avatar' }`
```

Notice that all work well if I don't use a directory prefix with my uploaded file.

Thank you !
