### ISSUE TITLE
Automatic rotation in conjunction with thumbnails

### ISSUE THREAD

**Issue by pscheit** [liip/LiipImagineBundle#737]
Hey Liip,

thank you so much for the bundle.

I have a issue with an not-yet-rotated image, which I try to thumbnail. Here's the config:

``` yaml
  filter_sets:
    xs:
      quality: 75
      filters:
        auto_rotate: ~
        thumbnail: { size: [120, 90], mode: inset }
```

My Image Size is: 2592x1944, so its landscape, but should be rotated to portrait 1944x2592
I have another Picture which is already rotated which is 1944x2592, too.

The thumbnails produces from the non-yet-rotated photo gives me: 90x120
And the already rotated one (portrait) gives me: 68x90 (which is the expected result).

I thought auto_rotate would apply first and then the thumbnail filter? Is my yaml wrong?

``` yaml
  filter_sets:
    xs:
      quality: 75
      filters:
        thumbnail: { size: [120, 90], mode: inset }
        auto_rotate: ~
```

this configuration gives me exactly the same results. So it looks like no matter what, its always thumbnailed first and then auto-rotated. Which isn't what I have expected. Are my expectations wrong?

**Comment by BartVB** [comment]
I'm using a similar config which works as expected:

```
liip_imagine:
    driver: imagick
    filter_sets:
        thumb:            
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [120, 90], mode: outbound }   
```

No idea why this isn't working for you. The documentation mentions that you should run the auto_rotate filter as early as possible:
http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#the-auto-rotate-filter

You could try using a different driver? This might solve the issue (but I'm only guessing here).
