### ISSUE TITLE
Auto rotate problem in real server

### ISSUE THREAD

**Issue by jekeyeke** [liip/LiipImagineBundle#741]
Hi everyone.

I have a problem with auto_rotate option.
In local, it works perfect but when I upload the code to the real server, the auto_rotate option doesn't work.
I'm working with Symfony and i don't know which is the problem.

This is my code:

```
liip_imagine:
    driver: gd
    cache:  default
    data_loader:   default

    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/images/cache
    filter_sets:
        original:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [1200, 1200], mode: inset }
```

I appreciate any help.

Thanks
