### ISSUE TITLE
defne public route

### ISSUE THREAD

**Issue by grekpg** [liip/LiipImagineBundle#743]
i have this situation - http://stackoverflow.com/questions/37544167/liipimaginebundle-https-behind-varnish 

HTTPS -> NGINX -> VARNISH -> APACHE2 -> SYMFONY 

so need have https:// in public routes but cannot add schemat to routing.

**Comment by rispo-service** [comment]
I have a similar situation

**Comment by antoligy** [comment]
Hi, your question seems to have been removed from Stack Overflow.

Is there any reason that the scheme cannot be defined in routing, or via a custom event handler within Symfony?

**Comment by robfrawley** [comment]
You can easily force a specific schema using the native Symfony firewall configuration options. For example, if you assets are cached at "/your/custom/base/path" and that is all you want to have forced to HTTPS, use the following within your `config.yml`:

```yml
security:
    access_control:
        - { path: ^/your/custom/base/path, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```

Similarly, to also force the `liip_imagine` routes to HTTPS, use:

```yml
security:
    access_control:
        - { path: ^/media/cache/resolve, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```

IMHO, this should not be a concern of this bundle given the native support in the full stack Symfony framework.
