### ISSUE TITLE
Redirection to login if cached image not created

### ISSUE THREAD

**Issue by d2sr** [liip/LiipImagineBundle#747]
Hi,

I habe the following problem: if an image isn't in the cache, liip imagine redirects to the fosuserbundle/login page. I just can't find wrong configuration...

`liip_imagine:
    resolvers:
        default:
            web_path: ~

```
filter_sets:
    cache: ~
    list_item:
        quality: 75
        filters:
            relative_resize: { widen: 164 }`
```

`_liip_imagine:
    prefix:   /images/rs/
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
`

any ideas? thanks!
