### ISSUE TITLE
Applying filter to a SVG file does not work

### ISSUE THREAD

**Issue by Torpedr** [liip/LiipImagineBundle#749]
Hi there. I have a serious problem resizing SVG files..
For example, I saved the same file as SVG and as PNG.

Code:

```
<img src="{{ '/uploads/file.png'|imagine_filter('thumbnail') }}" />
<img src="{{ '/uploads/file.svg'|imagine_filter('thumbnail') }}" />
```

Thumbnail shows only for the first image.

The error is:
`Unable to create image for path "uploads/file.svg" and filter "thumbnail". Message was "Unable to open image ~app/../web/uploads/file.svg"`
But the file exists in the filesystem!

Also, the generated path for this SVG file is incorrect:
`http://localhost:8000/media/cache/resolve/avatar_thumb/uploads/file.svg`
Why 'resolve'?

Instead of:
`http://localhost:8000/media/cache/avatar_thumb/uploads/file.svg`

**Comment by deviprsd21** [comment]
GD, gmagic driver don't yet support SVG, imagick does. Try changing the driver, other than that the bundle needs to probably support it too, maybe it does (haven't tried svg files yet)

**Comment by antoligy** [comment]
SVGs should be supported, the underlying library supports these and [includes them in its test suite](https://github.com/avalanche123/Imagine/blob/eb3c8d281632ddfeb18dda7d9195c1433d8c1c65/tests/Imagine/Test/Image/AbstractImageTest.php#L717-L723).

At a glance this looks like an issue with configuration - Could you provide more information about how you have configured the bundle, and as @deviprsd21 has said the driver you are currently using?

**Comment by kimwue** [comment]
Hi,

I'm having the same issue with applying a filter using twig to a svg. I use the driver imagick.

My config and filter:

```
liip_imagine:
    driver: imagick
    cache: default
    resolvers:
       default:
          web_path:
            web_root: %kernel.root_dir%/../web
            cache_prefix: /media/cache
    filter_sets:
        cache: ~
        exhibitor_booth:
            filters:
                relative_resize: { widen: 450px }
```

The image doesn't load in Firefox, and in Chrome the whole page doesn't even load.

Using version 1.6.*
