### ISSUE TITLE
Compatible with Symfony 3.1.1 ?

### ISSUE THREAD

**Issue by saundersgreg** [liip/LiipImagineBundle#765]
Hi,

Is this compatible with Symfony 3.1.1 ?

I've tried a basic usage case, but no thumbnail is generated - I'm running the inbuilt local PHP server.

I have these two img elements in a twig file:

```
<img src="/images/image.jpg" />
<img src="{{ '/images/image.jpg'|imagine_filter('thumb') }}" />
```

The first display the image correctly but the second produces the below img url but no image has been created:

`<img src="http://localhost:8000/media/cache/resolve/thumb/images/image.jpg">`

My config is very basic

```
# LiipImagine Configuration
liip_imagine:
    filter_sets:
            thumb:
                quality: 75
                filters:
                    thumbnail: { size: [50, 50], mode: outbound }
```
