### ISSUE TITLE
Image not generated and "resolve" in path

### ISSUE THREAD

**Issue by phong-steph** [liip/LiipImagineBundle#784]
Hello, 
It seems that LiipImagineBundle does not create the cached image and there is a "resolve" in the path returned by imagine_filter. 

Here the twig code : < img src="{{ asset('img/gallery/p1/test2.jpg') | imagine_filter('my_thumb') }}" />
And the path returned: http://localhost/app_dev.php/media/cache/**resolve**/my_thumb/img/gallery/p1/test2.jpg

If I want to generate an image, I have to manually create the image using: app/console liip:imagine:cache:resolve relative/path/to/image.jpg relative/path/to/image2.jpg --filters=my_thumb --filters=thumbnail_default

How can I automatically generate the image? Thanks

**Comment by cedricziel** [comment]
What resolver are you using? I'm having the same issues in just the production environment and I'm having a hard time to debug it..

**Comment by phong-steph** [comment]
I guess I am using default resolver so it might be cacheResolver

**Comment by robfrawley** [comment]
`CacheResolver` is a decorator for another resolver implementation. Can you share you configuration YAML?

FYI: An initial page request will return the `resolve` path. Subsequent request should be resolved already.

**Comment by phong-steph** [comment]
Ok thank you for your anwer.

Here is my LiipImagineBundle config: 

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        my_thumb:
            quality: 20

**Comment by winter7621** [comment]
I'm also having this problem, but only for some filter_sets.

    filter_sets:
        ash_small:
            data_loader: aws_loader
            cache: aws
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

The above is my config file setup. I'm working with Symfony CMF Blocks and if I use the default `slideshow_medium` filter, the filter works OK. But if I use my filter up above, it doesn't work

**Comment by robfrawley** [comment]
> How can I automatically generate the image? Thanks

So, your config is simple and quite standard. There is nothing about it that would advice me as to why you are experiencing issues. Are you sure images are not being generated? The `resolve` string should be in the URL on the first request...

**Comment by cedricziel** [comment]
Sorry for not coming back to this earlier. nginx shortcircuited request to assets so the filesystem which resulted in 404s and thus not generating correct URLs even on second load.

Removing the shortcurcuiting resolved my issue. Plus it's a little embarassing :)

**Comment by robfrawley** [comment]
@cedricziel Don't ever be embarrassed to explain the resolution to your issue, regardless of the origin of the malfunction. The absolute rock-stars of our field make the same mistakes as everyone else, and sharing it only serves to help others avoid banging their head against the wall suffering the same misconfiguration.

(If you ever happen upon a GitHub issue tracker who's members that pokes fun at your misfortune oversight, it'd be a good time to leave that project to slowly implode and die out, as the only remaining members become the elite a******s who talk down to and belittle their user base.)

**Comment by cedricziel** [comment]
Hey @robfrawley , thank you so much for encouraging a proper and open communication style on issues. Reading your answer made me smile and boosts confidence! :)

Did you solve your problems as well, @phong-steph ? Maybe - and only mabye - you're bitten by the same problem. :)

**Comment by phong-steph** [comment]
Hello,

Yep it solved it! thank you ;)

**Comment by jeroendesloovere** [comment]
I'm having the same problem.
Didn't find any solution yet.
```
liip_imagine:
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~
        # the name of the "filter set"
        backend_thumb:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size : [120, 90], mode : outbound }
```

My twig layout:
```twig
<img src="{{ item.mediaItem.webpath() | imagine_filter('lightbox_small') }}" itemprop="thumbnail" alt="{{ item.mediaItem.title }}" />
```
Result in HTML
`<img src="http://xxx.dev/media/cache/resolve/lightbox_small/src/xxx/xxx.jpg" itemprop="thumbnail" alt="zonnepaneel4-large">`

Can somebody help me?

**Comment by pascalbeynel** [comment]
I had the same problem. Just launch :
`php bin/console liip:imagine:cache:resolve relative/path/to/image1.jpg --filters=yourfilter`
You will get the error message. In my case, I was on a new server with GD not installed.

**Comment by jeroendesloovere** [comment]
Hi @pascalbeynel, that is a temporary solution for one image.
But I have hundreds of images...

**Comment by jeroendesloovere** [comment]
Anybody else knows a solution that fixes it?

**Comment by pascalbeynel** [comment]
@jeroendesloovere The idea is to test with one image. This way you can have the error detail why your thumbnails are not generated.

**Comment by jeroendesloovere** [comment]
Well, that is the strange thing.
My config.yml
![schermafbeelding 2017-03-20 om 15 55 23](https://cloud.githubusercontent.com/assets/588616/24105621/c0a146f4-0d85-11e7-8c4a-79a50416c410.png)

When I execute:
`php app/console liip:imagine:cache:resolve Source/01/schermafbeelding-2017-03-16-om-14-31-17.png --filters=backend_thumb`

The image is created.
But when I refresh the page, the image url is still:
`<img src="http://xxx/media/cache/resolve/lightbox_small/src/Frontend/Files/MediaLibrary/Source/01/istock-000001779902small.jpg" itemprop="thumbnail" alt="istock-000001779902small">`

Do you have any further tips @pascalbeynel ?

**Comment by indapublic** [comment]
@jeroendesloovere Hm, probably I have same issue. Are you using nginx?

**Comment by jeroendesloovere** [comment]
I fixed it by moving 
```yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```
To the top in `app/config/routing.yml`

**Comment by indapublic** [comment]
@jeroendesloovere Tried this, not solved my issue. Are you using nginx?

**Comment by jeroendesloovere** [comment]
I'm not using nginx.
Did you did `app/console cache:clear`?

**Comment by indapublic** [comment]
Yeah, I tried, no difference :)
But I founded solution. I add instruction to my nginx and all works!

```
location /media/cache/resolve {
    try_files $uri @rewriteapp;
}
```

Cheers!

**Comment by robfrawley** [comment]
I don't know why you are only using `try_files` at that location (how do you properly serve up CSS or image files?). For those having issues with Nginx, the configuration I always use for Symfony (including projects with this bundle) is the following:

```nginx
  location / {
      try_files $uri @rewrite_framework;
  }

  location @rewrite_framework {
      rewrite ^(.*)$ /app.php/$1 last;
  }
```

**Comment by indapublic** [comment]
@robfrawley In my project this is the correct config, but thanks, I will remember your remark in the future

**Comment by stephanvierkant** [comment]
jeroendesloovere's solution worked for me. (using Apache)

**Comment by diriy** [comment]
@robfrawley could you please explain for those who can't find where to place this config to nginx, where should it be placed? Can't really figure it out...

**Comment by indapublic** [comment]
@diriy Inside `server` section

**Comment by diriy** [comment]
@indapublic , I understand it. But, unfortunately, it crashes everytime, I try to launch the server. my nginx config is the following:

`server {
    listen         %ip%:%httpport%;
    listen         %ip%:%httpsport% ssl;
    server_name    %host% %aliases%;
    
    ssl_certificate               "%sprogdir%/userdata/config/cert_files/server.crt";
    ssl_certificate_key           "%sprogdir%/userdata/config/cert_files/server.key";
    
    location ~ /\. {deny all;}

    location / {
        proxy_buffer_size         64k;
        proxy_buffering           on;
        proxy_buffers             4 64k;
        proxy_connect_timeout     5s;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    off;
        proxy_pass                http://%ips%:%httpbackport%/;
        proxy_pass_header         Server;
        proxy_read_timeout        5m;
        proxy_redirect            off;
        proxy_send_timeout        5m;
        proxy_set_header          Host $host;
        proxy_set_header          X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header          X-Real-IP $remote_addr;
        proxy_set_header          X-Forwarded-Proto $scheme;
        try_files $uri @rewrite_framework;
    }

    location @rewrite_framework {
      rewrite ^(.*)$ /app.php/$1 last;
    }

    location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|js|cur|swf)$ {
        root     "%hostdir%";
        expires  7d;
    }

    location ^~ /apacheicons/ {
        alias    %sprogdir%/modules/http/%httpdriver%/icons/;
    }
    location ^~ /apacheerror/ {
        alias    %sprogdir%/modules/http/%httpdriver%/error/;
    }
    
    location /openserver/ {
        %allow%allow    all;
        allow    127.0.0.0/8;
        allow    ::1/128;
        allow    %ips%;
        deny     all;

        location /openserver/server-status {
            stub_status on;
        }

        proxy_buffer_size         64k;
        proxy_buffering           on;
        proxy_buffers             4 64k;
        proxy_connect_timeout     5s;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    off;
        proxy_pass                http://%ips%:%httpbackport%/openserver/;
        proxy_pass_header         Server;
        proxy_read_timeout        5m;
        proxy_redirect            off;
        proxy_send_timeout        5m;
        proxy_set_header          Host $host;
        proxy_set_header          X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header          X-Real-IP $remote_addr;
        proxy_set_header          X-Forwarded-Proto $scheme;

        location ~* ^/openserver/.+\.(jpg|jpeg|gif|png|ico|css|js|cur|swf)$ {
            root     "%sprogdir%/modules/system/html";
            expires  7d;
        }
    }

    location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
    # PROD
    location ~ ^/app\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
      
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
       
        internal;
    }
}`

Where did I do a mistake? I use OpenServer. Thank you for your help!

**Comment by indapublic** [comment]
@diriy `nginx -t` said anything?

**Comment by robfrawley** [comment]
@diriy There are multiple mistakes in your example, for example you don't define a `root` for Symfony's context. Also, you should always run `nginx -t` (you may need to run that as `sudo`) to check your configuration syntax, as well.

I run my site on PHP-FPM using the FastCGI transport of Nginx. Here is a basic, working example:

```ngin
server {
	listen      80;
	listen      443 ssl http2;
	server_name domain.com;
	root        /web/domain.com/web;

	access_log /var/log/nginx/acess_domain.com.log combined buffer=256k flush=10m;
	error_log  /var/log/nginx/error_domain.com.log error;

	location / {
	  try_files $uri @rewrite_framework_symfony;
	}

	location @rewrite_framework_symfony {
	  rewrite ^(.*)$ /app.php/$1 last;
	}

	location ~ \.php(/|$) {
		fastcgi_param QUERY_STRING      $query_string;
		fastcgi_param REQUEST_METHOD    $request_method;
		fastcgi_param CONTENT_TYPE      $content_type;
		fastcgi_param CONTENT_LENGTH    $content_length;

		fastcgi_param SCRIPT_NAME       $fastcgi_script_name;
		fastcgi_param REQUEST_URI       $request_uri;
		fastcgi_param DOCUMENT_URI      $document_uri;
		fastcgi_param DOCUMENT_ROOT     $document_root;
		fastcgi_param SERVER_PROTOCOL   $server_protocol;
		fastcgi_param HTTPS             $https if_not_empty;

		fastcgi_param GATEWAY_INTERFACE CGI/1.1;
		fastcgi_param SERVER_SOFTWARE   nginx/$nginx_version;

		fastcgi_param REMOTE_ADDR       $remote_addr;
		fastcgi_param REMOTE_PORT       $remote_port;
		fastcgi_param SERVER_ADDR       $server_addr;
		fastcgi_param SERVER_PORT       $server_port;
		fastcgi_param SERVER_NAME       $server_name;

		fastcgi_split_path_info         ^(.+\.php)(/.*)$;
		fastcgi_buffer_size             384k;
		fastcgi_buffers                 1024 8k;
		fastcgi_busy_buffers_size       384k;
		fastcgi_temp_file_write_size    384k;
		fastcgi_param                   SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param                   REDIRECT_STATUS 200;
		fastcgi_read_timeout            1m;
		fastcgi_pass                    127.0.0.1:9090;
	}
}
```

**Comment by dkuss** [comment]
I just encountered the same problem on an Apache Server. My config worked fine on my local development machine, but on the server the thumbnails were not generated and the "resolve" path showed up in the path to the thumbnail image.

Now i know that the "resolve" path is a hint for the bundle that there is no cached image yet and needs to be generated. If there IS a ached thumbnail this path will disappear from the url.

The problem showed up after setting up a deployment system that required me to move the image cache folder outside the application folder to a seperate shared files folder. So the cached files were only available via a symlink. But the bundle checks the absolute filesystem paths and stops working if your cache directory is outside your application directory. The Exception meesage showed up after trying to run the resolver via command line.

**The solution** was to configure the file_system loader with an additional data_root path to my shared files folder. that looks something like this:

```# configuration für liip imagine bundle und thumbnails / filter sets
liip_imagine:
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # loaders
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.root_dir%/../web/'
                    - '%liip_imagine_web_root%'
```

The first path is the default path, the second is my new parameter that i can define in parameters.yml and holds the complete absolte path to the shared files folder ( /var/www/......  ).

After clearing the cache everything is working properly again.

Good Luck!

**Comment by aricci95** [comment]
@dkuss solution worked for me, thank you man, was trying to make this work for weeks.

**Comment by dhirajpatra** [comment]
For some unknown reason installing php-imagick didn't work for me. The module was getting loaded for the PHP CLI (I checked with php -m | grep -i imagick) but through my nginx webserver it didn't show up in the list of modules reported by phpinfo() at all. I even inserted extension=imagick.so to /etc/php/7.0/fpm/php.ini manually, just to make sure.

I then purged the php-imagick package and installed from cpan:

sudo apt install libmagickwand-dev imagemagick php-dev
sudo pecl install imagick
And still, no cigar. It would work through the cli but not via nginx. Turns out I had to restart the fpm:

sudo service php7.0-fpm reload
Now it works just fine.

**Comment by cedricziel** [comment]
Thank you, @dhirajpatra for sharing your solution!

**Comment by soulghard** [comment]
If I try to access to the given "resolve" path in my browser, I'm redirected to my login page. Is there something to investigate this way ?

**Comment by inoubli** [comment]
In my case it was the "gd" not installed, simply solved the issue by uncommenting the extension under php.ini:
;extension=gd2
to
extension=gd2

**Comment by hugomonfouga** [comment]
Hey, I had this problem on my production server (using apache) and tried all the different solutions mentioned above.

Turns out I generated the apache .conf file and didn't double check it.

by adding 
<Directory "/var/www/[direcotry name]/current/public">
        Allow from all
        AllowOverride All
        Options -MultiViews
        Require all granted
    </Directory>

to the .conf file and reloading apache all was working properly again.

**Comment by kaizokou** [comment]
update to @dkuss solution for SF 4.4

```
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public/'
                    - '%env(LIIP_PUBLIC_PATH)%'
```

Then add LIIP_PUBLIC_PATH to your .env and .env.local file
Example : 

LIIP_PUBLIC_PATH=/var/www/myproject/shared/public

**Comment by ChristopheFerreboeuf** [comment]
I had the same problem and it was linked to nginx with web browser caching for images. @cedricziel reported it earlier in this thread but did not provide solution. As, like me, you may not be really at ease with nginx. I share my solution. If it is bad pattern, please tell me. It works but I recently moved from apache2 to nginx so it can be inaccurate.
```
    location ~*  \.(jpg|jpeg|png|gif|ico)$ {
        expires 365d;
        log_not_found off;
        access_log off;
        try_files $uri $uri/ /index.php?$query_string;
    }
```

**Comment by bastoune** [comment]
I had the same problem beacuse i used nginx cache as :
```
    # Media: images, icons, video, audio, HTC
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

I had to add  `try_files $uri $uri/ /index.php$is_args$args;` in this directive to make it work.

**Comment by pottink** [comment]
You can also use this instead of creating extra parameters or ENV variables.

```
liip_imagine:
  resolvers:
    default:
      web_path: ~

  loaders:
    default:
      filesystem:
        data_root:
          - '%kernel.project_dir%/public'
          - '%kernel.project_dir%/../../shared/public'
```

**Comment by ChristopheZOL** [comment]
> php app/console liip:imagine:cache:resolve

Hi everyone,

just to add my little stone to the wall, thanks for the hint here, we found the solution.

By using this command on prod (AWS EC2 with Apache + Cloudfront), we checked that the file can be correctly resolved. The problem was in the Cloudfront settings where we configured the distribution to serve directly the content from S3 if url match pattern "media/*"

(extract from cloud formation template)
```yaml
        CacheBehaviors:
          - Compress: true
            ForwardedValues:
              QueryString: false
            TargetOriginId: s3-media-endpoint
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            DefaultTTL: 30
            MaxTTL: 60
            PathPattern: "media/*"
```
By commenting theses lines and updating the distribution, the resolve is done correctly. For the moment we will let it disabled, I think we can change the pattern to exclude media/cache/resolve to fix it properly.

Hope it will help someone, some day.

**Comment by Geod-exe** [comment]
Heyy !
I have the same probleme in symfony 5, when I'm in prod on my computer its okkay but when i push on OVH in production, liip imagine not generate images....
I just read and test all solutions but didnt work....
![Screenshot_20220128_195528](https://user-images.githubusercontent.com/79382688/151605366-36c255c2-c303-4a52-8f2e-ed244ab828f8.png)
```
liip_imagine:
    driver: "imagick"
    default_filter_set_settings:
        format: webp
    resolvers:
        default:
            web_path: ~
    twig:
        mode: lazy
    filter_sets:
        cache: ~
        miniature:
            quality: 75
            filters:
                thumbnail: { size: [390, 220], mode: outbound }
        post:
            quality: 85
            filters:
                thumbnail: { size: [780, 440], mode: outbound }
        crud:
            quality: 75
            filters:
                scale:
                    dim: [600, 600]
        full:
            quality: 95
            filters:
                scale:
                    dim: [1000, 1000]
        about:
            quality: 75
            filters:
                thumbnail: { size: [330, 275], mode: outbound }
```

The default image path is public/img/home/jpg and use full filter

In dev the path is /public/media/cache/<filter>
But in prod path is /public/media/cache/resolve/<filter>/img/.... and its not generate image...

**Comment by KevinRoig** [comment]
@Geod-exe Did you find a solution? Having exactly the same issue with OVH.

**Comment by biron75** [comment]
Hello,
@Geod-exe, @KevinRoig , did you find a solution please ? Having exactly the same issue with OVH too..
Thanks

**Comment by biron75** [comment]
Hello,
I recently ran into the exact same problem as @Geod-exe and @KevinRoig.
I solved it using the [apache Symfony pack](https://symfony.com/doc/5.4/setup/web_server_configuration.html).
(thanks to the .htaccess file generated by the bundle recipe)
`composer require symfony/apache-pack`
Hoping this can help someone.
Bye

**Comment by KevinRoig** [comment]
Hi, 
thanks for your answer @biron75 , but for me, it was just a route problem in my /config/packages/liip_imagine.yaml.
I had to put this because OVh uses a "www"folder: 
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/www"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/www"
                cache_prefix: media/cache
Bye

**Comment by melroy89** [comment]
> I had the same problem beacuse i used nginx cache as :
> 
> ```
>     # Media: images, icons, video, audio, HTC
>     location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
>         expires 1M;
>         access_log off;
>         add_header Cache-Control "public";
>     }
> ```
> 
> I had to add `try_files $uri $uri/ /index.php$is_args$args;` in this directive to make it work.

Indeed, see more info: https://symfony.com/bundles/LiipImagineBundle/current/optimizations/avoid-redirects.html

Important: The order does matter. Be sure to put the `location ~ ^/media/cache/resolve {}` directive above the image cache directive under Nginx. 

Only then you can safely set the redirect from 302 (default) to 301 in the `config/packages/liip_imagine.yaml` file:

```yml
liip_imagine:
    .....

    controller:
        redirect_response_code: 301
```
