### ISSUE TITLE
Can't create thumbnail for JPEG

### ISSUE THREAD

**Issue by ktrzos** [liip/LiipImagineBundle#801]
I have an error with JPEG images. Your bundle don't want to create thumbnail for this file (and yes, file is uploaded properly):
http://image.prntscr.com/image/69ce55e73e264f18be5ba4bcdfc8b7fe.png

Code in Twig:

```
{{ value }}
<img src="{{ value|imagine_filter('beckend_image_list') }}">
```

Config:
```
parameters:
    images_quality: 80

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: images/thumb

    filter_sets:
        cache: ~
        beckend_image_list:
            quality: '%images_quality%'
            filters:
                thumbnail: { size: [200, 200], mode: inset }
```
