### ISSUE TITLE
Watermark-Filter does not support transparency? 

### ISSUE THREAD

**Issue by Stuffy** [liip/LiipImagineBundle#808]
When using the watermark-filter, the watermark appears with a black background on the filtered image.
These are the filter settings im using:

```
watermark_image:
            filters:
                strip: ~
                watermark:
                    image: ../data/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
```

Am I doing something wrong?
