### ISSUE TITLE
Could not find configuration for a filter

### ISSUE THREAD

**Issue by Doums** [liip/LiipImagineBundle#815]
Hi,
I have just install LiipImagineBundle by following that official doc http://symfony.com/doc/current/bundles/LiipImagineBundle/installation.html

And I get this error when I try to use my filter in my twig view :
`An exception has been thrown during the rendering of a template ("Could not find configuration for a filter: avatar") in PMCoreBundle::base.html.twig at line 31.`

in vendor/liip/imagine-bundle/Imagine/Filter/FilterConfiguration.php at line 34:

```
        public function get($filter)
        {
            if (false === array_key_exists($filter, $this->filters)) {
                throw new NonExistingFilterException(sprintf('Could not find configuration for a filter: %s', $filter));
            }
            return $this->filters[$filter];
```

My app/config/config.yml

```
# LiipImagineBundle Configuration
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
    filter_sets:
        cache: ~
        avatar:
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
```

AppKernel.php

```
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new PM\PlatformBundle\PMPlatformBundle(),
            new PM\CoreBundle\PMCoreBundle(),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new Liip\ImagineBundle\LiipImagineBundle(),
            new FOS\UserBundle\FOSUserBundle(),
            new PM\UserBundle\PMUserBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();
        }

        return $bundles;
    }
```

app/config/routing.yml

```
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```

and in my view:

`<img src="{{ asset('img/headshot_default/default-profile.png') | imagine_filter('avatar') }}" alt="" class="img-circle pull-right">`

What's wrong ?

(I use symfony 3 and php7)

**Comment by antoligy** [comment]
Hey,

At a glance it seems that there are a few issues with your configuration.

Could you try with the below configuration and let me know if you have any luck?
```
# LiipImagineBundle Configuration
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        avatar:
            quality: 75
            cache: ~
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
```
