### ISSUE TITLE
Private images handling

### ISSUE THREAD

**Issue by prodriguezval** [liip/LiipImagineBundle#817]
Hi,

Is there any way to restrict the access of the compressed images to non-authenticated users using this bundle?, all the processed images go to a public folder in all the examples that I found in the web.

Anyone have a workaround?

Thanks in advance for the help
Greetings

**Comment by robfrawley** [comment]
I'm not 100% clean as to the behavior you would like. _If the intention is to allow access to the transformed images only to authenticated users, and simply deny such to non-authenticated users at the HTTP-level_, then Symfony's [security component](http://symfony.com/doc/current/security.html) allows you to perform such by defining [firewall rules](http://symfony.com/doc/current/security.html#initial-security-yml-setup-authentication).

On the other hand, _if the intention is to always serve an image to all users, but selectively decide whether it is the original version or the transformed version of the image_, then there is no native functionality within this bundle to achieve that, but implementing it should be fairly straight forward by extending any required component class definitions, injecting any required services, and performing the desired conditional in your overridden method before calling it's parent.

If the latter is what you are looking to accomplish and you need some insight into where to begin, give a shout; I don't have the time to provide any examples in the immediate, but will be happy to later tonight or tomorrow morning when I'm not running out the door. ;-)

**Comment by prodriguezval** [comment]
Hi @robfrawley, 
Thanks for the answer :+1: 

I'm going to build a social network, I want to compress the user photos to improve the site performance, but also want to keep the more private possible, like:

1 -  if you're not my friend, you can see my photos
2 - If you aren't logged you can see any photos

By default this bundle store the compressed images in the public folder this folder is always visible, with the symfony security component, I think that we can achieve the point 2, not sure if I can achieve the 1

**Comment by robfrawley** [comment]
@prodriguezval Was one of those two points supposed to contain a "can't" in there instead of a "can"?

**Comment by prodriguezval** [comment]
@robfrawley yes, the point 1, 

I don't know if this can be achieved with this bundle.

This is my particular doubt

Thanks

**Comment by robfrawley** [comment]
@prodriguezval It absolutely can! ;-)

A fairly straight-forward way to handle this would be overwriting the default imagine controller with our own implementation. Let's create a new controller named `ImagineController` and place it at `src/AppBundle/Controller/ImagineController`.

Additionally, I'm assuming the existence of a service named `user.network.examiner` that contains helper functions for making assertions about the current user's social network context. Most importantly, it has a method signature `areFriends(User ...$users)` that checks any arbitrary list of users to ensure they are all friends. Moreover, another service exists named `user.media.inspector` that exposes a method with signature `getMediaOwner($mediaResource)` that accepts the resource (the file path string, file id, or whatever) and returns a `User` instance representing the owner of the passed resource.

So, let's write `src/AppBundle/Controller/ImagineController`:

```php
<?php

namespace AppBundle\Controller;

use AppBundle\Network\MediaInspector
use AppBundle\Network\NetworkExaminer
use Liip\ImagineBundle\Controller\ImagineController as BaseImagineController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class ImagineController extends BaseImagineController
{
    private $tokenStorage;
    private $mediaInspector;
    private $networkExaminer;

    public function setMediaInspector(MediaInspector $inspector)
    {
        $this->inspector = $inspector;
    }

    public function setTokenStorage(TokenStorage $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    public function setNetworkExaminer(NetworkExaminer $networkExaminer)
    {
        $this->networkExaminer = $networkExaminer;
    }

    public function filterAction(Request $request, $path, $filter)
    {
        $this->assertAllowableResourceForUser($path);

        return parent::filterAction($request, $path, $filter);
    }

    public function filterRuntimeAction(Request $request, $hash, $path, $filter)
    {
        $this->assertAllowableResourceForUser($path));

        return parent::filterRuntimeAction($request, $hash, $path, $filter);
    }

    private function assertAllowableResourceForUser($image)
    {
        if (!$owner = $this->mediaInspector->getMediaOwner($image)) {
            // do something special if media owner cannot be determined?
            throw new \RuntimeException(sprintf('Cannot determine media owner of "%s"...', $image));

            // or perhaps just allow in this case/
            return;
        }

        if (!$user = $this->getUser()) {
            // do something special if no user logged in (anonymous)?
            throw new \RuntimeException('Cannot determine active user (must be anonymous)...');

            // or perhaps just allow in this case/
            return;
        }

        if (!$this->networkExaminer->areFriends($user, $owner)) {
            // do something special if owner and active user are not friends?
            throw new AccessDeniedException('Cannot view photo of user outside of your friend network...');
        }
    }

    private function getUser()
    {
        if (!$token = $this->tokenStorage->getToken()) {
            return false;
        }

        if (!$user = $token->getUser()) {
            return false;
        }

        return $user;
    }
}
```

And now, let's register our new controller (and we'll write up quick template entries for our helper services you would need to define): 

```
# app/config/services.yml

parameters:
    liip_imagine.controller.class: AppBundle\Controller\ImagineController

services:
    liip_imagine.controller:
        class: "%liip_imagine.controller.class%"
        arguments:
            - "@liip_imagine.data.manager"
            - "@liip_imagine.filter.manager"
            - "@liip_imagine.cache.manager"
            - "@liip_imagine.cache.signer"
            - "@liip_imagine.data.manager"
            - "?@logger"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
            - [setNetworkExaminer, ["@user.network.examiner"]]
            - [seMediaInspector, ["@user.media.inspector"]]

    user.network.examiner:
        class: AppBundle\Network\NetworkExaminer
        arguments:
            # you'll need some other services passed here, likely

    user.media.inspector:
        class: AppBundle\Network\MediaInspector
        arguments:
            # you'll need some other services passed here, likely
```

So... something like that would solve your use-case?
