### ISSUE TITLE
Scale filter not found / incorrect filter config documentation

### ISSUE THREAD

**Issue by ktrzos** [liip/LiipImagineBundle#818]
http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html#scale

```
parameters:
    images_quality: 80

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: images/thumb

    filter_sets:
        cache: ~
        news_image:
            quality: '%images_quality%'
            filters:
                scale: { dim: [ 1000, 666 ] }
```

AAaaaaaaand it's not working. Returning error:

> Could not find filter loader for "scale" filter type 

Why documentation is writing about something that is not working???

And, when I'm adding `-` character before `scale: { dim: [ 1000, 666 ] }` (based on documentation from Symfony.com), error occurs:

> The attribute "name" must be set for path "liip_imagine.filter_sets.news_image.filters".

Where is the most updated documentation for this bundle...?
