### ISSUE TITLE
data_root and symbolic link

### ISSUE THREAD

**Issue by TomCamin** [liip/LiipImagineBundle#826]
Hi

I use a tool to deployer new version in production : https://github.com/REBELinBLUE/deployer

I have to folder releases with last 10 releases that i have deployer and latest who is a symbolic link to the last release.

I have an error with LiipImagineBundle : 
`Source image could not be found`
And the exeption : 
`Source image invalid "..../releases/20161126155635/src/Project/TestBundle/Resources/public/img/logo.png" as it is outside of the defined root path`
My apache configuration is link to ..../latest/web

I have try to set : 
`liip_imagine:
    loaders:
       default:
          filesystem:
            data_root: "/......../releases/20161126155635/src"`
And the result : 
`Source image not resolvable "bundles/projecttest/img/logo.png"`

Thanks to help me!

**Comment by robfrawley** [comment]
So, I am going to go out on a limb here and make some assumptions that would help explain your difficulties.

1. Your entire project is deployed in such a way that the live folder is a symbolic link to the currently released code base root.
2. You have installed your Symfony assets using the "symbolic" option, causing an additional level of redirection within your project root.

Fun. ;-) Let's confirm everything is at the very least setup correctly by doing this:

- Use the following as your data root value: `/[...]/releases/`
- Attempt to resolve the image `logo.png` by passing the following: `20161126155635/web/bundles/projecttest/img/logo.png`

With the above, does this bundle correctly resolve your image?

**Comment by TomCamin** [comment]
Thanks a lot for your answer!

I just try to install assets without symbolic links and works fine now ^^

**Comment by prathje** [comment]
I had the very same problem. I could finally solve it by adding additional data roots and configure them to be unresolvable:

 ```
   loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
                    - "%kernel.project_dir%/../../current/public"
                    - "%kernel.project_dir%/../../shared/public"
                allow_unresolvable_data_roots: true
```
