### ISSUE TITLE
helper not working

### ISSUE THREAD

**Issue by ahbaqdadi** [liip/LiipImagineBundle#838]
im on symfony 2,8 version 

when i want to use this 
<img src="{{ asset('my path/my-image.jpg') | imagine_filter('my_thumb') }}" />

helper , i got nothing 

here is my config 

```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [124, 94], position: center, color: '#000000' }
```
and my routing 

```
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```
