### ISSUE TITLE
image in media cache are not created

### ISSUE THREAD

**Issue by stickyhands** [liip/LiipImagineBundle#842]
Unable to create image for path "images/fiches/586bb8aa4da2e.jpg" and filter "thumb". Message was "Unable to open image /var/www/xxx/app/../web/images/fiches/586bb8aa4da2e.jpg"

My config is default:
```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
```

and in twig:

`<img src="{{ asset('images/fiches/' ~ sheet.imageName) | imagine_filter('thumb') }}" alt="" />
`

I also tried with the cli:

php bin/console liip:imagine:cache:resolve images/fiches/586bb8aa4da2e.jpg --filters
=thumb

 ```
[Imagine\Exception\RuntimeException]
Unable to open image /var/www/xxx/app/../web/images/fiches/586bb8aa4da2e.jpg
```
