### ISSUE TITLE
Multiple "Source image could not be found" since 1.7 update

### ISSUE THREAD

**Issue by picks44** [liip/LiipImagineBundle#849]
Since the update to 1.7, I have problems with images not being found and therefore no image beeing generated by the bundle.

Error is "Source image could not be found", and "[1/2] NotLoadableException: Source image invalid "C:\wamp\www\MyProject\src\MyBundle\Resources\public\images\icon.png" as it is outside of the defined root path".

I haven't changed my config  
```
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumb:
            filters:
                background: { size: [1140, 400], color: '#fff' }
                strip: ~
```

I'm also using VichUploaderBundle and the Symfony asset versioning system

```
framework:
    assets:
        version: 'X'
```

 so my Twig looks either like 

`{{ asset('bundles/mybundle/images/icon.png'|imagine_filter('thumb')) }}`

or

`{{ vich_uploader_asset(enity, 'iconFile')|imagine_filter('thumb') }}`

My assets are installed with symbolic links.

**Comment by robfrawley** [comment]
Please close and reference the already opened issue #846 and PR #848.

**Comment by robfrawley** [comment]
Please see if #851 resolves your issue.

**Comment by picks44** [comment]
Well I have to wait vor v1.7.1 to try this as I guess I have several data_root pah to configure (one for the bundle images, and one for the manual user uploads).

**Comment by picks44** [comment]
To me this new config is not really "user-friendly"...

**Comment by picks44** [comment]
Now I have the error `"Root image path not resolvable "kernel.root_dir%/../web/uploads"`... 

My confil.yml
```
liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
          filesystem:
            data_root: "kernel.root_dir%/../web/uploads"
    filter_sets:
        cache: ~
        thumb:
            ....
```

**Comment by adaniloff** [comment]
@picks44 try `"%kernel.root_dir%/../web/uploads"` instead.
I think you forgot a `%` car. in your config.yml file.

Regards

**Comment by edvinasnet** [comment]
@picks44 maybe are you using symlinks to cached image? I have same error with deployer and symlinks

**Comment by robfrawley** [comment]
@picks44 You absolutely forgot a `%`. Variables (or, more accurately, string replacements) in Symfony config files must be surrounded by `%` characters, for example: `%kernel.root_dir%`.

**Comment by robfrawley** [comment]
> To me this new config is not really "user-friendly"...

@picks44 This configuration isn't **new**, the root check is simply more secure, and takes symbolic links into account. If you aren't using symbolic links there is no need to set this configuration option. What is **new** is the ability to define multiple root paths.

**Comment by robfrawley** [comment]
Version [1.7.1](https://github.com/liip/LiipImagineBundle/releases/tag/1.7.1) released with multiple data roots support.

**Comment by picks44** [comment]
@robfrawley @edvinasnet @adaniloff Thanks, sorry for my basic mistake, I went over too quickly... Will try this new version.

**Comment by picks44** [comment]
It's strange, on my dev env (WIndows), I don't need to use the data_root option, but in prod env (Debian) it's looks like i do. Basically my assets are in the web/bundle/mybundle/images (hard copy) and in web/uploads/* (several folders for several types of uploads). Do I need to set a data_root for EVERY folder ?

**Comment by robfrawley** [comment]
@picks44 If they are symbolic links, yes (you should set their *destination* as `data_root` paths). If they are regular folders, then no.

**Comment by robfrawley** [comment]
@picks44 You can determine if any symbolic links exist using the `find` command 
```
find /web-server-root/src/web/ -type l
```

**Comment by robfrawley** [comment]
For example, given the following folders within `%kernel.root_dir%/../web`
```
uploads/ (as regular folder)
other/ (as regular folder)
more/ (as regular folder)
symlink/ (as symbolic link to /some/other/path)
```
You would have the following as your config for `data_root`
```yml
data_root:
  - %kernel.root_dir%/../web
  - /some/other/path
```

**Comment by robfrawley** [comment]
@picks44 Is you issue resolved?

**Comment by garak** [comment]
I'm getting the same issue. Thumbnails are not working anymore since last upgrade. I can't get any error in logs. Configuration in dev looks fine, there is a `data`root` defauit option set when I run `console debug:configuration liip_image`. but in prod is not working  :disappointed:

**Comment by garak** [comment]
OK I managed to log errors and I found the following:
```
Liip\ImagineBundle\Exception\Binary\Loader\NotLoadableException: Source image invalid "/myvhost/shared/web/media/lego-lsp_58820aba57b79.jpg" as it is outside of the defined root path in /myvhost/releases/20170123091600/vendor/liip/imagine-bundle/Binary/Loader/FileSystemLoader.php:67
```

I'm using capifony for deploy, I think that's a pretty common solution. How could be possible that you broke it on a minor release? :disappointed_relieved:

**Comment by picks44** [comment]
@garak I'm using Capifony to deploy too, and I'm currently trying to get this working. Will give you some updates soon.

**Comment by garak** [comment]
Solved with following config:
```yaml
liip_imagine:
    # ...
    # see https://github.com/liip/LiipImagineBundle/issues/849
    loaders:
        default:
            filesystem:
                data_root: 
                    - "%kernel.root_dir%/../web"
                    - "%kernel.root_dir%/../../../shared/web"
```

**Comment by picks44** [comment]
@garak yes I was trying this also. Did you put this in your config.yml or config_prod.yml ?

**Comment by garak** [comment]
When I tried to debug this problem I checked `ImagineController` and I wonder why every exception is not logged? I mean something like `$this->error($e->getMessage)`. This could improve a lot the ability of finding such problems in production

**Comment by garak** [comment]
I put it directly in `config.yml`, but now you let me think about it maybe `config_prod.yml` is more appropriated

**Comment by picks44** [comment]
Strange, if I do this in my config.yml

```
liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web"
                    - "%kernel.root_dir%/../../../shared/web"
```

And this in my config_dev.yml

```
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web"
```

The app still takes into account the config.yml configuration... Isn't it supposed to be overwritten by config_dev.yml ?

**Comment by garak** [comment]
I think that there's no need to override your config_dev, when I tried with config only, it worked. Anyway, I then moved it to config_prod

**Comment by picks44** [comment]
@garak @robfrawley if I do not override my config.yml, then I get this error on ALL my processed images `Root image path not resolvable "C:\wamp\www\MyBundle\app/../../../shared/web"`

**Comment by robfrawley** [comment]
@picks44 You are using the wrong "slash" character in your paths: on Windows, the correct one is `\`, whereas, on Linux, the correct one is `/`. My assumption (though I don't run anything on Windows) is that PHP isn't going to automatically handle that for you: you need to use the proper slash in your paths.

Moreover, due to this statement "if I do not override my config.yml, then I get this error on ALL my processed images <error message>" it is obvious your `config_dev.yml` *is* overwriting your `config.yml` when it exists, and when you remove it, you get the error because in `config.yml` you include the invalid path: `"%kernel.root_dir%/../../../shared/web"` (which should be `"%kernel.root_dir%\..\..\..\shared\web"` on Windows).

**Comment by robfrawley** [comment]
@garak @picks44 As for when to use `config.yml`, `config_prod.yml`, `config_dev.yml`, etc:

- Always use `config.yml` for global configuration (something that should apply to ALL environments)
- Only use `config_dev.yml` for configuration that should only apply to your development environment (and not your production environment)
- Only use `config_prod.yml` for configuration that should only apply to your production environment (and not your development environment)

You use that exact same logic when overwriting configuration from the global (`config.yml`) configuration file. It is likely you should be only using `config.yml`. The only reason to use the others is if your production and development environment should use different configuration options.

**Comment by robfrawley** [comment]
@garak I'd be happy to merge a PR from you that includes additional logging statements in the `ImagineController`!

**Comment by robfrawley** [comment]
@picks44 "The app still takes into account the config.yml configuration... Isn't it supposed to be overwritten by [...]"

To clarify a bit, the configurations are not only overridden, but merged. So, with

```yml
# config.yml
liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web"
                    - "%kernel.root_dir%/../../../shared/web"
```
```yml
# config_dev.yml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web"
```

The resolved configuration for the production environment is

```yml
liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web"
                    - "%kernel.root_dir%/../../../shared/web"
```

And the resolved configuration for the development environment is
```yml
liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                   - "%kernel.root_dir%/../web"
```

**Comment by robfrawley** [comment]
@garak 

> I think that there's no need to override your config_dev, when I tried with config only, it worked. Anyway, I then moved it to config_prod

You likely want the configuration to apply to both your production and development environment. Therefore it should be in `config.yml`. See https://github.com/liip/LiipImagineBundle/issues/849#issuecomment-274540235 for additional info.

**Comment by picks44** [comment]
@robfrawley This is exactly what I'm doing and in dev environment I get the same error on all images `Root image path not resolvable "C:\wamp\www\MyBundle\app/../../../shared/web" `
This path is not resolvable because it doesn't exists in my dev environment, so why is it taken into account while my config_dev.yml doesn't mention it? And this is not a backlash or slash issue, as I have other configs like this which work like a charm.

I've also tried writing my config like this 

```
# config.yml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: ["%kernel.root_dir%/../web", "%kernel.root_dir%/../../../shared/web"]
```

```
# config_dev.yml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: ["%kernel.root_dir%/../web"]
```

But I get the exact same error (in dev mode).
