### ISSUE TITLE
Images not resolved by cache

### ISSUE THREAD

**Issue by weyandch** [liip/LiipImagineBundle#850]
I've been trying to debug this issue quite some time now, digging through old issue and documentation.

When i start with a clean /media/cache folder (proper permissions, not symlinked) after deploy, i receive lots of 404 errors when the page renders in the browser. 

`[2017-01-13 16:12:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /media/cache/avatarfilter/uploads/bst980/avatar/282c3874413d9efb83bb37a773d82245.jpeg" (from "https://website.com/incrediblepath")" at /home/www/webadmindev.vlh.de/releases/20170113151031/var/cache/prod/classes.php line 3915 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /media/cache/avatarfilter/uploads/bst980/avatar/282c3874413d9efb83bb37a773d82245.jpeg\" (from \"https://website.com/incrediblepath\") at /home/www/webadmindev.vlh.de/releases/20170113151031/var/cache/prod/classes.php:3915, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/www/webadmindev.vlh.de/releases/20170113151031/var/cache/prod/appProdProjectContainerUrlMatcher.php:893)"}`

As i get those entries in my prod.log file, i don't expect the apache config to break anything.. it's beeing processed by my application.
I'm using PHP 7.0.14, Symfony3.2.2 and LiipImagineBundle 1.6.0.

When i refresh the browsers cache, the images are properly generated. The overall configuration seems to work fine.. at least i think so...

My configuration:
```
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "/media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web"
    filter_sets:
        cache: ~
        thumb:
            quality: 50
            filters:
                resize: { size:  [64, 64] }
```

I'd be thankful for any hint, works like a charme on local machine, even with prod environment.. just the server keeps bugging me *sight
