### ISSUE TITLE
Upscale now takes lowest dimention 

### ISSUE THREAD

**Issue by Rattler3** [liip/LiipImagineBundle#855]
Since the amalgamation of upscale and downscale filters upscale works differently.

Previously the below with an input image of 200, 150 would result in an output of 600, 450. Since the new release this now outputs 533, 400.
```
liip_imagine:
    filter_sets:
        default:
            filters:
                upscale: { min: [600, 400] }
```
