### ISSUE TITLE
Bundle giving wrong root domain

### ISSUE THREAD

**Issue by veighnsche** [liip/LiipImagineBundle#869]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 2.0.x-dev

I'm probably doing something wrong, but I have a webserver at home and when I look at the thumbs, I get the correct URL. which is http://{local ip address}/media/cache/item_show_thumb/... 

But when I'm looking it from outside my network the thumb URL still starts with the local ip address.

this is my config: 

```
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        item_show_thumb:
            quality: 75
            filters:
                thumbnail: { size: [320, 180], mode: outbound }
```

As you can see I've kept it pretty vanilla. I've tried to change some settings, without success.
