### ISSUE TITLE
Wrong image path

### ISSUE THREAD

**Issue by rokasmi** [liip/LiipImagineBundle#870]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | latest (1.7.1)

Im using vich uploader to upload images and oneup flysystem file abstraction. Also liip imagine bundle to make thumbnails.

The problem is that liip takes my oneup flysystem adapters local path and tries to find `uploads/58998d6502406.png` image in it. When i remove `uploads` prefix, then it works else throws source file not found exception.

Maybe i am missing something in my configuration?

Twig:
`<img src="{{ vich_uploader_asset(partner, 'imageFile') | imagine_filter('my_thumb') }}" />` (also tried with asset)

generated url:
`http://app.dev/media/cache/resolve/my_thumb/uploads/58998d6502406.png`

url that works:
`http://app.dev/media/cache/resolve/my_thumb/58998d6502406.png`

My configuration:

```
# OneupFlysystem Configuration
    oneup_flysystem:
        adapters:
            uploads_adapter:
                local:
                    directory: "%kernel.root_dir%/../web/uploads"
        filesystems:
            uploads_fs:
                adapter: uploads_adapter
                mount:   uploads_fs
    
    # Vich uploader Configuration
    vich_uploader:
        db_driver: orm
        storage:   flysystem
        mappings:
            partner_image:
                uri_prefix: /uploads
                upload_destination: uploads_fs
                namer: vich_uploader.namer_uniqid
                delete_on_remove: true
                delete_on_update: true
            news_image:
                uri_prefix: /uploads
                upload_destination: uploads_fs
                namer: vich_uploader.namer_uniqid
                delete_on_remove: true
                delete_on_update: true
    
    # Liip imagine bundle Configuration
    liip_imagine:
        loaders:
            uploaded_images:
                flysystem:
                    filesystem_service: oneup_flysystem.uploads_fs_filesystem
        data_loader: uploaded_images
        filter_sets :
            my_thumb:
                filters:
                    thumbnail: { size: [120, 90], mode: outbound }
```

**Comment by robfrawley** [comment]
Using the `vich_uploader_asset` function means it will apply the configuration defined for `vich_uploader`. In your case, this includes a `url_prefix` which is prepending `/uploads` to the file path.

```yml
vich_uploader:
        db_driver: orm
        storage:   flysystem
        mappings:
            partner_image:
                uri_prefix: /uploads
                # ^^ this line here is prepending "/uploads" to your file path
                upload_destination: uploads_fs
                namer: vich_uploader.namer_uniqid
                delete_on_remove: true
                delete_on_update: true
```

This has nothing to due with `LiipImagineBundle`. If the path should be `/media/cache/resolve/my_thumb` and not `/media/cache/resolve/uploads/my_thumb` then you need to remove the `uri_prefix` from `vich_uploader` configuration.

You are simply passing an invalid path to this bundle, hence the "Source file not found" exception.
