### ISSUE TITLE
[BUG] 1.7.2 One FileSystemLocator for several FileSystemLoader

### ISSUE THREAD

**Issue by sebastianblum** [liip/LiipImagineBundle#874]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? |no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.2

Hello,
with release 1.7.2 our implementation is broken.

We use several FileSystemLoaders to hide the directories we store our images and to shorten the image urls. We have these config:

```iml
liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: "%kernel.root_dir%/../web"
        cache_prefix: media

  loaders:
    assets:
      filesystem:
        data_root: "%kernel.root_dir%/../web/assets/"
    default:
      filesystem:
        data_root: "%kernel.root_dir%/../web"
    guide:
      filesystem:
        data_root: "%kernel.root_dir%/../web/assets/guide"
    news:
      filesystem:
        data_root: "%kernel.root_dir%/../web/assets/news"
    press:
      filesystem:
        data_root: "%kernel.root_dir%/../web/assets/press"
```

With version 1.7.2, you introduced one FileSystemLoader service for all FileSystemLoader.

https://github.com/liip/LiipImagineBundle/blob/1.0/Binary/Locator/FileSystemLocator.php#L28
will be executed in our case 5 times with
 "%kernel.root_dir%/../web/assets/",
"%kernel.root_dir%/../web",
 "%kernel.root_dir%/../web/assets/guide",
"%kernel.root_dir%/../web/assets/news",
"%kernel.root_dir%/../web/assets/press"

and only the last configuration ("%kernel.root_dir%/../web/assets/press") is stores in $this->roots attribute.

In my opinion, we need one FileSystemLocator each FileSystemLoader.

**Comment by robfrawley** [comment]
FYI: You can skip all of this and simply pass an array now; no need to use different loaders:
```yml
liip_imagine:
  loaders:
    all:
      filesystem:
        data_root: 
          - "%kernel.root_dir%/../web/assets/"
          - "%kernel.root_dir%/../web"
          - "%kernel.root_dir%/../web/assets/guide"
          - "%kernel.root_dir%/../web/assets/news"
          - "%kernel.root_dir%/../web/assets/press"
```
That said, this is definetly a bug that requires attention.
