### ISSUE TITLE
Images not being resolved outside standard paths

### ISSUE THREAD

**Issue by AlexandreKilian** [liip/LiipImagineBundle#879]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | yes
| Imagine Bundle Version | 1.7.2

After upgrading from 1.6.0 to 1.7.2, LiipImagineBundle couldn't resolve paths outside of the application anymore. We're using a deployment tool that symlinks our uploads from a directory outside of the application ( `/shared/web/uploads` vs `/current/web/uploads` ), this worked fine in 1.6.0, with 1.7.2, the files can't be loaded anymore since it's lying outside of the configured path. Configuring the Path according to the specs didn't solve the Problem

**Comment by robfrawley** [comment]
Please see https://github.com/liip/LiipImagineBundle/blob/1.0/UPGRADE.md. You can either register all the *resolved* root paths (the directories your symbolic links point to, not the symbolic links themselves) or enable the old, insecure loader.

```yml
  # provide an array of root paths
  liip_imagine:
    loaders:
      default:
        filesystem:
          data_root:
            - /multiple/root/paths/foo
            - /multiple/root/paths/bar

    # use the old (pre 0.7.x) locator algorithm
    liip_imagine:
      loaders:
        default:
          filesystem:
            locator: filesystem_insecure
```
