### ISSUE TITLE
Public resources are denied by the default FileSystemLoader

### ISSUE THREAD

**Issue by bobvandevijver** [liip/LiipImagineBundle#881]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | yes
| BC Break Report? | yes
| Imagine Bundle Version | 1.7.2

With the release of the 1.7.2, the FileSystemLoader no longer accepts images which are not placed in the "save" data roots. However, this breaks the logic of the public resources in your src directory, if they are symlinked in the web directory. 

This asset symlinking is a commonly used option with Symfony, and therefor this should not be considered unsafe. I know it is possible to add the dataroot of these `src` resources to the configuration of this bundle, but in my opinion, that should not be necessary.

In conclusion: images installed in the `web/bundles` folder which are symlinked to the `src` bundles should not be considered unsafe.

**Comment by robfrawley** [comment]
@bobvandevijver You can either configure your data roots explicitly (yes, this does require you specify all resolved symbolic link paths) or you can switch to the old resolver algorithm.

The default moving forward is to consider symbolic links unsafe. While the usage you are describing is safe, how would you expect we determine that *all* symbolic links are safe? We can't: they could point anywhere on the file system and they bypass the intent of the `data_root` value, which is to constrain your files to the configured director[y|ies].

As for automatically detecting "safe" paths, there is no "one" way to setup a Symfony application, and there is no dependency on a `src` directory, simply a common convention. I don't find it unnecessarily complicated to define the paths *you* consider safe, versus making arbitrary decisions for the user.

```yml
# provide an array of paths to use as data roots
liip_imagine:
  loaders:
    default:
      filesystem:
        data_root:
          - "%kernel.root_dir%/../web"
          - "%kernel.root_dir%/../src/AppBundle/Resources/public"
```
```yml
# use the current locator algorithm (default)
liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem
```
```yml
# use the old locator algorithm (pre 1.7.x)
liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
```
