### ISSUE TITLE
Broken path with images over 5mbs

### ISSUE THREAD

**Issue by jorgewiva** [liip/LiipImagineBundle#894]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.7

I want to resize all the images in my app with a simple filter (reduce the quality and the size like in a 70% for example), but when I upload images around 5mb, the path breaks and it does not find the image, but somewhat I think it's a random value (maybe not 5mb at all, but smaller ones work). 

The filter's config:

```
liip_imagine:
    cache: resize_images

    resolvers:
        default:
            web_path: ~

        resize_images:
          web_path:
            web_root: "%kernel.root_dir%/../web"
            cache_prefix: "./"

    filter_sets:
        cache: ~

        media_converted:
            quality: 70
            filters:
                scale:
                    to: 0.7
```

And the twig lines:

`{{ absolute_url(asset('images_courses/'~course.imageCourse)| imagine_filter('media_converted'))}}`

Also, the folders are created inside the web folder of Symfony when it works (in this case: web/media_converted/images_courses) but inside the firebug, I can see it adds a default path as well: 

`http://local.app.com/app_dev.php/media/cache/resolve/media_converted/images_courses/7d1f89bb6bdfb24d6f3749c12f17bf51.jpeg`

I think it didn't do this before, it was just app_dev.php/media_converted/images_courses/theimage.jpg, without the media/cache/resolve, but anyways, if the image filtered works and gets uploaded, it works anyways.

Any idea on what I could be doing wrong ? 

Thanks.

**Comment by robfrawley** [comment]
The path containing `resolve` is the controller action that creates the cached image (so the URL will appear when no cached image exists for the given image/transformation). Once it is cached, that is removed and the file is directly referenced. This is __not__ new behavior.

**Comment by robfrawley** [comment]
Also, have you checked the max memory limit of your PHP installation? If it's set to something like 5mb or even 10mb, you're going to experience issues. Sometimes (though we are trying to lower this floor as much as possible) you should expect to need 2x the size of the image in memory. Possible important ini settings (depending on whether you are performing uploads or not) include:
```
post_max_size
max_file_uploads
memory_limit
```
You can find these in your `/etc/php/*/*/php.ini` file(s).

**Comment by wapcrazut** [comment]
I have this issue, but it's kind different because I'm using a 500kb image but the proportions are 6000x6000px.

I have this values in my php.ini:

```
post_max_size=256M
max_file_uploads=20
memory_limit=256M
```

**Comment by mikemix** [comment]
Unfortunately this bundle uses outdated imagine version. For instance, newer versions of imagine library introduced the `ImageInterface::THUMBNAIL_FLAG_NOCLONE` flag which reduces memory footprint dramatically with the GD driver.

**Comment by Pixelshaped** [comment]
Has the situation improved?

**Comment by sarramegnag** [comment]
Got the same issue with this file https://unsplash.com/photos/idmvPhF8t4E. It's 4592x3448 and 1.69MB. PHP memory limit is 128MB.
It fails with GD but works with Imagick.

Configuration :
```yaml
liip_imagine:
    driver: imagick
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        post_banner:
            quality: 75
            filters:
                thumbnail: { size: [1000, 500], mode: outbound }
```
