### ISSUE TITLE
LiipImagine doesn't generate/save images + ignoring cache_prefix parameter.

### ISSUE THREAD

**Issue by kironet** [liip/LiipImagineBundle#897]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.7

Hello, 

I have a problem with this bundle.
It doesn't work...

Here is my config:

```
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: images/cache #or "images/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/"
    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        290x188:
            quality: 90
            jpeg_quality: 90
            png_compression_level: 9
            png_compression_filter: ~
            format: jpg
            filters:
                auto_rotate: ~
                thumbnail  : { size : [290, 188], mode : outbound }
                strip: ~
```

Here is twig:

`<img class="img-responsive" src="{{ ('bundles/webshop/img/apple/models/' ~ product.model.image) | imagine_filter('290x188') }}"/>`
or
`<img class="img-responsive" src="{{ asset('bundles/webshop/img/apple/models/' ~ product.model.image) | imagine_filter('290x188') }}"/>`

Here is output:

> https://www.domain.cz/media/cache/resolve/290x188/bundles/webshop/img/apple/models/macbookair.png

cache_prefix is set to images/media, but in url I see media/cache.
Folders images/cache and media/cache are empty.

My php config:

```
memory_limit 2G
post_max_size 100M
upload_max_filesize 100M
```

BTW: Same liipimagine configuration is working in project with "liip/imagine-bundle": "^1.6"

//EDIT:

I tried to remove liipimagine configuration parameters and left just this:

```
liip_imagine:
    filter_sets:
        290x188:
            quality: 90
            jpeg_quality: 90
            png_compression_level: 9
            png_compression_filter: ~
            format: jpg
            filters:
                auto_rotate: ~
                thumbnail  : { size : [290, 188], mode : outbound }
                strip: ~
```

Still doesn't work.
