### ISSUE TITLE
Source image could not be found with Amazon S3

### ISSUE THREAD

**Issue by Sense** [liip/LiipImagineBundle#900]
Hello, I'm currently encountering a strange issue with the bundle. The error is the following one ; `Source image could not be found`
The log shows up the following BAD request ; `"request":"myapp.com/media/cache/resolve/thumbnail/https://s3-eu-west-1.amazonaws.com/myapp/images/project/394/thumbnails/394.jpeg"`

Here's my configuration :

```
aws:
    version:    latest
    region:     %amazon_region%
    credentials:
        key:    %amazon_key%
        secret: %amazon_secret_key%
knp_gaufrette:
    adapters:
        adapter_aws_s3_images:
            aws_s3:
                service_id: "awsS3"
                bucket_name: "%amazon_bucket_name%"
                options:
                    acl: 'public-read'
                    directory: 'images'
                    create: true
    filesystems:
        filesystem_aws_s3_images:
            adapter: adapter_aws_s3_images
    stream_wrapper: ~

liip_imagine:
    loaders:
        loader_aws_s3_images:
            stream:
                wrapper: gaufrette://filesystem_aws_s3_images/
    resolvers:
        cache_resolver_aws_s3:
           aws_s3:
               bucket: %amazon_bucket_name%
               client_config:
                   credentials:
                       key:    %amazon_key%
                       secret: %amazon_secret_key%
                   region: %amazon_region%
                   version: %amazon_version%
               get_options:
                   Scheme: 'https'
               put_options:
                   CacheControl: 'max-age=86400'
    filter_sets:
        thumbnail:
            data_loader: loader_aws_s3_images
            cache: cache_resolver_aws_s3
            quality: 100
            filters:
                thumbnail: { size: [463, 232], mode: inset }

```

and my parameters.yml, indeed ;

```
    amazon_bucket_name: myapp
    amazon_bucket_pano: pano
    amazon_bucket_url: s3-eu-west-1.amazonaws.com/myapp
    amazon_region: eu-west-1
    amazon_version: latest
```

Thank you for your help, it seems like it's something wrong with these settings as it's appending https:// at the end of `myapp.com/media/cache/resolve/thumbnail/`. Note that the real url attended of the cache images should be something like ; `https://s3-eu-west-1.amazonaws.com/myapp/images/project/394/thumbnails/394.jpeg`
