### ISSUE TITLE
Auto_rotate not working

### ISSUE THREAD

**Issue by sergiownd** [liip/LiipImagineBundle#906]
Hei guys I'm having problems with IOS images, so I've tried to use the bundle but I cant make it run. Here is my config.yml:

```
liip_imagine:
    cache: resize_images
    resolvers:
        default:
            web_path: ~

        resize_images:
          web_path:
            web_root: "%kernel.root_dir%/../web"

    filter_sets:
        cache: ~

        media_converted:
            quality: 70
            filters:
                auto_rotate: ~
                scale:
                    to: 0.7
```

If i remove the auto_rotate it works, but I need it, any idea?
Thanks
