### ISSUE TITLE
Path save after using filter

### ISSUE THREAD

**Issue by rsaenen** [liip/LiipImagineBundle#910]
| Q | A
| --- | ---
| Bug Report? | np
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.4

Hi,
I got a question about how this bundle saves images after using a filter, here is my configuration :
- I use LiipImagine as a service  
- I don't use Twig, my app is REST 
- I post the image and I save it in that folder "web/uploads/temp"
- I use the function "filterAction"
- This is my config :
```
# Liip Imagine
liip_imagine:
    resolvers:
        path_cache:
          web_path:
            web_root: '%path_uploads_full%' # ie: "root_dir/web/uploads"
            cache_prefix: '%path_prefix%' ie: "images"
    filter_sets:
        full:
            cache: path_cache
            quality: 75
            filters:
                auto_rotate: ~
                relative_resize: 
                    widen: 1920
```
- The bundle saves the image in the folder "web/uploads/images/full/uploads/temp"

Can I avoid that this bundle takes the relative path of the temp image ?
I would save my image in this web/uploads/images/full".

Thanks

**Comment by robfrawley** [comment]
The "[Cache Resolver](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolvers.html)" implementation handles saving, retrieving, and deleting the transformed image, and by default, you are using the "[Web Path Resolver](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/web_path.html)". If you want to change this behavior, you can implement your own `CacheResolver` that saves images to whatever specification you'd like (I'd suggest extending the [`WebPathResolver`](https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/WebPathResolver.php) cache resolver class in your case).

Defining a custom Cache Resolver is [thoroughly detailed in the official documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolvers.html#custom-cache-resolver), but here is a quick overview of how to do it.

- Create your custom cache resolver, either extending [`WebPathResolver`](https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/WebPathResolver.php) if you want to expand on the existing implementation or implementing the [`ResolverInterface`](https://github.com/liip/LiipImagineBundle/blob/1.0/Imagine/Cache/Resolver/ResolverInterface.php) if you want to write it from scratch.
- Define the custom class as a service in your `app/config/services.yml` file, or a bundle-specific `services.yml` file, tagging it with "name" defined as `liip_imagine.cache.resolver` as well as "resolver" defined as whatever name you'd like to call it:
  ```yml
  # app/config/services.yml
  services:
      imagine.cache.resolver.my_custom:
          class: AppBundle\Imagine\Cache\Resolver\MyCustomResolver
          arguments:
              - "@filesystem"
              - "@router"
          tags:
              - { name: "liip_imagine.cache.resolver", resolver: my_custom_cache }
  ```
- Use the name you gave it using the "resolver" tag (in this case `my_custom_cache`) to register it either globally, or per filter set:
  ```yml
  # globally use your custom cache
  liip_imagine:
    cache: my_custom_cache

  # OR use your custom custom cache for specific filters
  liip_imagine:
      filter_sets:
          my_special_style:
              cache: my_custom_cache
  ```
- Enjoy your custom cache implementation! ;-)
