### ISSUE TITLE
Do not check the existence of the directory in data_root

### ISSUE THREAD

**Issue by indapublic** [liip/LiipImagineBundle#911]
I'm using symlink on remote server, so I found LiipImagineBundle not working if I not setted data_root needed

```
loaders:
    default:
        filesystem:
            data_root:
                - "%kernel.root_dir%/../web"
                - "%kernel.root_dir%/../../my-assets/dev"
```

But on local machine I receive message (in cli)

```
[Liip\ImagineBundle\Exception\InvalidArgumentException]
Root image path not resolvable
```

because "%kernel.root_dir%/../../my-assets/dev" is not exists on my local machine.

What is the best way to pass it?
