### ISSUE TITLE
Images will still be resolved in /media/cache location

### ISSUE THREAD

**Issue by indapublic** [liip/LiipImagineBundle#912]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.4

My **liip_imagine.yml**

```
liip_imagine:

    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../../my-assets/dev"


    resolvers:
        thumbnails:
            web_path:
                web_root: "%kernel.root_dir%/../../my-assets/dev"
                cache_prefix: "uploads/thumbnails"

    filter_sets:

        book_thumb:
            quality: 100
            jpeg_quality: 100
            png_compression_level: 0
            cache: thumbnails

            filters:

                thumbnail: { size: [320, 240], mode: outbound }
```

All is fine in CLI:

```
**root@server:/var/www/my-assets/dev/uploads# /var/www/example.com/app/console liip:imagine:cache:remove**

**root@server:/var/www/my-assets/dev/uploads# /var/www/example.com/app/console liip:imagine:cache:resolve /uploads/cover/b6f65f390c824dfe9ac41109e3801b48.jpeg**
https://localhost/uploads/thumbnails/book_thumb/uploads/cover/b6f65f390c824dfe9ac41109e3801b48.jpeg
```

And **that** image displayed in browser. But the rest of the images have wrong paths, like this:

```
<img
	data-original-src="/uploads/cover/046f8fc4840b456ea0bba3a7f003b7c6.jpeg" src="https://example.com/media/cache/resolve/book_thumb/uploads/cover/046f8fc4840b456ea0bba3a7f003b7c6.jpeg"
/>
```

I guess, there is an error in my configuration file, but cannot find it.
