### ISSUE TITLE
Symfony Flex Recipe

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#924]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.7.x

I've created an initial stab at a [Symfony Flex](https://github.com/symfony/flex) contributor [recipe](https://github.com/symfony/recipes#symfony-recipes), which I'll be submitting. Take a look at [my fork of the contributor recipe repo](https://github.com/robfrawley/recipes-contrib) and the added files to support this bundle, and let me know if we should add any additional items to it.

---

See https://github.com/symfony/recipes-contrib/pull/14 for the pull request submitted against the contributed recipe repository.

**Comment by antoligy** [comment]
Great idea, and the recipe you've submitted looks like a good starting point too (We don't want to overcomplicate/prematurely overconfigure if this is a potential entrypoint for new users!).  I've posted a comment about the issue raised by the PR checker.

LGTM!

**Comment by Koc** [comment]
@robfrawley why copy-paste and not just include bundle routing file inside `routing/imagine.yaml`?

**Comment by robfrawley** [comment]
@Koc The original intention of using YAML in the Flex recipe was to lower the entry barrier for someone looking to, perhaps, edit the route paths; XML is generally more difficult for newcomers to follow or edit. Do we want to prioritize ease of use in the recipe or duplication removal?

**Comment by robfrawley** [comment]
How does everyone feel about converting our XML to YAML so it can be easily used by the recipe in a user-friendly format, as well as used in the Flex recipe through the `manifest.json` file (instead of having two copies of it).

This question only applies to the `2.x` branch as we obviously cannot remove the XML in `1.x` and break everyone's prior usage. @Koc @antoligy Thoughts?

**Comment by robfrawley** [comment]
@Koc Perhaps we can combine a few of your ideas to resolve this?

Let's change `imagine.xml` to import our new `imagine.yml` file on the `1.x` branch, and then remove the `imagine.xml` file on the `2.x` branch, giving us:

```xml
<!-- /Resources/config/routing.xml -->

<?xml version="1.0" encoding="UTF-8" ?>
<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing
        http://symfony.com/schema/routing/routing-1.0.xsd">

    <import resource="@LiipImagineBundle/Resources/config/routing.yaml" />
</routes>
```

```yaml
# /Resources/config/routing.yaml

liip_imagine_filter: 
    path: '/media/cache/resolve/{filter}/{path}'
    defaults:
        _controller: '%liip_imagine.controller.filter_action%'
    methods: 
        - GET
    requirements: 
        filter: '[A-z0-9_\-]*'
        path: .+

liip_imagine_filter_runtime: 
    path: '/media/cache/resolve/{filter}/rc/{hash}/{path}'
    defaults:
        _controller: '%liip_imagine.controller.filter_runtime_action%'
    methods: 
        - GET
    requirements: 
        filter: '[A-z0-9_\-]*'
        path: .+
```

This will allow us to immediately benefit from the change by using the `manifest.json` file to copy the routing from the package, instead of duplicating it in the recipe, while maintaining backward compatibility, and removing the backward compatibility layer from `2.x`. Turning our `manifest.json` into the following in both `1.x` and `2.x` Flex recipes:

```json
{
    "bundles": {
        "Liip\\ImagineBundle\\LiipImagineBundle": ["all"]
    },
    "copy-from-recipe": {
        "etc/": "%ETC_DIR%/"
    },
    "copy-from-package": {
        "Resources/config/routing.yaml": "%ETC_DIR%/routing/"
    }
}
```
