### ISSUE TITLE
use base64 as source?

### ISSUE THREAD

**Issue by jrswgtr** [liip/LiipImagineBundle#952]
Is there a way to use base64 as source? I tried this, but it gives a broken image (the usr.picture variable is a base64 encoded image).

`<img class="avatar" src="{{ usr.picture|imagine_filter('single_obs') }} />`

**Comment by robfrawley** [comment]
By default, you are using the file system data loader, which obviously expects to load the data from the file system. To support passing a base64 string representing the image, I'd start by registering a [custom data loader](http://symfony.com/doc/current/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader):

```php
namespace AppBundle\Imagine\Binary\Loader;

use Liip\ImagineBundle\Binary\BinaryInterface;
use Liip\ImagineBundle\Binary\Loader\LoaderInterface;
use Liip\ImagineBundle\Binary\SimpleMimeTypeGuesser;
use Liip\ImagineBundle\Model\Binary;
use Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesserInterface;

class BaseSixtyFourDataLoader implements LoaderInterface
{
    /**
     * @var SimpleMimeTypeGuesser
     */
    protected $mimeTypeGuesser;

    /**
     * @var ExtensionGuesserInterface
     */
    protected $extensionGuesser;

    /**
     * @param SimpleMimeTypeGuesser     $mimeTypeGuesser
     * @param ExtensionGuesserInterface $extensionGuesser
     */
    public function __construct(SimpleMimeTypeGuesser $mimeTypeGuesser, ExtensionGuesserInterface $extensionGuesser)
    {
        $this->mimeTypeGuesser = $mimeTypeGuesser;
        $this->extensionGuesser = $extensionGuesser;
    }

    /**
     * @param mixed $data
     *
     * @return BinaryInterface
     */
    public function find($path)
    {
        $data = base64_decode($path);
        $mime = $this->mimeTypeGuesser->guess($data);

        return new Binary($data, $mime, $this->extensionGuesser->guess($mime));
    }
}
```

Then register the data loader in your service configuration file:

```yml
# app/config/services.yml

services:
    imagine.data.loader.base_sixty_four:
        class: AppBundle\Imagine\Binary\Loader\BaseSixtyFourDataLoader
        arguments:
            - "@liip_imagine.binary.mime_type_guesser"
            - "@liip_imagine.extension_guesser"
        tags:
            - { name: "liip_imagine.binary.loader", loader: base_sixty_four_data_loader }
```

And finally, use the data loader in your bundle configuration:

```yml
# app/config/config.yml

liip_imagine:
    # set it globally for all filter sets
    data_loader: base_sixty_four_data_loader

    # OR set it for specific filter sets
    filter_sets:
        my_special_filter_set:
            data_loader: base_sixty_four_data_loader
            filters:
                # your filters
```

There are likely additional custom components you will need to create for this to work well. Reference our [official documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/index.html) for more information on how the different components hook into one another.
