### ISSUE TITLE
resizing don't coop with auto_rotation

### ISSUE THREAD

**Issue by annamakowskaespeo** [liip/LiipImagineBundle#954]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8.0

Hi! I'm trying to auto rotate image and then resize it. My problem is, that resizing filters (I tried many) don't coop with auto_rotate filter. 

For example, I have taken vertical photo by phone. This photo is saved as horizontal image 640x480 that should auto rotate to vertical.  I want to make thumbnail, that will be 120px width and will be displayed correctly (vertical). 

With configuration:
```
liip_imagine:
    driver: imagick
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        thumbi_small:
            quality: 100
            filters:
                auto_rotate: ~
                relative_resize: { widen: 120 }
```

I get image that is displayed vertical (as I wanted), but the width is 90px (height is 120px). What is surprising, this image is not physically auto_rotated - it's just displayed correctly (without auto_rotate it's displaying wrong).
How can I solve this?

example image: [image](https://soma-dev.espeo.pl/uploads/Items/2/0bc8b123eef3e1b99585779a5ab53c3f.JPG)

I have exif installed.
I have tried gd liblary, but auto_rotate is not working with it
I'm using imagick module version => 3.4.3

I have also tried configuration:
```
filters:
    auto_rotate: ~
    thumbnail: { size: [120, 200], mode: inset }
```
```
filters:
    auto_rotate: ~
    scale:
        dim: [ 120, 200 ]
```
