### ISSUE TITLE
FilesystemLoader : "not found image path" option.

### ISSUE THREAD

**Issue by theredled** [liip/LiipImagineBundle#960]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.0.0

Hi,
Problem: When a source image is not found, it makes a long Symfony request with no cache. When 100 images are not found are you're working on a local machine, it can be a nightmare.

Solution: Add an optional "not found image path" option. That image will replace the missing one, to  generate filtered etc images in the cache.

Can be added to FilesystemLoader and probably others.

Example:
```
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../var/Data"
                not_found_path: ./not-found.png

```

Note : I tried to override FilesystemLoader but it seems very very tricky - that's maybe another issue.

**Comment by robfrawley** [comment]
See our[ configuration reference](https://symfony.com/doc/current/bundles/LiipImagineBundle/configuration.html) for the `default_image` option which already allows you to return a default image when the requested one is not found. For example, you can configure a default image by adding the following to your application configuration:

```yml
liip_imagine:
  default_image: my/default/image.jpg
```

Also, creating a custom data loading is [easy and well documented](https://symfony.com/doc/current/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader), so if you ever need to do that to achieve a specific loader functionality, you shouldn't have any issue.

**Comment by theredled** [comment]
Oh, fine for `default_image`.
Creating a custom data loading is indeed easy, but override existing ones (to make custom ones) seems very tricky.

**Comment by theredled** [comment]
Unfortunately using `default_image` is not solving the performance issue: 
- Generate the path to a cache path that doesn't exist
- Client loads that path
- A full SF request is done, which eventually redirects to `default_image` (with is an absolute URL)
And next time with the same image : same long process.

Maybe I'm missing something ?

**Comment by robfrawley** [comment]
I don't believe the issue you described is part of the loader; it is instead due to other architectural decisions made during the development of this library. Regardless, setting up a custom `FileSystem` loader should be achievable using something like the following:

```php
<?php

namespace AppBundle;

use Liip\ImagineBundle\Binary\Loader\FileSystemLoader;
use Liip\ImagineBundle\Model\FileBinary;

class MyFileSystemLoader extends FileSystemLoader
{
    public function find($path)
    {
        return parent::find($path);
    }
}
```

```xml
<!-- app/config/services.xml -->

<parameters>
    <parameter key="app.data_root">/my/data/root</parameter>
</parameters>

<services>
    <service id="app.binary.loader.filesystem" class="Liip\ImagineBundle\Binary\Loader\FileSystemLoader">
        <tag name="liip_imagine.data.loader" loader="my_custom_fs_loader" />
        <argument type="service" id="app.mime_type_guesser" />
        <argument type="service" id="app.extension_guesser" />
        <argument>%app.data_root%</argument>
        <argument type="service" id="app.binary.locator.filesystem" />
    </service>

    <service id="app.binary.locator.filesystem" class="Liip\ImagineBundle\Binary\Locator\FileSystemLocator" public="false" shared="false">
    </service>

    <service id="app.mime_type_guesser" class="Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface">
        <factory class="Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser" method="getInstance" />
    </service>

    <service id="app.extension_guesser" class="Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesserInterface">
        <factory class="Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser" method="getInstance" />
    </service>
</services>
```

```yml
# app/config/config.yml

liip_imagine:
    data_loader: my_custom_fs_loader
```

**Comment by theredled** [comment]
Works with following Loader: 
````
class NotFoundLoader extends FileSystemLoader
{
    protected $rootPath;

    public function __construct(
        MimeTypeGuesserInterface $mimeTypeGuesser,
        ExtensionGuesserInterface $extensionGuesser,
        $dataRoots
    ) {
        $this->rootPath = $dataRoots;
        parent::__construct($mimeTypeGuesser, $extensionGuesser, $dataRoots);
    }

    public function find($path)
    {
        if (false !== strpos($path, '../')) {
            throw new NotLoadableException(sprintf("Source image was searched with '%s' out side of the defined root path", $path));
        }

        $absolutePath = $this->rootPath.'/'.ltrim($path, '/');

        if (false == file_exists($absolutePath)) {
            $absolutePath = $this->rootPath.'/../../web/images/not-found.png';
            //throw new NotLoadableException(sprintf('Source image not found in "%s"', $absolutePath));
        }

        $mimeType = $this->mimeTypeGuesser->guess($absolutePath);

        return new FileBinary(
            $absolutePath,
            $mimeType,
            $this->extensionGuesser->guess($mimeType)
        );
    }
}
````
services.yml:
````
    my_liip_imagine_not_found_loader:
        class: \NotFoundLoader
        arguments:
            - "@liip_imagine.mime_type_guesser"
            - "@liip_imagine.extension_guesser"
            - "%kernel.root_dir%/../var/Data"
        tags:
            - { name: "liip_imagine.binary.loader", loader: my_not_found_loader }
````
config.yml:
`````
liip_imagine:
    filter_sets:
        photo_thumb: {quality: 75, filters: {thumbnail: { size: [200, 200]}}, default_image: /images/not-found.png}
    data_loader: my_not_found_loader
`````

However, that feature should be in the native code IMO : massive performance improvement.
