### ISSUE TITLE
Resolve cache images in background not working

### ISSUE THREAD

**Issue by PeterZhukov** [liip/LiipImagineBundle#962]
I did everything that is written in this instruction:
[Resolve cache images in background](http://symfony.com/doc/current/bundles/LiipImagineBundle/resolve-cache-images-in-background.html)
My config:
```
liip_imagine:
    enqueue: true
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: 'inset', allow_upscale: true }
            #post_processors:
                #optipng: { strip_all: true, level: 5 }
                #jpegoptim: { strip_all: true, max: 10, progressive: true }

enqueue:
    transport:
        default: 'file://'
    client: ~
````

in controller:
```
$producer = $this->get('enqueue.producer');
$producer->send(Topics::RESOLVE_CACHE, new ResolveCache('test.jpg', array('my_thumb')));
```

Then in console (Windows) I do:
```
php bin\console enqueue:consume --setup-broker -vvv
```

Messages are saved to:
```
C:\Users\zhukov_p\AppData\Local\Temp\enqueue\enqueue.app.router
```
but console command watches:
```
C:\Users\zhukov_p\AppData\Local\Temp\enqueue\enqueue.app.default
```
file.

Output:

```
[debug] Set context's logger Symfony\Component\Console\Logger\ConsoleLogger
[debug] [FsDriver] Declare router exchange "enqueue.app.router" file: C:\Users\zhukov_p\AppData\Local\Temp/enqueue/enqueue.app.router
[debug] [FsDriver] Declare router queue "enqueue.app.default" file: C:\Users\zhukov_p\AppData\Local\Temp/enqueue/enqueue.app.router
[debug] [FsDriver] Declare processor queue "liip_imagine_resolve_cache" file: C:\Users\zhukov_p\AppData\Local\Temp/enqueue/liip_imagine_resolve_cache
[debug] [FsDriver] Declare processor queue "enqueue.app.default" file: C:\Users\zhukov_p\AppData\Local\Temp/enqueue/enqueue.app.default
[debug] [FsDriver] Declare processor queue "symfony_events" file: C:\Users\zhukov_p\AppData\Local\Temp/enqueue/symfony_events
```

**Comment by makasim** [comment]
@PeterZhukov what version of the imagine bundle and enqueue are you using?

**Comment by PeterZhukov** [comment]
@makasim:
```
liip/imagine-bundle: 1.8.0
enqueue/enqueue-bundle: 0.6.0
enqueue/psr-queue: 0.5.0
enqueue/fs: 0.5.0
```
I changed config to:
```
enqueue:
    transport:
        default: 'file://'
    client: ~
        router_topic: 'default'
```
and everything worked, except that later it thows exception, that `ContainerAwareProcessorRegistry` needs` Interop\Queue\PsrProcessor`, but gets `Liip\ImagineBundle\Async\ResolveCacheProcessor` that implements `Enqueue\Psr\PsrProcessor`. 

I think bug is in documentation, for example there is no such article for 2.0 version(Resolve cache images in background), only for 1.0.

**Comment by makasim** [comment]
You have to use enqueue-bundle 0.5.x as well

**Comment by makasim** [comment]
You can find doc for 2.x here: https://github.com/liip/LiipImagineBundle/blob/2.0/Resources/doc/resolve-cache-images-in-background.rst

**Comment by makasim** [comment]
The router_topic causing some problems, we will change it to default so it works from the beginning

**Comment by PeterZhukov** [comment]
@makasim very thanks, now with my last config:
```
enqueue:
    transport:
        default: 'file://'
    client:
        router_topic: 'default'
```
everything worked fine.
composer.json packages:
```
"liip/imagine-bundle": "^1.8",
"enqueue/enqueue-bundle": "^0.5.0", <-- if these versions didn't match i get an error
"enqueue/psr-queue": "^0.5.0", <-- may be this too
"enqueue/fs": "^0.5.0" <-- if these versions didn't match i get an error
```
