### ISSUE TITLE
web_path is not generating path correctly

### ISSUE THREAD

**Issue by koxder** [liip/LiipImagineBundle#968]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8.0

I have a problem when I am trying to get image from cache, I mean the first time is working fine and I get the image correctly, because the first time is not using the cache,  but in the second time, when I try to get the image I get an error:

> Warning: file_get_contents(/media/cache/default_vertical_small/default/0001/01/25_default_vertical_small.jpg): failed to open stream: No such file or directory

 Because the path is not correct, I have to remove the common slash at the path beggining to get the image correctly. To do that, I have to rewrite the function  liipImagineFilterAction and delete the first character of the path (/) after that image are working fine. I think that is something related to a misunderstanding in configuration, but right now after try all possible options is not working for me. 

Configuration:

```
liip_imagine:
    cache: web_path
    web_root: "%kernel.root_dir%/../web"
    cache_prefix: media/cache

    filter_sets:
        admin:
            quality: 100
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                upscale: { min: [100, 100] }
                thumbnail: { size: [100, 100], mode: outbound }
        default_small:
            quality: 70
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                upscale: { min: [100, 70] }
                thumbnail: { size: [100, 70], mode: outbound }
```
