### ISSUE TITLE
Not working for https 

### ISSUE THREAD

**Issue by pbabar** [liip/LiipImagineBundle#980]
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.8.0

After using imagine_filter like below 
```
<img class="img-circle img-responsive user-image" src="{{ asset(item.extra('icon-user')) | imagine_filter('user_small') }}" alt="Profile Image" title="Profile Image"/>
```

I get image url like 
http://sitedomain.com/media/cache/user_small/images/default.jpg
I want 
**https**://sitedomain.com/media/cache/user_small/images/default.jpg

My configurations are
config.yml
```
liip_imagine:
  resolvers:
    default:
      web_path: ~
            filter_sets:
               cache: ~
user_small:
      quality: 75
      filters:
        thumbnail:
          size:
            - 30
            - 30
          mode: outbound

```
