### ISSUE TITLE
Why is the image rotated automatically?

### ISSUE THREAD

**Issue by augustinfla** [liip/LiipImagineBundle#984]
| Q
| Bug Report? | yes/no ?
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.*

Hello

I do not understand why with this config liip, returns me the image in portrait mode.

Basically I have a picture in portrait mode and once the thumbnails generated it ends up at a 90 ° rotation why?

I tried deleting the auto_rotate but it does not change the problem how to make sure not to rotate the images?

Thank you.

```
view_thumb:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [650, 840], mode: outbound }
                background: { size: [650, 840], color: '#fff' }
                watermark:
                    image: Resources/views/img/watermark.png
                    size: 0.1
                    position: bottomright
```

**Comment by robfrawley** [comment]
You were right to remove the `auto_rotate` directive, but you also have to *delete the cached image* or it will not be regenerated.

**Comment by disruptual-augustin** [comment]
Yes the cache is well drained but the rotate is still active on some photo...
What is strange is that the same photo is sometimes rotate and other times no... Totally random...

**Comment by robfrawley** [comment]
Why don't you add one filter at a time and figure out which is causing your issue? It should be fairly easy to detect. Start with
```yml
view_thumb:
    quality: 75
    filters:
        thumbnail: { size: [650, 840], mode: outbound }
```

And work your way through adding the rest one by one:

```yml
view_thumb:
    quality: 75
    filters:
        thumbnail: { size: [650, 840], mode: outbound }
        # add this one second, and test
        background: { size: [650, 840], color: '#fff' }
        # add this one third, and test
        watermark:
            image: Resources/views/img/watermark.png
            size: 0.1
            position: bottomright
```

Then, perhaps, we can look at the implementation of a filter and figure out why it is behaving as you describe.
