### ISSUE TITLE
Argument 1 passed to Liip\ImagineBundle\Binary\Locator\FileSystemLocator::__construct() must be of the type array, string given

### ISSUE THREAD

**Issue by Shoplifter** [liip/LiipImagineBundle#995]
| Q | A
| --- | ---
| Bug Report? | yes?
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

I'm getting the above error message, when i am using a custum loader as described [here](http://symfony.com/doc/master/bundles/LiipImagineBundle/data-loaders.html#custom-data-loader) but with `FileSystemLocator` injected.

My configuration looks like:
services.yml
    
    AppBundle\Imagine\Binary\Loader\CustomDataLoader:
        arguments:
            $mimeGuesser: '@liip_imagine.mime_type_guesser'
            $extensionGuesser: '@liip_imagine.extension_guesser'
            $locator: '@liip_imagine.binary.locator.filesystem'
        tags:
            - { name: liip_imagine.binary.loader, loader: 'custom_data_loader' }

config.yml:    
    
    liip_imagine:
        loaders:
            default:
                filesystem:
                    data_root:
                        - "%kernel.root_dir%/Resources/images"
        data_loader: custom_data_loader
        cache: custom_cache
        filter_sets:
            ...

And this is the part in `appDevDebugProjectContainer.php` that throws the error:
`$instance->addLoader('custom_data_loader', new \AppBundle\Imagine\Binary\Loader\CustomDataLoader(${($_ = isset($this->services['liip_imagine.mime_type_guesser']) ? $this->services['liip_imagine.mime_type_guesser'] : $this->get('liip_imagine.mime_type_guesser')) && false ?: '_'}, $a, new \Liip\ImagineBundle\Binary\Locator\FileSystemLocator('')));`

I'm not sure that this is a bug, maybe I'm doing it wrong, but really cant find what that would be. I've been using CustomLoaders since recently up to version 1.8 (but then of course, $locator hasnt been in the signature of the FileSystemLoader constructor, which my CustomLoader extends)

I can post my old code working with v.1.8 here if that is helpful helpful.

**Comment by robfrawley** [comment]
The "Locator" service is setup via the [`FileSystemLoaderFactory`](https://github.com/liip/LiipImagineBundle/blob/1.0/DependencyInjection/Factory/Loader/FileSystemLoaderFactory.php). When used outside the filesystem loader, you need to properly pass an array of data roots to the locator, as the error message describes.

**Comment by Shoplifter** [comment]
I now added
````
app.binary.locator.filesystem:
    class: Liip\ImagineBundle\Binary\Locator\FileSystemLocator
        arguments: ["%kernel.root_dir%/Resources/imagine"]
````
to my service configuration and used this service id as third argument for my custom data loader, but i am still getting the same error.

**Comment by robfrawley** [comment]
First of all, your "locator" service definition is wrong. It must pass an array of root paths to as the first constructor argument, as seen in my example. Your example above should be:

```yml
app.binary.locator.filesystem:
    class: Liip\ImagineBundle\Binary\Locator\FileSystemLocator
        arguments:
          - ["%kernel.root_dir%/Resources/imagine"]
```

Furthermore, what Symfony version are you using? With Symfony >= `3.3` the following service definition works as expected:

```yml
services :

  _defaults:
    autowire: true
    public: false

  app.binary.locator.filesystem:
    class: Liip\ImagineBundle\Binary\Locator\FileSystemLocator
    arguments:
      - ["%kernel.root_dir%/Resources/imagine"]

  Liip\ImagineBundle\Binary\Locator\LocatorInterface:
    alias: app.binary.locator.filesystem

  AppBundle\CustomDataLoader:
    tags:
        - { name: liip_imagine.binary.loader, loader: 'custom_data_loader' }
```
